{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"colab":{"name":"pokemonAE_Dense_reconst_ssim_inverse.ipynb","provenance":[],"collapsed_sections":["rxbwWZcG5566","gtfq2Hr4MTas","yZDc5ASsMTbF","7m0f7a_MMTc4","cdNWtOKBMTdy","UhSTW1KSQeC_","hCPgsBp9QeDA","Qk6qBylRQeDJ","dS4QPAXoQeDX","Y8mKKa7hQeDv","M4JbbHnQQeD-","9vPAhxCyQeEQ","s5OsqNYaQeES","oEEynQF2QeET","iwDP-H8cQeEq","TdeyPBhtQeFG"],"toc_visible":true},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","metadata":{"id":"dq0MV5Xgm4ow"},"source":["**Trained and tested except Frechet**"]},{"cell_type":"code","metadata":{"id":"mjj6CMZfQd_u"},"source":["%load_ext autoreload\n","%autoreload 2"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"FaAUkhTxnzQT"},"source":["# Environment prep for Colab\n"," - download git repo \n"," - install required pip packages"]},{"cell_type":"code","metadata":{"id":"jRy-3Mj7Rn2h","executionInfo":{"status":"ok","timestamp":1604287495483,"user_tz":-60,"elapsed":2895,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"383ea85d-62ff-4c51-b45a-8298a0b491b3","colab":{"base_uri":"https://localhost:8080/"}},"source":["!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["fatal: destination path 'Generative_Models' already exists and is not an empty directory.\n","/content/Generative_Models\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0zbi2r-8nENp","scrolled":true,"executionInfo":{"status":"ok","timestamp":1604287531481,"user_tz":-60,"elapsed":38861,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"67da37d9-3f7e-4a66-e2c2-de132715d8e0","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","!pip install colorlog==4.0.2\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Mounted at /content/drive\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n","/content/Generative_Models\n","Collecting colorlog==4.0.2\n","  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl\n","Installing collected packages: colorlog\n","Successfully installed colorlog-4.0.2\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"N09gj2pVgT7R","executionInfo":{"status":"ok","timestamp":1604287531484,"user_tz":-60,"elapsed":38841,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"35b54b2a-6901-46a0-e314-0bca83cff156","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"pDUjPvxE-DA2"},"source":["# Connect Drive to save and restore results"]},{"cell_type":"code","metadata":{"id":"YqhHHzGuEAi1","executionInfo":{"status":"ok","timestamp":1604287531488,"user_tz":-60,"elapsed":37865,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"f4b18097-ee99-4d7a-b9ab-36c1d5e94fef","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"39O7_8FyQeAF"},"source":["# Settings"]},{"cell_type":"code","metadata":{"id":"A7JMGRKYQeAG","executionInfo":{"status":"ok","timestamp":1604287531491,"user_tz":-60,"elapsed":35903,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"99f38943-bb3e-4e65-d7ae-0a3ed5aaca58","colab":{"base_uri":"https://localhost:8080/"}},"source":["%env TF_KERAS = 1\n","import os\n","sep_local = os.path.sep\n","\n","import sys\n","sys.path.append('..'+sep_local+'..')\n","print(sep_local)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["env: TF_KERAS=1\n","/\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"RPwxSJHtQeAM","executionInfo":{"status":"ok","timestamp":1604287531763,"user_tz":-60,"elapsed":36155,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"5d94ddb9-75af-4eda-ae85-5c07a4825b37","colab":{"base_uri":"https://localhost:8080/"}},"source":["import tensorflow as tf\n","print(tf.__version__)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2.3.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"WjzDvWotQeAR","executionInfo":{"status":"ok","timestamp":1604287531765,"user_tz":-60,"elapsed":36128,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"59c74879-f27c-41ec-bd08-fc543da8dbc8","colab":{"base_uri":"https://localhost:8080/"}},"source":["#os.chdir('..'+sep_local+'..'+sep_local+'..'+sep_local+'..'+sep_local+'..')\n","os.chdir('/content/Generative_Models')\n","print(os.getcwd())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"sePRvXjHQeAX"},"source":["# only on colab"]},{"cell_type":"code","metadata":{"id":"jKLnMEbfQeAa"},"source":["!cat data/.pokemon/pokemon.tar.part* > data/.pokemon/pokemon.tar"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"low1ZyVAQeAh","executionInfo":{"status":"ok","timestamp":1604287533671,"user_tz":-60,"elapsed":37031,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"3ad8981e-e444-4b2f-9fd5-fd8c72460eb0","colab":{"base_uri":"https://localhost:8080/"}},"source":["!tar -xvf data/.pokemon/pokemon.tar --directory data/.pokemon/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Pokemon_LMDB/_training/\n","Pokemon_LMDB/_training/lock.mdb\n","Pokemon_LMDB/_training/data.mdb\n","Pokemon_LMDB/_validation/\n","Pokemon_LMDB/_validation/lock.mdb\n","Pokemon_LMDB/_validation/data.mdb\n","Pokemon_LMDB/meta_info.json\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"rLHNPjqY-8vS"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"rxbwWZcG5566"},"source":["# Dataset loading"]},{"cell_type":"code","metadata":{"id":"b-iYFSVT5568"},"source":["from training.generators.from_lmdb.lmdb_image_generator import get_generators"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"NywPh_82557G"},"source":["dataset_name='pokemon'\n","inputs_shape= image_shape=(100, 100, 3)\n","batch_size = 10\n","latents_dim = 100\n","intermediate_dim = 50\n","lmdb_dir = 'data/.pokemon/Pokemon_LMDB'"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"gzWP-VkK557O"},"source":["from transformation.lmdb_transformer import LmdbTransformer"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"s7EXzcta557U","executionInfo":{"status":"ok","timestamp":1604287594456,"user_tz":-60,"elapsed":6725,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"8f68718a-6cf7-400b-929a-412665df0610","colab":{"base_uri":"https://localhost:8080/"}},"source":["train_generator, val_generator = get_generators(\n","        lmdb_dir=lmdb_dir,\n","        batch_size=batch_size,\n","        episode_len=None,\n","        episode_shift=None\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/transformation/file_image_generator.py:51: UserWarning: No files found\n","  warnings.warn(msg)\n"],"name":"stderr"},{"output_type":"stream","text":["Initializing Iterator training Number of images 591\n","Initializing Iterator validation Number of images 218\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"eekZ1Dgd557f","executionInfo":{"status":"ok","timestamp":1604287598102,"user_tz":-60,"elapsed":628,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"764eb35e-a3e7-4523-b330-b9d5922d7f94","colab":{"base_uri":"https://localhost:8080/"}},"source":["_instance_scale=1.0\n","for data in val_generator:\n","    print(data['images'].numpy().max())\n","    break\n","    #print(data.keys())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"eCDHardb557k"},"source":["data['images'][0].shape"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZRFT1ycl557r","executionInfo":{"status":"ok","timestamp":1604287605933,"user_tz":-60,"elapsed":727,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"a3f0c810-8b08-4adc-c1cc-d6a4e15c978b","colab":{"base_uri":"https://localhost:8080/"}},"source":["data.keys()"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["dict_keys(['images', 'label'])"]},"metadata":{"tags":[]},"execution_count":20}]},{"cell_type":"markdown","metadata":{"id":"gtfq2Hr4MTas"},"source":["# Model's Layers definition"]},{"cell_type":"code","metadata":{"id":"FzyWqCgIMTau","executionInfo":{"status":"ok","timestamp":1604287610264,"user_tz":-60,"elapsed":703,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"099fd704-fb8a-4f54-d13c-2ccfdfd932fd","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","from collections.abc import Iterable\n","if isinstance(inputs_shape, Iterable):\n","    flat_outputs_shape = np.prod(inputs_shape)\n","flat_outputs_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["30000"]},"metadata":{"tags":[]},"execution_count":21}]},{"cell_type":"code","metadata":{"id":"E2slpbN9MTa5","executionInfo":{"status":"ok","timestamp":1604287610267,"user_tz":-60,"elapsed":680,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"c5da07aa-7d00-40fb-8a8b-d3959aa5384f","colab":{"base_uri":"https://localhost:8080/"}},"source":["latents_dim"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["100"]},"metadata":{"tags":[]},"execution_count":22}]},{"cell_type":"code","metadata":{"id":"mrvD3cpaMTbA"},"source":["enc_lays = [tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Flatten(),\n","            tf.keras.layers.Dense(units=latents_dim)]\n","\n","dec_lays = [tf.keras.layers.Dense(units=latents_dim, activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","\n","            tf.keras.layers.Dense(units=flat_outputs_shape),\n","            tf.keras.layers.Reshape(inputs_shape)]"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"yZDc5ASsMTbF"},"source":["# Model definition"]},{"cell_type":"code","metadata":{"id":"PiSxygypMTbI","executionInfo":{"status":"ok","timestamp":1604287611783,"user_tz":-60,"elapsed":1014,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"2232b568-00b4-4ef9-b876-6f6f817dc222","colab":{"base_uri":"https://localhost:8080/"}},"source":["model_name = dataset_name+'AE_Dense_reconst_ssim_inverse'\n","experiments_dir='/content/drive/My Drive/Results'+sep_local+model_name\n","print(experiments_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"XYc9zsYCMTbP"},"source":["from training.autoencoding_basic.autoencoders.autoencoder import autoencoder as AE"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"d_F1_WWiMTbV"},"source":["variables_params = \\\n","[\n","    {\n","        'name': 'inference', \n","        'inputs_shape':inputs_shape,\n","        'outputs_shape':latents_dim,\n","        'layers': enc_lays\n","    }\n","\n","    ,\n","    \n","        {\n","        'name': 'generative', \n","        'inputs_shape':latents_dim,\n","        'outputs_shape':inputs_shape,\n","        'layers':dec_lays\n","    }\n","]"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"M7xroaffMTbe"},"source":["from utils.data_and_files.file_utils import create_if_not_exist"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"JFb53i6pMTbl"},"source":["_restore = os.path.join(experiments_dir, 'var_save_dir')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"cF-sekSFMTbv","executionInfo":{"status":"ok","timestamp":1604287612703,"user_tz":-60,"elapsed":1878,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"78616681-2ab4-40a5-c0dd-4f66aa51fd34","colab":{"base_uri":"https://localhost:8080/","height":35}},"source":["create_if_not_exist(_restore)\n","_restore"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir'"]},"metadata":{"tags":[]},"execution_count":29}]},{"cell_type":"code","metadata":{"id":"6xTRCctiMTb2"},"source":["#to restore trained model, set filepath=_restore"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":false,"id":"yKUqCILIMTcC","executionInfo":{"status":"ok","timestamp":1604287613065,"user_tz":-60,"elapsed":2211,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"a1ab0214-ddcd-4597-b8b0-59af0fb76532","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae = AE( \n","    name=model_name,\n","    latents_dim=latents_dim,\n","    batch_size=batch_size,\n","    variables_params=variables_params, \n","    filepath=_restore\n","    )"],"execution_count":null,"outputs":[{"output_type":"stream","text":["  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[31mERROR   \u001b[0m | \u001b[31mFaild to restore old models !\u001b[0m\n","  \u001b[31mERROR   \u001b[0m | \u001b[31mFaild to restore old models !\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["\n","SavedModel file does not exist at: /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir/pokemonAE_Dense_reconst_ssim_inverse_inference.hdf5/{saved_model.pbtxt|saved_model.pb}\n","\n","\n","Model: \"inference\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","dense (Dense)                (None, 100, 100, 50)      200       \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 100, 100, 50)      2550      \n","_________________________________________________________________\n","flatten (Flatten)            (None, 500000)            0         \n","_________________________________________________________________\n","dense_2 (Dense)              (None, 100)               50000100  \n","_________________________________________________________________\n","batch_normalization (BatchNo (None, 100)               400       \n","_________________________________________________________________\n","dropout (Dropout)            (None, 100)               0         \n","_________________________________________________________________\n","activity_regularization (Act (None, 100)               0         \n","_________________________________________________________________\n","inference_outputs (Activatio (None, 100)               0         \n","=================================================================\n","Total params: 50,003,250\n","Trainable params: 50,003,050\n","Non-trainable params: 200\n","_________________________________________________________________\n","\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"generative\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","generative_inputs (InputLaye [(None, 100)]             0         \n","_________________________________________________________________\n","dense_3 (Dense)              (None, 100)               10100     \n","_________________________________________________________________\n","dense_4 (Dense)              (None, 1666)              168266    \n","_________________________________________________________________\n","dense_5 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_6 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_7 (Dense)              (None, 30000)             50010000  \n","_________________________________________________________________\n","reshape (Reshape)            (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","batch_normalization_1 (Batch (None, 100, 100, 3)       12        \n","_________________________________________________________________\n","dropout_1 (Dropout)          (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","activity_regularization_1 (A (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","generative_outputs (Activati (None, 100, 100, 3)       0         \n","=================================================================\n","Total params: 55,742,822\n","Trainable params: 55,742,816\n","Non-trainable params: 6\n","_________________________________________________________________\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"a6tSA2CUMTcS"},"source":["from evaluation.quantitive_metrics.structural_similarity import prepare_ssim_multiscale\n","\n","#from statistical.losses_utilities import similarty_to_distance\n","from statistical.ae_losses import expected_loglikelihood_with_lower_bound as ellwlb"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"7j5uDDrLMTch"},"source":["def similarity_to_distance(similarity_fn):\n","    distance_fn = lambda x, y: 0.5*(1-similarity_fn(x,y))\n","    return distance_fn\n","\n","ssim = similarity_to_distance(prepare_ssim_multiscale([ae.batch_size]+ae.get_inputs_shape()))"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"vYFcWTyFMTcs","executionInfo":{"status":"ok","timestamp":1604287613077,"user_tz":-60,"elapsed":2172,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"e0d36e10-e91d-47c7-a65d-6e9be8d280c7","colab":{"base_uri":"https://localhost:8080/"}},"source":["#ae.compile(metrics=None)\n","#ae.compile()\n","ae.compile(loss={'x_logits': lambda x_true, x_logits: ssim(x_true, x_logits)})"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Model: \"pokemonAE_Dense_reconst_ssim_inverse\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","inference (Functional)       (None, 100)               50003250  \n","_________________________________________________________________\n","generative (Functional)      (None, 100, 100, 3)       55742822  \n","_________________________________________________________________\n","tf_op_layer_x_logits (Tensor [(None, 100, 100, 3)]     0         \n","=================================================================\n","Total params: 105,746,072\n","Trainable params: 105,745,866\n","Non-trainable params: 206\n","_________________________________________________________________\n","None\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0ckAyLXKMTcy","executionInfo":{"status":"ok","timestamp":1604287613079,"user_tz":-60,"elapsed":2150,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"0bf772c9-94fb-472e-a924-52b49bed89ce","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.output_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(None, 100, 100, 3)"]},"metadata":{"tags":[]},"execution_count":35}]},{"cell_type":"markdown","metadata":{"id":"7m0f7a_MMTc4"},"source":["# Callbacks"]},{"cell_type":"code","metadata":{"id":"V2dd4lXtMTc6"},"source":["from training.callbacks.sample_generation import SampleGeneration\n","from training.callbacks.save_model import ModelSaver"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"GRgVLjDIMTdC"},"source":["es = tf.keras.callbacks.EarlyStopping(\n","    monitor='val_loss', \n","    min_delta=1e-15, \n","    patience=10, \n","    verbose=1, \n","    restore_best_weights=False\n",")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"4AbL7cp9MTdL"},"source":["ms = ModelSaver(filepath=_restore)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"_Oy54_-gMTdS","executionInfo":{"status":"ok","timestamp":1604287616262,"user_tz":-60,"elapsed":1442,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"8c65ee1b-6d28-495d-bb85-d78918e575ee","colab":{"base_uri":"https://localhost:8080/"}},"source":["csv_dir = os.path.join(experiments_dir, 'csv_dir')\n","create_if_not_exist(csv_dir)\n","csv_dir = os.path.join(csv_dir, ae.name+'.csv')\n","csv_log = tf.keras.callbacks.CSVLogger(csv_dir, append=True)\n","csv_dir"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/csv_dir/pokemonAE_Dense_reconst_ssim_inverse.csv'"]},"metadata":{"tags":[]},"execution_count":39}]},{"cell_type":"code","metadata":{"id":"qhNWsycyMTdY"},"source":["image_gen_dir = os.path.join(experiments_dir, 'image_gen_dir')\n","create_if_not_exist(image_gen_dir)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"5I6roj_uMTdf"},"source":["sg = SampleGeneration(latents_shape=latents_dim, filepath=image_gen_dir, gen_freq=5, save_img=True, gray_plot=False)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Dt4p2f05MTdn"},"source":["import numpy as np"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"cdNWtOKBMTdy"},"source":["# Model Training"]},{"cell_type":"code","metadata":{"scrolled":false,"id":"qrfCAdMxMTdz","executionInfo":{"status":"ok","timestamp":1604298727080,"user_tz":-60,"elapsed":11109953,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"127df218-b901-410b-9634-454f6a02a9ce","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.fit(\n","    x=train_generator,\n","    input_kw='images',\n","    steps_per_epoch=int(5e3),\n","    epochs=int(1e6), \n","    verbose=2,\n","    callbacks=[es, ms, csv_log, sg],\n","    workers=-1,\n","    use_multiprocessing=True,\n","    validation_data=val_generator,\n","    validation_steps=int(1e4)\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Epoch 1/1000000\n","WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:297: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.\n","Instructions for updating:\n","This op will be removed after the deprecation date. Please switch to tf.sets.difference().\n","WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0381s vs `on_train_batch_end` time: 0.0695s). Check your callbacks.\n","\n","Epoch 00001: loss improved from inf to -2.20064, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 651s - loss: -2.2006e+00 - psnr: 11.0902 - total_variation: 95345.1719 - ssim_multiscale: 5.6901 - sharpdiff: 5.2676 - mean_absolute_error: 0.2230 - mean_squared_error: 0.0833 - val_loss: -1.0802e+00 - val_psnr: 10.2640 - val_total_variation: 18152.4785 - val_ssim_multiscale: 3.2459 - val_sharpdiff: 9.3705 - val_mean_absolute_error: 0.2790 - val_mean_squared_error: 0.0958\n","Epoch 2/1000000\n","\n","Epoch 00002: loss improved from -2.20064 to -2.68491, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 651s - loss: -2.6849e+00 - psnr: 12.3217 - total_variation: 97123.1016 - ssim_multiscale: 6.7080 - sharpdiff: 5.3674 - mean_absolute_error: 0.1791 - mean_squared_error: 0.0596 - val_loss: -1.0629e+00 - val_psnr: 10.0449 - val_total_variation: 14773.6035 - val_ssim_multiscale: 3.1997 - val_sharpdiff: 9.6233 - val_mean_absolute_error: 0.2879 - val_mean_squared_error: 0.1007\n","Epoch 3/1000000\n","\n","Epoch 00003: loss improved from -2.68491 to -2.72585, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 651s - loss: -2.7258e+00 - psnr: 12.4228 - total_variation: 95462.8203 - ssim_multiscale: 6.7871 - sharpdiff: 5.4592 - mean_absolute_error: 0.1761 - mean_squared_error: 0.0583 - val_loss: -1.1183e+00 - val_psnr: 10.2613 - val_total_variation: 13875.9404 - val_ssim_multiscale: 3.3171 - val_sharpdiff: 9.7011 - val_mean_absolute_error: 0.2806 - val_mean_squared_error: 0.0960\n","Epoch 4/1000000\n","\n","Epoch 00004: loss improved from -2.72585 to -2.74523, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 651s - loss: -2.7452e+00 - psnr: 12.4723 - total_variation: 94670.4375 - ssim_multiscale: 6.8237 - sharpdiff: 5.5041 - mean_absolute_error: 0.1745 - mean_squared_error: 0.0576 - val_loss: -1.0892e+00 - val_psnr: 10.1174 - val_total_variation: 12107.7227 - val_ssim_multiscale: 3.2495 - val_sharpdiff: 9.8375 - val_mean_absolute_error: 0.2870 - val_mean_squared_error: 0.0993\n","Epoch 5/1000000\n","\n","Epoch 00005: loss improved from -2.74523 to -2.75713, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 651s - loss: -2.7571e+00 - psnr: 12.5025 - total_variation: 94287.7578 - ssim_multiscale: 6.8455 - sharpdiff: 5.5282 - mean_absolute_error: 0.1734 - mean_squared_error: 0.0573 - val_loss: -1.2649e+00 - val_psnr: 10.6421 - val_total_variation: 13683.4365 - val_ssim_multiscale: 3.6279 - val_sharpdiff: 9.7841 - val_mean_absolute_error: 0.2646 - val_mean_squared_error: 0.0878\n","Epoch 6/1000000\n","\n","Epoch 00006: loss improved from -2.75713 to -2.76698, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 653s - loss: -2.7670e+00 - psnr: 12.5240 - total_variation: 93978.0000 - ssim_multiscale: 6.8628 - sharpdiff: 5.5457 - mean_absolute_error: 0.1728 - mean_squared_error: 0.0570 - val_loss: -1.3632e+00 - val_psnr: 10.9762 - val_total_variation: 13893.2725 - val_ssim_multiscale: 3.8497 - val_sharpdiff: 9.8181 - val_mean_absolute_error: 0.2491 - val_mean_squared_error: 0.0812\n","Epoch 7/1000000\n","\n","Epoch 00007: loss improved from -2.76698 to -2.77364, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 664s - loss: -2.7736e+00 - psnr: 12.5429 - total_variation: 93811.7891 - ssim_multiscale: 6.8741 - sharpdiff: 5.5572 - mean_absolute_error: 0.1721 - mean_squared_error: 0.0567 - val_loss: -1.4872e+00 - val_psnr: 11.3318 - val_total_variation: 14753.4336 - val_ssim_multiscale: 4.1333 - val_sharpdiff: 9.8042 - val_mean_absolute_error: 0.2323 - val_mean_squared_error: 0.0749\n","Epoch 8/1000000\n","\n","Epoch 00008: loss improved from -2.77364 to -2.78101, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 660s - loss: -2.7810e+00 - psnr: 12.5628 - total_variation: 93647.3047 - ssim_multiscale: 6.8869 - sharpdiff: 5.5676 - mean_absolute_error: 0.1714 - mean_squared_error: 0.0564 - val_loss: -1.4186e+00 - val_psnr: 11.2714 - val_total_variation: 13151.9600 - val_ssim_multiscale: 3.9755 - val_sharpdiff: 9.9132 - val_mean_absolute_error: 0.2399 - val_mean_squared_error: 0.0763\n","Epoch 9/1000000\n","\n","Epoch 00009: loss improved from -2.78101 to -2.78556, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 653s - loss: -2.7856e+00 - psnr: 12.5726 - total_variation: 93487.7422 - ssim_multiscale: 6.8940 - sharpdiff: 5.5767 - mean_absolute_error: 0.1712 - mean_squared_error: 0.0563 - val_loss: -1.2920e+00 - val_psnr: 11.0836 - val_total_variation: 10683.7061 - val_ssim_multiscale: 3.6993 - val_sharpdiff: 10.0682 - val_mean_absolute_error: 0.2521 - val_mean_squared_error: 0.0803\n","Epoch 10/1000000\n","\n","Epoch 00010: loss improved from -2.78556 to -2.78969, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 650s - loss: -2.7897e+00 - psnr: 12.5836 - total_variation: 93394.8125 - ssim_multiscale: 6.9013 - sharpdiff: 5.5823 - mean_absolute_error: 0.1708 - mean_squared_error: 0.0562 - val_loss: -1.2205e+00 - val_psnr: 10.8682 - val_total_variation: 10039.9355 - val_ssim_multiscale: 3.5503 - val_sharpdiff: 10.0945 - val_mean_absolute_error: 0.2597 - val_mean_squared_error: 0.0843\n","Epoch 11/1000000\n","\n","Epoch 00011: loss improved from -2.78969 to -2.79143, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 658s - loss: -2.7914e+00 - psnr: 12.5851 - total_variation: 93228.8906 - ssim_multiscale: 6.9040 - sharpdiff: 5.5913 - mean_absolute_error: 0.1708 - mean_squared_error: 0.0562 - val_loss: -1.1634e+00 - val_psnr: 10.7708 - val_total_variation: 9554.3369 - val_ssim_multiscale: 3.4297 - val_sharpdiff: 10.1111 - val_mean_absolute_error: 0.2645 - val_mean_squared_error: 0.0866\n","Epoch 12/1000000\n","\n","Epoch 00012: loss improved from -2.79143 to -2.79295, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 648s - loss: -2.7930e+00 - psnr: 12.5877 - total_variation: 93111.7812 - ssim_multiscale: 6.9068 - sharpdiff: 5.5982 - mean_absolute_error: 0.1707 - mean_squared_error: 0.0562 - val_loss: -1.1369e+00 - val_psnr: 10.7095 - val_total_variation: 8572.2295 - val_ssim_multiscale: 3.3720 - val_sharpdiff: 10.1940 - val_mean_absolute_error: 0.2673 - val_mean_squared_error: 0.0875\n","Epoch 13/1000000\n","\n","Epoch 00013: loss improved from -2.79295 to -2.79481, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 649s - loss: -2.7948e+00 - psnr: 12.5879 - total_variation: 92995.2109 - ssim_multiscale: 6.9102 - sharpdiff: 5.6035 - mean_absolute_error: 0.1708 - mean_squared_error: 0.0562 - val_loss: -1.1351e+00 - val_psnr: 10.6765 - val_total_variation: 9087.5508 - val_ssim_multiscale: 3.3702 - val_sharpdiff: 10.1443 - val_mean_absolute_error: 0.2676 - val_mean_squared_error: 0.0882\n","Epoch 14/1000000\n","\n","Epoch 00014: loss improved from -2.79481 to -2.79638, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 649s - loss: -2.7964e+00 - psnr: 12.5916 - total_variation: 92931.1250 - ssim_multiscale: 6.9132 - sharpdiff: 5.6079 - mean_absolute_error: 0.1706 - mean_squared_error: 0.0561 - val_loss: -1.1608e+00 - val_psnr: 10.7369 - val_total_variation: 9418.5156 - val_ssim_multiscale: 3.4264 - val_sharpdiff: 10.1269 - val_mean_absolute_error: 0.2650 - val_mean_squared_error: 0.0874\n","Epoch 15/1000000\n","\n","Epoch 00015: loss did not improve from -2.79638\n","5000/5000 - 648s - loss: -2.7958e+00 - psnr: 12.5889 - total_variation: 92821.1250 - ssim_multiscale: 6.9117 - sharpdiff: 5.6133 - mean_absolute_error: 0.1708 - mean_squared_error: 0.0562 - val_loss: -9.1090e-01 - val_psnr: 10.1642 - val_total_variation: 6734.9238 - val_ssim_multiscale: 2.8995 - val_sharpdiff: 10.2581 - val_mean_absolute_error: 0.2885 - val_mean_squared_error: 0.0991\n","Epoch 16/1000000\n","\n","Epoch 00016: loss improved from -2.79638 to -2.79792, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 652s - loss: -2.7979e+00 - psnr: 12.5915 - total_variation: 92767.4297 - ssim_multiscale: 6.9158 - sharpdiff: 5.6170 - mean_absolute_error: 0.1707 - mean_squared_error: 0.0561 - val_loss: -1.1432e+00 - val_psnr: 10.7287 - val_total_variation: 9251.2383 - val_ssim_multiscale: 3.3928 - val_sharpdiff: 10.1303 - val_mean_absolute_error: 0.2653 - val_mean_squared_error: 0.0875\n","Epoch 17/1000000\n","\n","Epoch 00017: loss improved from -2.79792 to -2.79854, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_ssim_inverse/var_save_dir\n","5000/5000 - 652s - loss: -2.7985e+00 - psnr: 12.5946 - total_variation: 92702.7188 - ssim_multiscale: 6.9171 - sharpdiff: 5.6208 - mean_absolute_error: 0.1706 - mean_squared_error: 0.0561 - val_loss: -1.1234e+00 - val_psnr: 10.6443 - val_total_variation: 9214.5264 - val_ssim_multiscale: 3.3586 - val_sharpdiff: 10.1337 - val_mean_absolute_error: 0.2675 - val_mean_squared_error: 0.0891\n","Epoch 00017: early stopping\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["<tensorflow.python.keras.callbacks.History at 0x7f4bc943bf98>"]},"metadata":{"tags":[]},"execution_count":43}]},{"cell_type":"markdown","metadata":{"id":"UhSTW1KSQeC_"},"source":["# Model Evaluation"]},{"cell_type":"markdown","metadata":{"id":"hCPgsBp9QeDA"},"source":["## inception_score"]},{"cell_type":"code","metadata":{"id":"w0wPQHi0QeDB"},"source":["from evaluation.generativity_metrics.inception_metrics import inception_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"7c7I66B9QeDF","executionInfo":{"status":"ok","timestamp":1604315257802,"user_tz":-60,"elapsed":27636792,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"980c3f01-05df-4924-b6c8-406bc0af70f8","colab":{"base_uri":"https://localhost:8080/"}},"source":["is_mean, is_sigma = inception_score(ae, tolerance_threshold=1e-6, max_iteration=300)\n","print(f'inception_score mean: {is_mean.compute()}, sigma: {is_sigma.compute()}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5\n","87916544/87910968 [==============================] - 1s 0us/step\n","calculating the inception_score mean ...\n","WARNING:tensorflow:Model was constructed with shape (None, 75, 75, 3) for input Tensor(\"input_1:0\", shape=(None, 75, 75, 3), dtype=float32), but it was called on an input with incompatible shape (None, 100, 100, 3).\n"],"name":"stdout"},{"output_type":"stream","text":["300it [2:16:12, 27.18s/it]"],"name":"stderr"},{"output_type":"stream","text":["calculating the inception_score sigma ...\n"],"name":"stdout"},{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/dask/array/routines.py:780: RuntimeWarning: Degrees of freedom <= 0 for slice\n","  warnings.warn(\"Degrees of freedom <= 0 for slice\", RuntimeWarning)\n","0it [00:00, ?it/s]/usr/local/lib/python3.6/dist-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide\n","  return func(*(_execute_task(a, cache) for a in args))\n","1it [00:27, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","2it [00:54, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","3it [01:21, 27.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","4it [01:49, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","5it [02:17, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","6it [02:44, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","7it [03:11, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","8it [03:39, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","9it [04:06, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","10it [04:34, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","11it [05:01, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","12it [05:29, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","13it [05:56, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","14it [06:24, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","15it [06:51, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","16it [07:19, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","17it [07:47, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","18it [08:14, 27.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","19it [08:41, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","20it [09:08, 27.31s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","21it [09:35, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","22it [10:03, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","23it [10:29, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","24it [10:56, 26.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","25it [11:23, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","26it [11:50, 26.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","27it [12:17, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","28it [12:44, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","29it [13:12, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","30it [13:39, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","31it [14:06, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","32it [14:33, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","33it [15:00, 27.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","34it [15:27, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","35it [15:54, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","36it [16:22, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","37it [16:49, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","38it [17:16, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","39it [17:43, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","40it [18:10, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","41it [18:37, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","42it [19:04, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","43it [19:31, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","44it [19:58, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","45it [20:25, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","46it [20:52, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","47it [21:19, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","48it [21:46, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","49it [22:13, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","50it [22:40, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","51it [23:08, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","52it [23:34, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","53it [24:01, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","54it [24:28, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","55it [24:55, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","56it [25:22, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","57it [25:49, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","58it [26:16, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","59it [26:43, 26.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","60it [27:10, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","61it [27:37, 26.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","62it [28:05, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","63it [28:32, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","64it [28:59, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","65it [29:25, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","66it [29:52, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","67it [30:19, 26.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","68it [30:46, 26.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","69it [31:13, 26.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","70it [31:40, 26.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","71it [32:07, 26.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","72it [32:34, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","73it [33:01, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","74it [33:28, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","75it [33:55, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","76it [34:22, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","77it [34:49, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","78it [35:16, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","79it [35:43, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","80it [36:10, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","81it [36:37, 26.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","82it [37:04, 26.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","83it [37:31, 26.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","84it [37:58, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","85it [38:25, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","86it [38:52, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","87it [39:19, 26.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","88it [39:46, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","89it [40:12, 26.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","90it [40:40, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","91it [41:06, 26.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","92it [41:33, 26.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","93it [42:00, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","94it [42:27, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","95it [42:54, 26.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","96it [43:21, 26.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","97it [43:48, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","98it [44:15, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","99it [44:42, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","100it [45:09, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","101it [45:36, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","102it [46:03, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","103it [46:30, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","104it [46:57, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","105it [47:25, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","106it [47:51, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","107it [48:18, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","108it [48:46, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","109it [49:12, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","110it [49:39, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","111it [50:06, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","112it [50:33, 26.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","113it [51:00, 26.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","114it [51:27, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","115it [51:54, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","116it [52:21, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","117it [52:48, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","118it [53:15, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","119it [53:42, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","120it [54:10, 27.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","121it [54:37, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","122it [55:04, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","123it [55:31, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","124it [55:58, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","125it [56:25, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","126it [56:52, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","127it [57:19, 26.90s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","128it [57:46, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","129it [58:13, 26.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","130it [58:40, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","131it [59:08, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","132it [59:36, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","133it [1:00:03, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","134it [1:00:31, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","135it [1:00:58, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","136it [1:01:25, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","137it [1:01:52, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","138it [1:02:19, 27.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","139it [1:02:46, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","140it [1:03:13, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","141it [1:03:40, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","142it [1:04:07, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","143it [1:04:35, 27.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","144it [1:05:03, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","145it [1:05:30, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","146it [1:05:58, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","147it [1:06:25, 27.28s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","148it [1:06:52, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","149it [1:07:18, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","150it [1:07:46, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","151it [1:08:13, 27.28s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","152it [1:08:41, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","153it [1:09:09, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","154it [1:09:36, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","155it [1:10:03, 27.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","156it [1:10:30, 27.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","157it [1:10:57, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","158it [1:11:25, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","159it [1:11:53, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","160it [1:12:20, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","161it [1:12:48, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","162it [1:13:15, 27.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","163it [1:13:42, 27.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","164it [1:14:09, 27.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","165it [1:14:38, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","166it [1:15:06, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","167it [1:15:33, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","168it [1:16:00, 27.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","169it [1:16:27, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","170it [1:16:54, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","171it [1:17:23, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","172it [1:17:51, 27.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","173it [1:18:18, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","174it [1:18:44, 27.28s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","175it [1:19:12, 27.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","176it [1:19:40, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","177it [1:20:08, 27.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","178it [1:20:35, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","179it [1:21:02, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","180it [1:21:29, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","181it [1:21:57, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","182it [1:22:25, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","183it [1:22:52, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","184it [1:23:19, 27.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","185it [1:23:47, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","186it [1:24:15, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","187it [1:24:43, 27.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","188it [1:25:11, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","189it [1:25:38, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","190it [1:26:06, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","191it [1:26:34, 27.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","192it [1:27:01, 27.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","193it [1:27:29, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","194it [1:27:57, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","195it [1:28:25, 27.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","196it [1:28:52, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","197it [1:29:19, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","198it [1:29:47, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","199it [1:30:16, 27.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","200it [1:30:43, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","201it [1:31:10, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","202it [1:31:38, 27.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","203it [1:32:06, 27.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","204it [1:32:33, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","205it [1:33:01, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","206it [1:33:30, 27.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","207it [1:33:57, 27.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","208it [1:34:24, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","209it [1:34:52, 27.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","210it [1:35:21, 28.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","211it [1:35:48, 27.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","212it [1:36:16, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","213it [1:36:44, 27.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","214it [1:37:12, 27.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","215it [1:37:39, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","216it [1:38:07, 27.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","217it [1:38:35, 27.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","218it [1:39:02, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","219it [1:39:30, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","220it [1:39:59, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","221it [1:40:26, 27.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","222it [1:40:54, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","223it [1:41:23, 28.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","224it [1:41:50, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","225it [1:42:18, 27.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","226it [1:42:47, 28.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","227it [1:43:13, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","228it [1:43:42, 27.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","229it [1:44:10, 27.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","230it [1:44:38, 27.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","231it [1:45:06, 27.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","232it [1:45:34, 27.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","233it [1:46:02, 27.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","234it [1:46:30, 28.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","235it [1:46:57, 27.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","236it [1:47:25, 27.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","237it [1:47:54, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","238it [1:48:21, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","239it [1:48:50, 28.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","240it [1:49:18, 28.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","241it [1:49:46, 28.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","242it [1:50:14, 28.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","243it [1:50:42, 27.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","244it [1:51:09, 27.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","245it [1:51:38, 28.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","246it [1:52:05, 27.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","247it [1:52:34, 28.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","248it [1:53:02, 28.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","249it [1:53:30, 28.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","250it [1:53:58, 28.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","251it [1:54:26, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","252it [1:54:54, 28.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","253it [1:55:22, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","254it [1:55:50, 28.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","255it [1:56:19, 28.28s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","256it [1:56:47, 28.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","257it [1:57:15, 28.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","258it [1:57:43, 28.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","259it [1:58:11, 28.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","260it [1:58:39, 28.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","261it [1:59:07, 28.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","262it [1:59:36, 28.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","263it [2:00:03, 27.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","264it [2:00:32, 28.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","265it [2:01:00, 28.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","266it [2:01:28, 28.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","267it [2:01:56, 28.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","268it [2:02:25, 28.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","269it [2:02:53, 28.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","270it [2:03:21, 28.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","271it [2:03:49, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","272it [2:04:17, 28.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","273it [2:04:45, 28.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","274it [2:05:13, 28.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","275it [2:05:41, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","276it [2:06:10, 28.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","277it [2:06:38, 28.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","278it [2:07:06, 28.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","279it [2:07:34, 28.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","280it [2:08:03, 28.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","281it [2:08:31, 28.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","282it [2:08:59, 28.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","283it [2:09:27, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","284it [2:09:55, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","285it [2:10:23, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","286it [2:10:51, 28.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","287it [2:11:19, 28.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","288it [2:11:47, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","289it [2:12:16, 28.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","290it [2:12:44, 28.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","291it [2:13:12, 28.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","292it [2:13:40, 28.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","293it [2:14:08, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","294it [2:14:36, 28.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","295it [2:15:04, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","296it [2:15:33, 28.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","297it [2:16:01, 28.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","298it [2:16:29, 28.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","299it [2:16:57, 28.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","300it [2:17:25, 28.12s/it]"],"name":"stderr"},{"output_type":"stream","text":["inception_score mean: [9.92040901e+168], sigma: inf\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"Qk6qBylRQeDJ"},"source":["\n","## Frechet_inception_distance\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"t54Qm7_FQeDK"},"source":["from evaluation.generativity_metrics.inception_metrics import frechet_inception_distance"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"p-_KQpVPQeDP"},"source":["fis_score = frechet_inception_distance(ae, train_generator.as_numpy_iterator(), \n","                                       tolerance_threshold=1e-6, \n","                                       max_iteration=300, \n","                                       batch_size=32)\n"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"GtJ1QNcx_rt2"},"source":["print(f'frechet inception distance: {fis_score.compute()}')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"dS4QPAXoQeDX"},"source":["## perceptual_path_length_score"]},{"cell_type":"code","metadata":{"id":"FHxOntNaQeDZ"},"source":["from evaluation.generativity_metrics.perceptual_path_length import perceptual_path_length_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"FtgoCP49QeDj","executionInfo":{"status":"ok","timestamp":1604315530316,"user_tz":-60,"elapsed":27905666,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"8bdf272b-fe4f-4b62-b6a3-3b845619df65","colab":{"base_uri":"https://localhost:8080/"}},"source":["ppl_mean_score = perceptual_path_length_score(ae, train_generator.as_numpy_iterator(), \n","                                              tolerance_threshold=1e-6, \n","                                              max_iteration=300, \n","                                              batch_size=32)\n","print(f'perceptual path length score: {ppl_mean_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5\n","58892288/58889256 [==============================] - 0s 0us/step\n"],"name":"stdout"},{"output_type":"stream","text":["300it [04:29,  1.12it/s]"],"name":"stderr"},{"output_type":"stream","text":["perceptual path length score: 4936.9296875\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"l6zFWvmtQeDr"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Y8mKKa7hQeDv"},"source":["## precision score"]},{"cell_type":"code","metadata":{"id":"2VF-JOv3QeDx"},"source":["from evaluation.generativity_metrics.precision_recall import precision_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"vT1C64RdQeD5","executionInfo":{"status":"ok","timestamp":1604315530865,"user_tz":-60,"elapsed":27903852,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"99253cdb-d40d-47cb-e2e8-acd556075665","colab":{"base_uri":"https://localhost:8080/"}},"source":["_precision_score = precision_score(ae,  train_generator.as_numpy_iterator(), \n","                                   tolerance_threshold=1e-6, \n","                                   max_iteration=300)\n","print(f'precision score: {_precision_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00166249s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00171447s\n","precision score: [0.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"M4JbbHnQQeD-"},"source":["## recall score"]},{"cell_type":"code","metadata":{"id":"RhwDYty1QeEA"},"source":["from evaluation.generativity_metrics.precision_recall import recall_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LMzfn5KHQeEF","executionInfo":{"status":"ok","timestamp":1604315530869,"user_tz":-60,"elapsed":27902550,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"3dd9c0cb-9e92-499e-b1de-df8427d09807","colab":{"base_uri":"https://localhost:8080/"}},"source":["_recall_score = recall_score(ae, train_generator.as_numpy_iterator(), tolerance_threshold=1e-6, max_iteration=300)\n","print(f'recall score: {_recall_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00188971s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00184464s\n","recall score: [1.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"nQH-mfDmQeEJ"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"9vPAhxCyQeEQ"},"source":["# Image Generation"]},{"cell_type":"markdown","metadata":{"id":"s5OsqNYaQeES"},"source":["## image reconstruction"]},{"cell_type":"markdown","metadata":{"id":"oEEynQF2QeET"},"source":["### Training dataset"]},{"cell_type":"code","metadata":{"id":"Fg1wGMkRQeEU"},"source":["from training.generators.from_images.image_generation_testing import reconstruct_from_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZSJ55VozQeEZ","executionInfo":{"status":"ok","timestamp":1604315530873,"user_tz":-60,"elapsed":27901067,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"d8748119-909d-43c4-9e0e-f2e111f53d57","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 39.45it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"G1_8VcdJQeEl","executionInfo":{"status":"ok","timestamp":1604315530875,"user_tz":-60,"elapsed":27901054,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"bc80520f-ca91-48e2-a5c0-c3f015570d8f","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 43.07it/s]\n"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"iwDP-H8cQeEq"},"source":["## with Randomness"]},{"cell_type":"code","metadata":{"id":"4YXvt2J8QeEr"},"source":["from training.generators.from_images.image_generation_testing import generate_images_like_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Lxr8AimWQeEy","executionInfo":{"status":"ok","timestamp":1604315530878,"user_tz":-60,"elapsed":27901039,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"2182c815-d976-4b01-9028-eed0fae61a2f","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 43.23it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"VfEeBtsxQeE7","executionInfo":{"status":"ok","timestamp":1604315530880,"user_tz":-60,"elapsed":27901034,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"b2edfd7b-ff56-42a3-8e43-04ad1d887aeb","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 45.45it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"pHRCUI6eQeFD"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"TdeyPBhtQeFG"},"source":["### Complete Randomness"]},{"cell_type":"code","metadata":{"id":"Tr8JPmloQeFH"},"source":["from training.generators.from_images.image_generation_testing import generate_images_randomly"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"9OZuHVx2QeFK","executionInfo":{"status":"ok","timestamp":1604315531762,"user_tz":-60,"elapsed":27901893,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"b71cb448-ee8a-4831-a65d-99f1ade4ab5c","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'random_synthetic_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_randomly(ae, save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["32it [00:00, 92.74it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"Jh8HeIbMQeFR"},"source":["from training.generators.from_images.image_generation_testing import interpolate_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"oKULH_U9QeFW","executionInfo":{"status":"ok","timestamp":1604315532332,"user_tz":-60,"elapsed":27902449,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"16720956653858362116"}},"outputId":"58b08576-d9df-4933-f411-e7b145a4c6d5","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'interpolate_dir')\n","create_if_not_exist(save_dir)\n","\n","interpolate_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 113.82it/s]\n","10it [00:00, 140.13it/s]\n","0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["\n","\n","\n"],"name":"stdout"},{"output_type":"stream","text":["10it [00:00, 135.68it/s]\n","10it [00:00, 138.32it/s]\n","100%|██████████| 4/4 [00:00<00:00, 10.90it/s]\n","10it [00:00, 145.66it/s]\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"}]}]}