{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"colab":{"name":"pokemonAE_Dense_reconst_1ellwlb_01.ipynb","provenance":[],"collapsed_sections":["eCZz4Obe5572","sVfmYBee559W","PNBTrwzS55-D","UhSTW1KSQeC_","hCPgsBp9QeDA","Qk6qBylRQeDJ","dS4QPAXoQeDX","Y8mKKa7hQeDv","M4JbbHnQQeD-","s5OsqNYaQeES","oEEynQF2QeET","TdeyPBhtQeFG"],"toc_visible":true},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","metadata":{"id":"EymQpwjjoVj_"},"source":["Trained and tested except Frechet"]},{"cell_type":"code","metadata":{"id":"mjj6CMZfQd_u"},"source":["%load_ext autoreload\n","%autoreload 2"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"FaAUkhTxnzQT"},"source":["# Environment prep for Colab\n"," - download git repo \n"," - install required pip packages"]},{"cell_type":"code","metadata":{"id":"jRy-3Mj7Rn2h","executionInfo":{"status":"ok","timestamp":1604256892531,"user_tz":-60,"elapsed":29022,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"33b2f0cf-6585-4a40-b96b-0265fac47be8","colab":{"base_uri":"https://localhost:8080/"}},"source":["!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Cloning into 'Generative_Models'...\n","remote: Enumerating objects: 15891, done.\u001b[K\n","remote: Total 15891 (delta 0), reused 0 (delta 0), pack-reused 15891\u001b[K\n","Receiving objects: 100% (15891/15891), 733.46 MiB | 45.76 MiB/s, done.\n","Resolving deltas: 100% (10845/10845), done.\n","Checking out files: 100% (1697/1697), done.\n","/content/Generative_Models\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0zbi2r-8nENp","scrolled":true,"executionInfo":{"status":"ok","timestamp":1604256944585,"user_tz":-60,"elapsed":81046,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"6f5b682a-55f8-4e72-fe88-65ba8046f41d","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","!pip install colorlog==4.0.2\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Mounted at /content/drive\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n","/content/Generative_Models\n","Collecting colorlog==4.0.2\n","  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl\n","Installing collected packages: colorlog\n","Successfully installed colorlog-4.0.2\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"N09gj2pVgT7R","executionInfo":{"status":"ok","timestamp":1604256944589,"user_tz":-60,"elapsed":81015,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"48501110-a847-4a2e-f98a-e5f119e2d0b1","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"pDUjPvxE-DA2"},"source":["# Connect Drive to save and restore results"]},{"cell_type":"code","metadata":{"id":"YqhHHzGuEAi1","executionInfo":{"status":"ok","timestamp":1604256944594,"user_tz":-60,"elapsed":80987,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"5abe7e7d-7a64-4e84-ea0e-29296641f44c","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"mUIT0NXP555-"},"source":["# Settings"]},{"cell_type":"code","metadata":{"id":"vfhhLCPJ556A","executionInfo":{"status":"ok","timestamp":1604256944597,"user_tz":-60,"elapsed":80944,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"01ee6a3b-7b4f-4c91-83f8-4a82d2f28270","colab":{"base_uri":"https://localhost:8080/"}},"source":["%env TF_KERAS = 1\n","import os\n","sep_local = os.path.sep\n","\n","import sys\n","sys.path.append('..'+sep_local+'..')\n","print(sep_local)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["env: TF_KERAS=1\n","/\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"w_cq5ry8556L","executionInfo":{"status":"ok","timestamp":1604256946234,"user_tz":-60,"elapsed":82548,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"627ad538-920d-466d-84fe-dd20d3f5ecb8","colab":{"base_uri":"https://localhost:8080/"}},"source":["import tensorflow as tf\n","print(tf.__version__)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2.3.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"aGwlXRqN556W","executionInfo":{"status":"ok","timestamp":1604256946236,"user_tz":-60,"elapsed":82521,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"25479888-a8fa-481b-e848-ec328a8aa6ed","colab":{"base_uri":"https://localhost:8080/"}},"source":["#os.chdir('..'+sep_local+'..'+sep_local+'..'+sep_local+'..'+sep_local+'..')\n","os.chdir('/content/Generative_Models')\n","print(os.getcwd())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"N8pi1dTM556i"},"source":["# only on colab"]},{"cell_type":"code","metadata":{"id":"aIaxtIM5556k"},"source":["!cat data/.pokemon/pokemon.tar.part* > data/.pokemon/pokemon.tar"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZrCBqCik556t","executionInfo":{"status":"ok","timestamp":1604256947629,"user_tz":-60,"elapsed":83878,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"c1d406b8-4b5e-49ba-9d38-777d7528396e","colab":{"base_uri":"https://localhost:8080/"}},"source":["!tar -xvf data/.pokemon/pokemon.tar --directory data/.pokemon/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Pokemon_LMDB/_training/\n","Pokemon_LMDB/_training/lock.mdb\n","Pokemon_LMDB/_training/data.mdb\n","Pokemon_LMDB/_validation/\n","Pokemon_LMDB/_validation/lock.mdb\n","Pokemon_LMDB/_validation/data.mdb\n","Pokemon_LMDB/meta_info.json\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"rxbwWZcG5566"},"source":["# Dataset loading"]},{"cell_type":"code","metadata":{"id":"b-iYFSVT5568"},"source":["from training.generators.from_lmdb.lmdb_image_generator import get_generators"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"NywPh_82557G"},"source":["dataset_name='pokemon'\n","inputs_shape= image_shape=(100, 100, 3)\n","batch_size = 10\n","latents_dim = 100\n","intermediate_dim = 50\n","lmdb_dir = 'data/.pokemon/Pokemon_LMDB'"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"gzWP-VkK557O"},"source":["from transformation.lmdb_transformer import LmdbTransformer"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"s7EXzcta557U","executionInfo":{"status":"ok","timestamp":1604257089294,"user_tz":-60,"elapsed":6581,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"982248ac-5b62-46f7-ebe6-c1cfe022f21b","colab":{"base_uri":"https://localhost:8080/"}},"source":["train_generator, val_generator = get_generators(\n","        lmdb_dir=lmdb_dir,\n","        batch_size=batch_size,\n","        episode_len=None,\n","        episode_shift=None\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/transformation/file_image_generator.py:51: UserWarning: No files found\n","  warnings.warn(msg)\n"],"name":"stderr"},{"output_type":"stream","text":["Initializing Iterator training Number of images 591\n","Initializing Iterator validation Number of images 218\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"eekZ1Dgd557f","executionInfo":{"status":"ok","timestamp":1604257089319,"user_tz":-60,"elapsed":1859,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"839804ac-77ac-47d3-8356-51a6ff5f6a06","colab":{"base_uri":"https://localhost:8080/"}},"source":["_instance_scale=1.0\n","for data in val_generator:\n","    print(data['images'].numpy().max())\n","    break\n","    #print(data.keys())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"eCDHardb557k","executionInfo":{"status":"ok","timestamp":1604257092131,"user_tz":-60,"elapsed":1265,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"2cd6fee3-5396-4792-bb41-2762a8eff940","colab":{"base_uri":"https://localhost:8080/"}},"source":["data['images'][0].shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["TensorShape([100, 100, 3])"]},"metadata":{"tags":[]},"execution_count":18}]},{"cell_type":"code","metadata":{"id":"ZRFT1ycl557r","executionInfo":{"status":"ok","timestamp":1604257093452,"user_tz":-60,"elapsed":1407,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"08ed3022-7711-40da-a9fd-0a4f56ac5ca0","colab":{"base_uri":"https://localhost:8080/"}},"source":["data.keys()"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["dict_keys(['images', 'label'])"]},"metadata":{"tags":[]},"execution_count":19}]},{"cell_type":"markdown","metadata":{"id":"eCZz4Obe5572"},"source":["# Model's Layers definition"]},{"cell_type":"code","metadata":{"id":"kG5KZPmA5573","executionInfo":{"status":"ok","timestamp":1604257098335,"user_tz":-60,"elapsed":1121,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"96597286-1fea-471e-b92f-f4d6dd468f81","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","from collections.abc import Iterable\n","if isinstance(inputs_shape, Iterable):\n","    flat_outputs_shape = np.prod(inputs_shape)\n","flat_outputs_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["30000"]},"metadata":{"tags":[]},"execution_count":20}]},{"cell_type":"code","metadata":{"id":"g9SHECH9558A","executionInfo":{"status":"ok","timestamp":1604257098341,"user_tz":-60,"elapsed":1082,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"a2489139-f3af-49fb-9715-c826f5c8b88f","colab":{"base_uri":"https://localhost:8080/"}},"source":["latents_dim"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["100"]},"metadata":{"tags":[]},"execution_count":21}]},{"cell_type":"code","metadata":{"id":"oDFmTKn2558G"},"source":["enc_lays = [tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Flatten(),\n","            tf.keras.layers.Dense(units=latents_dim)]\n","\n","dec_lays = [tf.keras.layers.Dense(units=latents_dim, activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","\n","            tf.keras.layers.Dense(units=flat_outputs_shape),\n","            tf.keras.layers.Reshape(inputs_shape)]"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"UapSLGYl558M"},"source":["# Model definition"]},{"cell_type":"code","metadata":{"id":"dcDbVZzt558N","executionInfo":{"status":"ok","timestamp":1604257102093,"user_tz":-60,"elapsed":1393,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"a2b4ef51-d79f-46ce-8b97-0ccc6dbe0c7e","colab":{"base_uri":"https://localhost:8080/"}},"source":["model_name = dataset_name+'AE_Dense_reconst_1ellwlb_01'\n","experiments_dir='/content/drive/My Drive/Results'+sep_local+model_name\n","print(experiments_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"FUp7_ebd558T"},"source":["from training.autoencoding_basic.autoencoders.autoencoder import autoencoder as AE"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"pYOinQZJ558Y"},"source":["variables_params = \\\n","[\n","    {\n","        'name': 'inference', \n","        'inputs_shape':inputs_shape,\n","        'outputs_shape':latents_dim,\n","        'layers': enc_lays\n","    }\n","\n","    ,\n","    \n","        {\n","        'name': 'generative', \n","        'inputs_shape':latents_dim,\n","        'outputs_shape':inputs_shape,\n","        'layers':dec_lays\n","    }\n","]"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"QmPg7jWy558f"},"source":["from utils.data_and_files.file_utils import create_if_not_exist"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ROXA6PV0558l"},"source":["_restore = os.path.join(experiments_dir, 'var_save_dir')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"81SHKgGa558q","executionInfo":{"status":"ok","timestamp":1604257102715,"user_tz":-60,"elapsed":1922,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"2ea84046-9bc0-4b66-c6a0-1349b6ce1a40","colab":{"base_uri":"https://localhost:8080/"}},"source":["create_if_not_exist(_restore)\n","_restore"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir'"]},"metadata":{"tags":[]},"execution_count":28}]},{"cell_type":"code","metadata":{"id":"zdwdcD3G5580"},"source":["#to restore trained model, set filepath=_restore"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":false,"id":"2idCMlOV5587","executionInfo":{"status":"ok","timestamp":1604257109251,"user_tz":-60,"elapsed":8425,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"f7a72205-1751-4ebf-9ab9-af3d6193ba30","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae = AE( \n","    name=model_name,\n","    latents_dim=latents_dim,\n","    batch_size=batch_size,\n","    variables_params=variables_params, \n","    filepath=_restore\n","    )"],"execution_count":null,"outputs":[{"output_type":"stream","text":["  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"inference\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","dense (Dense)                (None, 100, 100, 50)      200       \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 100, 100, 50)      2550      \n","_________________________________________________________________\n","flatten (Flatten)            (None, 500000)            0         \n","_________________________________________________________________\n","dense_2 (Dense)              (None, 100)               50000100  \n","_________________________________________________________________\n","batch_normalization (BatchNo (None, 100)               400       \n","_________________________________________________________________\n","dropout (Dropout)            (None, 100)               0         \n","_________________________________________________________________\n","activity_regularization (Act (None, 100)               0         \n","_________________________________________________________________\n","inference_outputs (Activatio (None, 100)               0         \n","=================================================================\n","Total params: 50,003,250\n","Trainable params: 50,003,050\n","Non-trainable params: 200\n","_________________________________________________________________\n","\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"generative\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","generative_inputs (InputLaye [(None, 100)]             0         \n","_________________________________________________________________\n","dense_3 (Dense)              (None, 100)               10100     \n","_________________________________________________________________\n","dense_4 (Dense)              (None, 1666)              168266    \n","_________________________________________________________________\n","dense_5 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_6 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_7 (Dense)              (None, 30000)             50010000  \n","_________________________________________________________________\n","reshape (Reshape)            (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","batch_normalization_1 (Batch (None, 100, 100, 3)       12        \n","_________________________________________________________________\n","dropout_1 (Dropout)          (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","activity_regularization_1 (A (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","generative_outputs (Activati (None, 100, 100, 3)       0         \n","=================================================================\n","Total params: 55,742,822\n","Trainable params: 55,742,816\n","Non-trainable params: 6\n","_________________________________________________________________\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"VVzbwjcu559D"},"source":["from evaluation.quantitive_metrics.peak_signal_to_noise_ratio import prepare_psnr\n","#from statistical.losses_utilities import similarty_to_distance\n","from statistical.ae_losses import expected_loglikelihood_with_lower_bound as ellwlb"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"o_Gmeg5C559I","executionInfo":{"status":"ok","timestamp":1604257109276,"user_tz":-60,"elapsed":8413,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"aa41329b-f4c1-4a8d-9bc7-bad440fbe209","colab":{"base_uri":"https://localhost:8080/"}},"source":["#ae.compile(metrics=None)\n","#ae.compile()\n","ae.compile(loss={'x_logits': lambda x_true, x_logits: ellwlb(x_true, x_logits)+ 0.1*prepare_psnr([ae.batch_size]+ae.get_inputs_shape())(x_true, x_logits)})"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Model: \"pokemonpokemonAE_Dense_reconst_1ellwlb_01\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","inference (Functional)       (None, 100)               50003250  \n","_________________________________________________________________\n","generative (Functional)      (None, 100, 100, 3)       55742822  \n","_________________________________________________________________\n","tf_op_layer_x_logits (Tensor [(None, 100, 100, 3)]     0         \n","=================================================================\n","Total params: 105,746,072\n","Trainable params: 105,745,866\n","Non-trainable params: 206\n","_________________________________________________________________\n","None\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"HtHuJG0J559S","executionInfo":{"status":"ok","timestamp":1604257109284,"user_tz":-60,"elapsed":8395,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"c303e242-b415-4e06-9d6d-4bddf04715e7","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.output_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(None, 100, 100, 3)"]},"metadata":{"tags":[]},"execution_count":33}]},{"cell_type":"markdown","metadata":{"id":"sVfmYBee559W"},"source":["# Callbacks"]},{"cell_type":"code","metadata":{"id":"dSTEDwij559X"},"source":["from training.callbacks.sample_generation import SampleGeneration\n","from training.callbacks.save_model import ModelSaver"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"12-SyM1k559e"},"source":["es = tf.keras.callbacks.EarlyStopping(\n","    monitor='val_loss', \n","    min_delta=1e-15, \n","    patience=10, \n","    verbose=1, \n","    restore_best_weights=False\n",")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"2DjkYDq6559j"},"source":["ms = ModelSaver(filepath=_restore)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"rd0tNDN4559w","executionInfo":{"status":"ok","timestamp":1604257109307,"user_tz":-60,"elapsed":5580,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"1a0b3ac4-b720-44b4-8017-f95fa52fc8b2","colab":{"base_uri":"https://localhost:8080/"}},"source":["csv_dir = os.path.join(experiments_dir, 'csv_dir')\n","create_if_not_exist(csv_dir)\n","csv_dir = os.path.join(csv_dir, ae.name+'.csv')\n","csv_log = tf.keras.callbacks.CSVLogger(csv_dir, append=True)\n","csv_dir"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/csv_dir/pokemonpokemonAE_Dense_reconst_1ellwlb_01.csv'"]},"metadata":{"tags":[]},"execution_count":37}]},{"cell_type":"code","metadata":{"id":"Bmu9aRcw5591"},"source":["image_gen_dir = os.path.join(experiments_dir, 'image_gen_dir')\n","create_if_not_exist(image_gen_dir)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"VnLBIPXa5596"},"source":["sg = SampleGeneration(latents_shape=latents_dim, filepath=image_gen_dir, gen_freq=5, save_img=True, gray_plot=False)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"dxZ02tca559-"},"source":["import numpy as np"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"PNBTrwzS55-D"},"source":["# Model Training"]},{"cell_type":"code","metadata":{"scrolled":true,"id":"m1_Vu8ty55-E","executionInfo":{"status":"ok","timestamp":1604264325243,"user_tz":-60,"elapsed":271323,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"f08de65f-e641-4331-e22b-3ffe6c743eab","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.fit(\n","    x=train_generator,\n","    input_kw='images',\n","    steps_per_epoch=int(5e3),\n","    epochs=int(1e6), \n","    verbose=2,\n","    callbacks=[es, ms, csv_log, sg],\n","    workers=-1,\n","    use_multiprocessing=True,\n","    validation_data=val_generator,\n","    validation_steps=int(1e4)\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Epoch 1/1000000\n","\n","Epoch 00001: loss improved from inf to 3871.39233, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 601s - loss: 3871.3923 - psnr: 13.3538 - total_variation: 102582.4531 - ssim_multiscale: 6.8440 - sharpdiff: 5.3606 - mean_absolute_error: 0.1140 - mean_squared_error: 0.0470 - val_loss: 7773.0933 - val_psnr: 11.0798 - val_total_variation: 10389.0674 - val_ssim_multiscale: 3.5983 - val_sharpdiff: 10.1594 - val_mean_absolute_error: 0.2136 - val_mean_squared_error: 0.0861\n","Epoch 2/1000000\n","\n","Epoch 00002: loss improved from 3871.39233 to 3864.27783, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 605s - loss: 3864.2778 - psnr: 13.3561 - total_variation: 102722.7969 - ssim_multiscale: 6.8430 - sharpdiff: 5.3535 - mean_absolute_error: 0.1138 - mean_squared_error: 0.0469 - val_loss: 7750.7627 - val_psnr: 11.0882 - val_total_variation: 10671.4199 - val_ssim_multiscale: 3.6926 - val_sharpdiff: 10.1564 - val_mean_absolute_error: 0.2098 - val_mean_squared_error: 0.0860\n","Epoch 3/1000000\n","\n","Epoch 00003: loss did not improve from 3864.27783\n","5000/5000 - 602s - loss: 3871.5596 - psnr: 13.3577 - total_variation: 102617.3828 - ssim_multiscale: 6.8472 - sharpdiff: 5.3607 - mean_absolute_error: 0.1134 - mean_squared_error: 0.0470 - val_loss: 8442.9082 - val_psnr: 10.7311 - val_total_variation: 8249.1396 - val_ssim_multiscale: 3.2990 - val_sharpdiff: 10.3143 - val_mean_absolute_error: 0.2214 - val_mean_squared_error: 0.0939\n","Epoch 4/1000000\n","\n","Epoch 00004: loss improved from 3864.27783 to 3856.31372, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 601s - loss: 3856.3137 - psnr: 13.3680 - total_variation: 102577.6094 - ssim_multiscale: 6.8522 - sharpdiff: 5.3658 - mean_absolute_error: 0.1126 - mean_squared_error: 0.0468 - val_loss: 8071.4868 - val_psnr: 10.9323 - val_total_variation: 9675.2295 - val_ssim_multiscale: 3.4117 - val_sharpdiff: 10.2001 - val_mean_absolute_error: 0.2201 - val_mean_squared_error: 0.0892\n","Epoch 5/1000000\n","\n","Epoch 00005: loss improved from 3856.31372 to 3835.36865, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 598s - loss: 3835.3687 - psnr: 13.3783 - total_variation: 102537.2578 - ssim_multiscale: 6.8581 - sharpdiff: 5.3705 - mean_absolute_error: 0.1119 - mean_squared_error: 0.0467 - val_loss: 8113.6914 - val_psnr: 10.8967 - val_total_variation: 9631.3779 - val_ssim_multiscale: 3.5223 - val_sharpdiff: 10.2303 - val_mean_absolute_error: 0.2148 - val_mean_squared_error: 0.0900\n","Epoch 6/1000000\n","\n","Epoch 00006: loss did not improve from 3835.36865\n","5000/5000 - 598s - loss: 3846.0300 - psnr: 13.3768 - total_variation: 102472.5234 - ssim_multiscale: 6.8606 - sharpdiff: 5.3745 - mean_absolute_error: 0.1117 - mean_squared_error: 0.0468 - val_loss: 8347.0000 - val_psnr: 10.7857 - val_total_variation: 8728.7266 - val_ssim_multiscale: 3.3102 - val_sharpdiff: 10.2694 - val_mean_absolute_error: 0.2215 - val_mean_squared_error: 0.0924\n","Epoch 7/1000000\n","\n","Epoch 00007: loss improved from 3835.36865 to 3827.62524, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 599s - loss: 3827.6252 - psnr: 13.3885 - total_variation: 102387.5156 - ssim_multiscale: 6.8660 - sharpdiff: 5.3812 - mean_absolute_error: 0.1110 - mean_squared_error: 0.0466 - val_loss: 8132.5000 - val_psnr: 10.8880 - val_total_variation: 9427.0957 - val_ssim_multiscale: 3.5409 - val_sharpdiff: 10.2505 - val_mean_absolute_error: 0.2144 - val_mean_squared_error: 0.0905\n","Epoch 8/1000000\n","\n","Epoch 00008: loss improved from 3827.62524 to 3823.18921, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 599s - loss: 3823.1892 - psnr: 13.3905 - total_variation: 102357.4531 - ssim_multiscale: 6.8689 - sharpdiff: 5.3841 - mean_absolute_error: 0.1107 - mean_squared_error: 0.0466 - val_loss: 7991.5332 - val_psnr: 10.9659 - val_total_variation: 10185.2402 - val_ssim_multiscale: 3.5180 - val_sharpdiff: 10.1751 - val_mean_absolute_error: 0.2159 - val_mean_squared_error: 0.0884\n","Epoch 9/1000000\n","\n","Epoch 00009: loss did not improve from 3823.18921\n","5000/5000 - 598s - loss: 3830.5923 - psnr: 13.3903 - total_variation: 102317.2188 - ssim_multiscale: 6.8701 - sharpdiff: 5.3868 - mean_absolute_error: 0.1106 - mean_squared_error: 0.0466 - val_loss: 8663.5879 - val_psnr: 10.6377 - val_total_variation: 8071.4634 - val_ssim_multiscale: 3.2658 - val_sharpdiff: 10.3348 - val_mean_absolute_error: 0.2218 - val_mean_squared_error: 0.0961\n","Epoch 10/1000000\n","\n","Epoch 00010: loss improved from 3823.18921 to 3810.50781, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 598s - loss: 3810.5078 - psnr: 13.3983 - total_variation: 102288.9062 - ssim_multiscale: 6.8738 - sharpdiff: 5.3896 - mean_absolute_error: 0.1100 - mean_squared_error: 0.0465 - val_loss: 8585.4844 - val_psnr: 10.6625 - val_total_variation: 8274.1611 - val_ssim_multiscale: 3.3345 - val_sharpdiff: 10.3456 - val_mean_absolute_error: 0.2195 - val_mean_squared_error: 0.0954\n","Epoch 11/1000000\n","\n","Epoch 00011: loss did not improve from 3810.50781\n","5000/5000 - 597s - loss: 3816.8496 - psnr: 13.3986 - total_variation: 102230.4453 - ssim_multiscale: 6.8756 - sharpdiff: 5.3935 - mean_absolute_error: 0.1099 - mean_squared_error: 0.0465 - val_loss: 8494.2275 - val_psnr: 10.7219 - val_total_variation: 8810.7832 - val_ssim_multiscale: 3.3501 - val_sharpdiff: 10.2887 - val_mean_absolute_error: 0.2192 - val_mean_squared_error: 0.0939\n","Epoch 12/1000000\n","\n","Epoch 00012: loss improved from 3810.50781 to 3803.61353, saving model to /content/drive/My Drive/Results/pokemonpokemonAE_Dense_reconst_1ellwlb_01/var_save_dir\n","5000/5000 - 604s - loss: 3803.6135 - psnr: 13.4032 - total_variation: 102258.8750 - ssim_multiscale: 6.8751 - sharpdiff: 5.3940 - mean_absolute_error: 0.1095 - mean_squared_error: 0.0464 - val_loss: 8706.5635 - val_psnr: 10.6238 - val_total_variation: 8067.3335 - val_ssim_multiscale: 3.2277 - val_sharpdiff: 10.3371 - val_mean_absolute_error: 0.2227 - val_mean_squared_error: 0.0963\n","Epoch 00012: early stopping\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["<tensorflow.python.keras.callbacks.History at 0x7fd3c9044d30>"]},"metadata":{"tags":[]},"execution_count":41}]},{"cell_type":"markdown","metadata":{"id":"UhSTW1KSQeC_"},"source":["# Model Evaluation"]},{"cell_type":"markdown","metadata":{"id":"hCPgsBp9QeDA"},"source":["## inception_score"]},{"cell_type":"code","metadata":{"id":"w0wPQHi0QeDB"},"source":["from evaluation.generativity_metrics.inception_metrics import inception_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"7c7I66B9QeDF","executionInfo":{"status":"ok","timestamp":1604281094843,"user_tz":-60,"elapsed":12678246,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"acefc9f0-fe89-4c28-baef-db7f5b9bdac4","colab":{"base_uri":"https://localhost:8080/"}},"source":["is_mean, is_sigma = inception_score(ae, tolerance_threshold=1e-6, max_iteration=300)\n","print(f'inception_score mean: {is_mean.compute()}, sigma: {is_sigma.compute()}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5\n","87916544/87910968 [==============================] - 1s 0us/step\n","calculating the inception_score mean ...\n","WARNING:tensorflow:Model was constructed with shape (None, 75, 75, 3) for input Tensor(\"input_1:0\", shape=(None, 75, 75, 3), dtype=float32), but it was called on an input with incompatible shape (None, 100, 100, 3).\n"],"name":"stdout"},{"output_type":"stream","text":["300it [2:18:19, 26.80s/it]"],"name":"stderr"},{"output_type":"stream","text":["calculating the inception_score sigma ...\n"],"name":"stdout"},{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/dask/array/routines.py:780: RuntimeWarning: Degrees of freedom <= 0 for slice\n","  warnings.warn(\"Degrees of freedom <= 0 for slice\", RuntimeWarning)\n","0it [00:00, ?it/s]/usr/local/lib/python3.6/dist-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide\n","  return func(*(_execute_task(a, cache) for a in args))\n","1it [00:26, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","2it [00:53, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","3it [01:20, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","4it [01:46, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","5it [02:13, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","6it [02:40, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","7it [03:07, 26.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","8it [03:33, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","9it [04:00, 26.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","10it [04:27, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","11it [04:54, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","12it [05:21, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","13it [05:47, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","14it [06:14, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","15it [06:41, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","16it [07:07, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","17it [07:34, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","18it [08:01, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","19it [08:27, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","20it [08:54, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","21it [09:21, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","22it [09:48, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","23it [10:15, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","24it [10:42, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","25it [11:08, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","26it [11:35, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","27it [12:02, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","28it [12:29, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","29it [12:56, 26.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","30it [13:22, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","31it [13:49, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","32it [14:16, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","33it [14:43, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","34it [15:10, 26.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","35it [15:37, 26.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","36it [16:03, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","37it [16:30, 26.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","38it [16:57, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","39it [17:24, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","40it [17:50, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","41it [18:17, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","42it [18:44, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","43it [19:11, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","44it [19:37, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","45it [20:05, 26.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","46it [20:31, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","47it [20:58, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","48it [21:25, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","49it [21:52, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","50it [22:18, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","51it [22:45, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","52it [23:12, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","53it [23:39, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","54it [24:05, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","55it [24:32, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","56it [24:59, 26.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","57it [25:26, 26.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","58it [25:53, 26.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","59it [26:19, 26.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","60it [26:46, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","61it [27:12, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","62it [27:39, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","63it [28:06, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","64it [28:33, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","65it [28:59, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","66it [29:26, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","67it [29:53, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","68it [30:20, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","69it [30:46, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","70it [31:13, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","71it [31:39, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","72it [32:06, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","73it [32:32, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","74it [32:59, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","75it [33:26, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","76it [33:52, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","77it [34:19, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","78it [34:46, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","79it [35:12, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","80it [35:39, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","81it [36:05, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","82it [36:32, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","83it [36:58, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","84it [37:25, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","85it [37:52, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","86it [38:19, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","87it [38:45, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","88it [39:11, 26.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","89it [39:38, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","90it [40:05, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","91it [40:31, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","92it [40:58, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","93it [41:24, 26.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","94it [41:51, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","95it [42:17, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","96it [42:44, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","97it [43:10, 26.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","98it [43:37, 26.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","99it [44:03, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","100it [44:30, 26.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","101it [44:56, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","102it [45:23, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","103it [45:50, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","104it [46:16, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","105it [46:43, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","106it [47:09, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","107it [47:36, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","108it [48:02, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","109it [48:29, 26.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","110it [48:55, 26.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","111it [49:22, 26.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","112it [49:48, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","113it [50:15, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","114it [50:42, 26.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","115it [51:08, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","116it [51:35, 26.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","117it [52:02, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","118it [52:28, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","119it [52:55, 26.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","120it [53:21, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","121it [53:48, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","122it [54:14, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","123it [54:41, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","124it [55:08, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","125it [55:34, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","126it [56:01, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","127it [56:28, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","128it [56:54, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","129it [57:21, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","130it [57:47, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","131it [58:14, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","132it [58:40, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","133it [59:07, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","134it [59:33, 26.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","135it [1:00:00, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","136it [1:00:26, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","137it [1:00:53, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","138it [1:01:20, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","139it [1:01:46, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","140it [1:02:13, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","141it [1:02:39, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","142it [1:03:06, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","143it [1:03:33, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","144it [1:04:00, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","145it [1:04:27, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","146it [1:04:53, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","147it [1:05:20, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","148it [1:05:46, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","149it [1:06:13, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","150it [1:06:40, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","151it [1:07:06, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","152it [1:07:33, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","153it [1:08:00, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","154it [1:08:27, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","155it [1:08:53, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","156it [1:09:20, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","157it [1:09:46, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","158it [1:10:13, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","159it [1:10:39, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","160it [1:11:06, 26.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","161it [1:11:33, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","162it [1:12:00, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","163it [1:12:27, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","164it [1:12:53, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","165it [1:13:20, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","166it [1:13:47, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","167it [1:14:14, 26.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","168it [1:14:40, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","169it [1:15:07, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","170it [1:15:34, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","171it [1:16:00, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","172it [1:16:28, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","173it [1:16:55, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","174it [1:17:21, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","175it [1:17:48, 26.90s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","176it [1:18:15, 26.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","177it [1:18:42, 26.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","178it [1:19:09, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","179it [1:19:36, 26.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","180it [1:20:02, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","181it [1:20:29, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","182it [1:20:56, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","183it [1:21:23, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","184it [1:21:49, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","185it [1:22:16, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","186it [1:22:43, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","187it [1:23:10, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","188it [1:23:37, 26.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","189it [1:24:03, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","190it [1:24:30, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","191it [1:24:56, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","192it [1:25:23, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","193it [1:25:50, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","194it [1:26:17, 26.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","195it [1:26:43, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","196it [1:27:10, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","197it [1:27:37, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","198it [1:28:03, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","199it [1:28:30, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","200it [1:28:57, 26.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","201it [1:29:23, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","202it [1:29:50, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","203it [1:30:16, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","204it [1:30:43, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","205it [1:31:10, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","206it [1:31:36, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","207it [1:32:02, 26.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","208it [1:32:29, 26.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","209it [1:32:55, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","210it [1:33:22, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","211it [1:33:48, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","212it [1:34:14, 26.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","213it [1:34:41, 26.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","214it [1:35:07, 26.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","215it [1:35:33, 26.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","216it [1:36:00, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","217it [1:36:26, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","218it [1:36:53, 26.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","219it [1:37:19, 26.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","220it [1:37:46, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","221it [1:38:12, 26.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","222it [1:38:39, 26.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","223it [1:39:05, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","224it [1:39:32, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","225it [1:39:58, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","226it [1:40:25, 26.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","227it [1:40:51, 26.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","228it [1:41:18, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","229it [1:41:44, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","230it [1:42:11, 26.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","231it [1:42:37, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","232it [1:43:04, 26.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","233it [1:43:31, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","234it [1:43:57, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","235it [1:44:24, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","236it [1:44:50, 26.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","237it [1:45:17, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","238it [1:45:44, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","239it [1:46:10, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","240it [1:46:37, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","241it [1:47:04, 26.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","242it [1:47:30, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","243it [1:47:57, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","244it [1:48:24, 26.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","245it [1:48:51, 26.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","246it [1:49:17, 26.77s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","247it [1:49:44, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","248it [1:50:11, 26.75s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","249it [1:50:37, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","250it [1:51:04, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","251it [1:51:30, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","252it [1:51:57, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","253it [1:52:23, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","254it [1:52:50, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","255it [1:53:17, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","256it [1:53:43, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","257it [1:54:10, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","258it [1:54:36, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","259it [1:55:03, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","260it [1:55:30, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","261it [1:55:56, 26.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","262it [1:56:23, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","263it [1:56:49, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","264it [1:57:16, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","265it [1:57:42, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","266it [1:58:09, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","267it [1:58:36, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","268it [1:59:02, 26.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","269it [1:59:28, 26.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","270it [1:59:55, 26.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","271it [2:00:21, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","272it [2:00:48, 26.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","273it [2:01:14, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","274it [2:01:41, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","275it [2:02:07, 26.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","276it [2:02:33, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","277it [2:03:00, 26.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","278it [2:03:26, 26.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","279it [2:03:53, 26.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","280it [2:04:20, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","281it [2:04:46, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","282it [2:05:13, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","283it [2:05:39, 26.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","284it [2:06:05, 26.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","285it [2:06:32, 26.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","286it [2:06:59, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","287it [2:07:26, 26.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","288it [2:07:52, 26.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","289it [2:08:18, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","290it [2:08:45, 26.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","291it [2:09:12, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","292it [2:09:39, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","293it [2:10:05, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","294it [2:10:32, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","295it [2:10:59, 26.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","296it [2:11:25, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","297it [2:11:52, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","298it [2:12:18, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","299it [2:12:45, 26.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","300it [2:13:11, 26.52s/it]"],"name":"stderr"},{"output_type":"stream","text":["inception_score mean: [6.91512587e+178], sigma: inf\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"Qk6qBylRQeDJ"},"source":["\n","## Frechet_inception_distance\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"t54Qm7_FQeDK"},"source":["from evaluation.generativity_metrics.inception_metrics import frechet_inception_distance"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"p-_KQpVPQeDP","executionInfo":{"status":"error","timestamp":1604143187935,"user_tz":-60,"elapsed":1338,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"121ac6e1-8c1f-4568-8564-355bdbc24b70","colab":{"base_uri":"https://localhost:8080/","height":214}},"source":["fis_score = frechet_inception_distance(ae, train_generator.as_numpy_iterator(), \n","                                       tolerance_threshold=1e-6, \n","                                       max_iteration=300, \n","                                       batch_size=32)\n"],"execution_count":null,"outputs":[{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-40b7a1c014a0>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m fis_score = frechet_inception_distance(ae, train_generator.as_numpy_iterator(), \n\u001b[0m\u001b[1;32m      2\u001b[0m                                        \u001b[0mtolerance_threshold\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1e-6\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m                                        \u001b[0mmax_iteration\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m                                        batch_size=32)\n","\u001b[0;31mNameError\u001b[0m: name 'frechet_inception_distance' is not defined"]}]},{"cell_type":"code","metadata":{"id":"GtJ1QNcx_rt2"},"source":["print(f'frechet inception distance: {fis_score.compute()}')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"dS4QPAXoQeDX"},"source":["## perceptual_path_length_score"]},{"cell_type":"code","metadata":{"id":"FHxOntNaQeDZ"},"source":["from evaluation.generativity_metrics.perceptual_path_length import perceptual_path_length_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"FtgoCP49QeDj","executionInfo":{"status":"ok","timestamp":1604281367724,"user_tz":-60,"elapsed":272900,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"e099c70e-8138-40b2-d374-99c5baa64f89","colab":{"base_uri":"https://localhost:8080/"}},"source":["ppl_mean_score = perceptual_path_length_score(ae, train_generator.as_numpy_iterator(), \n","                                              tolerance_threshold=1e-6, \n","                                              max_iteration=300, \n","                                              batch_size=32)\n","print(f'perceptual path length score: {ppl_mean_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5\n","58892288/58889256 [==============================] - 0s 0us/step\n"],"name":"stdout"},{"output_type":"stream","text":["300it [04:30,  1.12it/s]"],"name":"stderr"},{"output_type":"stream","text":["perceptual path length score: 5077.5146484375\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"l6zFWvmtQeDr"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Y8mKKa7hQeDv"},"source":["## precision score"]},{"cell_type":"code","metadata":{"id":"2VF-JOv3QeDx"},"source":["from evaluation.generativity_metrics.precision_recall import precision_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"vT1C64RdQeD5","executionInfo":{"status":"ok","timestamp":1604281368481,"user_tz":-60,"elapsed":773,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"b8b5d2f2-7b32-4324-d471-d76afd4ccde0","colab":{"base_uri":"https://localhost:8080/"}},"source":["_precision_score = precision_score(ae,  train_generator.as_numpy_iterator(), \n","                                   tolerance_threshold=1e-6, \n","                                   max_iteration=300)\n","print(f'precision score: {_precision_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","0it [00:00, ?it/s]/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00238824s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00192547s\n","precision score: [0.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"M4JbbHnQQeD-"},"source":["## recall score"]},{"cell_type":"code","metadata":{"id":"RhwDYty1QeEA"},"source":["from evaluation.generativity_metrics.precision_recall import recall_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LMzfn5KHQeEF","executionInfo":{"status":"ok","timestamp":1604281369133,"user_tz":-60,"elapsed":672,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"81627b55-a227-4477-88cf-5be3f1c2d0e9","colab":{"base_uri":"https://localhost:8080/"}},"source":["_recall_score = recall_score(ae, train_generator.as_numpy_iterator(), tolerance_threshold=1e-6, max_iteration=300)\n","print(f'recall score: {_recall_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00192714s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00177145s\n","recall score: [1.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"nQH-mfDmQeEJ"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"9vPAhxCyQeEQ"},"source":["# Image Generation"]},{"cell_type":"markdown","metadata":{"id":"s5OsqNYaQeES"},"source":["## image reconstruction"]},{"cell_type":"markdown","metadata":{"id":"oEEynQF2QeET"},"source":["### Training dataset"]},{"cell_type":"code","metadata":{"id":"Fg1wGMkRQeEU"},"source":["from training.generators.from_images.image_generation_testing import reconstruct_from_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZSJ55VozQeEZ","executionInfo":{"status":"ok","timestamp":1604281369139,"user_tz":-60,"elapsed":99,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"69c2f568-677f-4dcb-f65e-ab9874a3e665","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 69.46it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"G1_8VcdJQeEl","executionInfo":{"status":"ok","timestamp":1604281369140,"user_tz":-60,"elapsed":78,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"bd1ec7a3-fad8-4f57-860e-d398358fafea","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 41.62it/s]\n"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"iwDP-H8cQeEq"},"source":["## with Randomness"]},{"cell_type":"code","metadata":{"id":"4YXvt2J8QeEr"},"source":["from training.generators.from_images.image_generation_testing import generate_images_like_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Lxr8AimWQeEy","executionInfo":{"status":"ok","timestamp":1604281369891,"user_tz":-60,"elapsed":785,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"d7d43a34-6f4f-4a40-fc14-1935c2107a1d","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 50.31it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"VfEeBtsxQeE7","executionInfo":{"status":"ok","timestamp":1604281369894,"user_tz":-60,"elapsed":134,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"22795a32-8bcf-4690-f6c1-33a4c593a8f3","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 43.85it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"pHRCUI6eQeFD"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"TdeyPBhtQeFG"},"source":["### Complete Randomness"]},{"cell_type":"code","metadata":{"id":"Tr8JPmloQeFH"},"source":["from training.generators.from_images.image_generation_testing import generate_images_randomly"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"9OZuHVx2QeFK","executionInfo":{"status":"ok","timestamp":1604281370317,"user_tz":-60,"elapsed":454,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"8a04f0f7-4c07-43dd-c82f-73e28c5ba8f6","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'random_synthetic_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_randomly(ae, save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["32it [00:00, 96.67it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"Jh8HeIbMQeFR"},"source":["from training.generators.from_images.image_generation_testing import interpolate_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"oKULH_U9QeFW","executionInfo":{"status":"ok","timestamp":1604281370755,"user_tz":-60,"elapsed":464,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"14943304361895926464"}},"outputId":"59007c05-295f-4e8c-9498-cb56e32e5dda","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'interpolate_dir')\n","create_if_not_exist(save_dir)\n","\n","interpolate_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 138.35it/s]\n","10it [00:00, 142.13it/s]\n","0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["\n","\n","\n"],"name":"stdout"},{"output_type":"stream","text":["10it [00:00, 139.64it/s]\n","10it [00:00, 143.66it/s]\n","100%|██████████| 4/4 [00:00<00:00, 11.75it/s]\n","10it [00:00, 140.54it/s]\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Fuhv1qXyQeFb"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"i0mPqk0UQeFg"},"source":[""],"execution_count":null,"outputs":[]}]}