{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"colab":{"name":"pokemonAE_Dense_reconst_psnr-inverse.ipynb","provenance":[],"collapsed_sections":["FaAUkhTxnzQT","pDUjPvxE-DA2","39O7_8FyQeAF","sePRvXjHQeAX","eWvSm0wmMEoa","FLYyUnFRMEpX","Qrel5s5qMErK","UhSTW1KSQeC_","9vPAhxCyQeEQ"],"toc_visible":true},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","metadata":{"id":"0BsTPqCamntV"},"source":["**Trained and tested except Frechet**"]},{"cell_type":"code","metadata":{"id":"mjj6CMZfQd_u"},"source":["%load_ext autoreload\n","%autoreload 2"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"FaAUkhTxnzQT"},"source":["# Environment prep for Colab\n"," - download git repo \n"," - install required pip packages"]},{"cell_type":"code","metadata":{"id":"jRy-3Mj7Rn2h","executionInfo":{"status":"ok","timestamp":1604286847237,"user_tz":-60,"elapsed":27806,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"3b17597e-00a1-4256-9a28-ed9035034657","colab":{"base_uri":"https://localhost:8080/"}},"source":["!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Cloning into 'Generative_Models'...\n","remote: Enumerating objects: 15891, done.\u001b[K\n","remote: Total 15891 (delta 0), reused 0 (delta 0), pack-reused 15891\u001b[K\n","Receiving objects: 100% (15891/15891), 733.46 MiB | 45.86 MiB/s, done.\n","Resolving deltas: 100% (10845/10845), done.\n","Checking out files: 100% (1697/1697), done.\n","/content/Generative_Models\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0zbi2r-8nENp","scrolled":true,"executionInfo":{"status":"ok","timestamp":1604286884732,"user_tz":-60,"elapsed":65270,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"64f5348e-72ea-4701-a434-9b21b5f384fd","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","!pip install colorlog==4.0.2\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Mounted at /content/drive\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n","/content/Generative_Models\n","Collecting colorlog==4.0.2\n","  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl\n","Installing collected packages: colorlog\n","Successfully installed colorlog-4.0.2\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"N09gj2pVgT7R","executionInfo":{"status":"ok","timestamp":1604286884736,"user_tz":-60,"elapsed":65253,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"fc04ce3d-11b0-427c-cbfe-1d4ee6bfbd23","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"pDUjPvxE-DA2"},"source":["# Connect Drive to save and restore results"]},{"cell_type":"code","metadata":{"id":"YqhHHzGuEAi1","executionInfo":{"status":"ok","timestamp":1604286884738,"user_tz":-60,"elapsed":63964,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"d2b6e71d-a4a1-44a9-a52b-187654b18ecc","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"39O7_8FyQeAF"},"source":["# Settings"]},{"cell_type":"code","metadata":{"id":"A7JMGRKYQeAG","executionInfo":{"status":"ok","timestamp":1604286884740,"user_tz":-60,"elapsed":62671,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"fa502042-08b4-4560-af7c-021cbfa7caf2","colab":{"base_uri":"https://localhost:8080/"}},"source":["%env TF_KERAS = 1\n","import os\n","sep_local = os.path.sep\n","\n","import sys\n","sys.path.append('..'+sep_local+'..')\n","print(sep_local)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["env: TF_KERAS=1\n","/\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"RPwxSJHtQeAM","executionInfo":{"status":"ok","timestamp":1604286885727,"user_tz":-60,"elapsed":63632,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"1646d2d5-5264-4c8f-e7ff-ef1dcb7a49a6","colab":{"base_uri":"https://localhost:8080/"}},"source":["import tensorflow as tf\n","print(tf.__version__)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2.3.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"WjzDvWotQeAR","executionInfo":{"status":"ok","timestamp":1604286885735,"user_tz":-60,"elapsed":63620,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"e76efd48-7280-41b3-e899-07f6c818aaaf","colab":{"base_uri":"https://localhost:8080/"}},"source":["#os.chdir('..'+sep_local+'..'+sep_local+'..'+sep_local+'..'+sep_local+'..')\n","os.chdir('/content/Generative_Models')\n","print(os.getcwd())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"sePRvXjHQeAX"},"source":["# only on colab"]},{"cell_type":"code","metadata":{"id":"jKLnMEbfQeAa"},"source":["!cat data/.pokemon/pokemon.tar.part* > data/.pokemon/pokemon.tar"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"low1ZyVAQeAh","executionInfo":{"status":"ok","timestamp":1604286887593,"user_tz":-60,"elapsed":63334,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"bd9a22d4-0a95-4aae-9cee-db5528c8af74","colab":{"base_uri":"https://localhost:8080/"}},"source":["!tar -xvf data/.pokemon/pokemon.tar --directory data/.pokemon/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Pokemon_LMDB/_training/\n","Pokemon_LMDB/_training/lock.mdb\n","Pokemon_LMDB/_training/data.mdb\n","Pokemon_LMDB/_validation/\n","Pokemon_LMDB/_validation/lock.mdb\n","Pokemon_LMDB/_validation/data.mdb\n","Pokemon_LMDB/meta_info.json\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"eWvSm0wmMEoa"},"source":["# Dataset loading"]},{"cell_type":"code","metadata":{"id":"VaGZyyaqMEoc"},"source":["from training.generators.from_lmdb.lmdb_image_generator import get_generators"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"J3RYyzA3MEow"},"source":["dataset_name='pokemon'\n","inputs_shape= image_shape=(100, 100, 3)\n","batch_size = 10\n","latents_dim = 100\n","intermediate_dim = 50\n","lmdb_dir = 'data/.pokemon/Pokemon_LMDB'"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Dwl4782EMEo1"},"source":["from transformation.lmdb_transformer import LmdbTransformer"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"pbDcP0w8MEo7","executionInfo":{"status":"ok","timestamp":1604286953354,"user_tz":-60,"elapsed":6150,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"9ae0dc3e-3340-4c25-f148-5ac30c7c20b2","colab":{"base_uri":"https://localhost:8080/"}},"source":["train_generator, val_generator = get_generators(\n","        lmdb_dir=lmdb_dir,\n","        batch_size=batch_size,\n","        episode_len=None,\n","        episode_shift=None\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/transformation/file_image_generator.py:51: UserWarning: No files found\n","  warnings.warn(msg)\n"],"name":"stderr"},{"output_type":"stream","text":["Initializing Iterator training Number of images 591\n","Initializing Iterator validation Number of images 218\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"L6PV-uvvMEpC","executionInfo":{"status":"ok","timestamp":1604286956235,"user_tz":-60,"elapsed":1304,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"fb7c4f70-8515-400e-e3c6-6c4d864101e3","colab":{"base_uri":"https://localhost:8080/"}},"source":["_instance_scale=1.0\n","for data in val_generator:\n","    print(data['images'].numpy().max())\n","    break\n","    #print(data.keys())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"-2Hcf5HeMEpJ","executionInfo":{"status":"ok","timestamp":1604286958717,"user_tz":-60,"elapsed":1108,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"48b47043-3196-4072-ca64-beb8dd87a2dc","colab":{"base_uri":"https://localhost:8080/"}},"source":["data['images'][0].shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["TensorShape([100, 100, 3])"]},"metadata":{"tags":[]},"execution_count":18}]},{"cell_type":"code","metadata":{"id":"wLxxcyA5MEpQ","executionInfo":{"status":"ok","timestamp":1604286959944,"user_tz":-60,"elapsed":1312,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"b24a3981-c317-429b-81c6-d8c4aa28cb46","colab":{"base_uri":"https://localhost:8080/"}},"source":["data.keys()"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["dict_keys(['images', 'label'])"]},"metadata":{"tags":[]},"execution_count":19}]},{"cell_type":"markdown","metadata":{"id":"FLYyUnFRMEpX"},"source":["# Model's Layers definition"]},{"cell_type":"code","metadata":{"id":"wamjX29sMEpc","executionInfo":{"status":"ok","timestamp":1604286970528,"user_tz":-60,"elapsed":877,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"63a6eb71-26b3-4ee3-e5b0-a39287df9b7c","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","from collections.abc import Iterable\n","if isinstance(inputs_shape, Iterable):\n","    flat_outputs_shape = np.prod(inputs_shape)\n","flat_outputs_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["30000"]},"metadata":{"tags":[]},"execution_count":20}]},{"cell_type":"code","metadata":{"id":"U1EtMu5qMEpm","executionInfo":{"status":"ok","timestamp":1604286970536,"user_tz":-60,"elapsed":877,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"81c49fc1-bb3c-491f-ca40-78f79efe3d52","colab":{"base_uri":"https://localhost:8080/"}},"source":["latents_dim"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["100"]},"metadata":{"tags":[]},"execution_count":21}]},{"cell_type":"code","metadata":{"id":"aJjrSHgVMEps"},"source":["enc_lays = [tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Flatten(),\n","            tf.keras.layers.Dense(units=latents_dim)]\n","\n","dec_lays = [tf.keras.layers.Dense(units=latents_dim, activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","\n","            tf.keras.layers.Dense(units=flat_outputs_shape),\n","            tf.keras.layers.Reshape(inputs_shape)]"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"WrdIr5BpMEpy"},"source":["# Model definition"]},{"cell_type":"code","metadata":{"id":"wTCGQPY5MEpz","executionInfo":{"status":"ok","timestamp":1604286979441,"user_tz":-60,"elapsed":1482,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"841e303d-24cd-41ab-d27f-3f29ff0ec49b","colab":{"base_uri":"https://localhost:8080/"}},"source":["model_name = dataset_name+'AE_Dense_reconst_psnr_inverse'\n","experiments_dir='/content/drive/My Drive/Results'+sep_local+model_name\n","print(experiments_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"Gp_6m-RpMEp8"},"source":["from training.autoencoding_basic.autoencoders.autoencoder import autoencoder as AE"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"vSjvuRwlMEqD"},"source":["variables_params = \\\n","[\n","    {\n","        'name': 'inference', \n","        'inputs_shape':inputs_shape,\n","        'outputs_shape':latents_dim,\n","        'layers': enc_lays\n","    }\n","\n","    ,\n","    \n","        {\n","        'name': 'generative', \n","        'inputs_shape':latents_dim,\n","        'outputs_shape':inputs_shape,\n","        'layers':dec_lays\n","    }\n","]"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Txx3QfGDMEqJ"},"source":["from utils.data_and_files.file_utils import create_if_not_exist"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"G_CQRcqAMEqQ"},"source":["_restore = os.path.join(experiments_dir, 'var_save_dir')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"FAY7Ea_bMEqV","executionInfo":{"status":"ok","timestamp":1604286980060,"user_tz":-60,"elapsed":2045,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"ea47bad5-4fa2-4bab-f013-0a3d884e92e5","colab":{"base_uri":"https://localhost:8080/","height":35}},"source":["create_if_not_exist(_restore)\n","_restore"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir'"]},"metadata":{"tags":[]},"execution_count":28}]},{"cell_type":"code","metadata":{"id":"7zRfld2HMEqb"},"source":["#to restore trained model, set filepath=_restore"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":false,"id":"UY2-rhLCMEql","executionInfo":{"status":"ok","timestamp":1604286980700,"user_tz":-60,"elapsed":2671,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"7123ded7-ec6d-4923-c7e3-1f62727d5b26","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae = AE( \n","    name=model_name,\n","    latents_dim=latents_dim,\n","    batch_size=batch_size,\n","    variables_params=variables_params, \n","    filepath=_restore\n","    )"],"execution_count":null,"outputs":[{"output_type":"stream","text":["  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[31mERROR   \u001b[0m | \u001b[31mFaild to restore old models !\u001b[0m\n","  \u001b[31mERROR   \u001b[0m | \u001b[31mFaild to restore old models !\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["\n","SavedModel file does not exist at: /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir/pokemonAE_Dense_reconst_psnr_inverse_inference.hdf5/{saved_model.pbtxt|saved_model.pb}\n","\n","\n","Model: \"inference\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","dense (Dense)                (None, 100, 100, 50)      200       \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 100, 100, 50)      2550      \n","_________________________________________________________________\n","flatten (Flatten)            (None, 500000)            0         \n","_________________________________________________________________\n","dense_2 (Dense)              (None, 100)               50000100  \n","_________________________________________________________________\n","batch_normalization (BatchNo (None, 100)               400       \n","_________________________________________________________________\n","dropout (Dropout)            (None, 100)               0         \n","_________________________________________________________________\n","activity_regularization (Act (None, 100)               0         \n","_________________________________________________________________\n","inference_outputs (Activatio (None, 100)               0         \n","=================================================================\n","Total params: 50,003,250\n","Trainable params: 50,003,050\n","Non-trainable params: 200\n","_________________________________________________________________\n","\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"generative\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","generative_inputs (InputLaye [(None, 100)]             0         \n","_________________________________________________________________\n","dense_3 (Dense)              (None, 100)               10100     \n","_________________________________________________________________\n","dense_4 (Dense)              (None, 1666)              168266    \n","_________________________________________________________________\n","dense_5 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_6 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_7 (Dense)              (None, 30000)             50010000  \n","_________________________________________________________________\n","reshape (Reshape)            (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","batch_normalization_1 (Batch (None, 100, 100, 3)       12        \n","_________________________________________________________________\n","dropout_1 (Dropout)          (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","activity_regularization_1 (A (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","generative_outputs (Activati (None, 100, 100, 3)       0         \n","=================================================================\n","Total params: 55,742,822\n","Trainable params: 55,742,816\n","Non-trainable params: 6\n","_________________________________________________________________\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"_2Z6eauUMEqs"},"source":["from evaluation.quantitive_metrics.peak_signal_to_noise_ratio import prepare_psnr\n","#from statistical.losses_utilities import similarty_to_distance\n","from statistical.ae_losses import expected_loglikelihood_with_lower_bound as ellwlb"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"sFq4vtIZMEqy"},"source":["def similarity_to_distance(similarity_fn):\n","    distance_fn = lambda x, y: 0.5*(1-similarity_fn(x,y))\n","    return distance_fn\n","\n","psnr = similarity_to_distance(prepare_psnr([ae.batch_size]+ae.get_inputs_shape()))"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Jf75aK6LMEq8","executionInfo":{"status":"ok","timestamp":1604286980706,"user_tz":-60,"elapsed":2654,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"72ed6b81-2741-4263-db9a-115a2af1eaa3","colab":{"base_uri":"https://localhost:8080/"}},"source":["#ae.compile(metrics=None)\n","#ae.compile()\n","ae.compile(loss={'x_logits': lambda x_true, x_logits: psnr(x_true, x_logits)})"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Model: \"pokemonAE_Dense_reconst_psnr_inverse\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","inference (Functional)       (None, 100)               50003250  \n","_________________________________________________________________\n","generative (Functional)      (None, 100, 100, 3)       55742822  \n","_________________________________________________________________\n","tf_op_layer_x_logits (Tensor [(None, 100, 100, 3)]     0         \n","=================================================================\n","Total params: 105,746,072\n","Trainable params: 105,745,866\n","Non-trainable params: 206\n","_________________________________________________________________\n","None\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"uEuQT_MpMErB","executionInfo":{"status":"ok","timestamp":1604286980707,"user_tz":-60,"elapsed":2647,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"2209b312-4c3a-44ca-a72b-e2fb4262ac82","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.output_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(None, 100, 100, 3)"]},"metadata":{"tags":[]},"execution_count":34}]},{"cell_type":"markdown","metadata":{"id":"Qrel5s5qMErK"},"source":["# Callbacks"]},{"cell_type":"code","metadata":{"id":"lNORqNfHMErM"},"source":["from training.callbacks.sample_generation import SampleGeneration\n","from training.callbacks.save_model import ModelSaver"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"WpCYFsV-MErR"},"source":["es = tf.keras.callbacks.EarlyStopping(\n","    monitor='val_loss', \n","    min_delta=1e-15, \n","    patience=10, \n","    verbose=1, \n","    restore_best_weights=False\n",")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"6iWp0WrqMEre"},"source":["ms = ModelSaver(filepath=_restore)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"HjJaO2WUMErw","executionInfo":{"status":"ok","timestamp":1604286984593,"user_tz":-60,"elapsed":1354,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"7a706798-1695-4ed7-872d-1a7748d40fb1","colab":{"base_uri":"https://localhost:8080/"}},"source":["csv_dir = os.path.join(experiments_dir, 'csv_dir')\n","create_if_not_exist(csv_dir)\n","csv_dir = os.path.join(csv_dir, ae.name+'.csv')\n","csv_log = tf.keras.callbacks.CSVLogger(csv_dir, append=True)\n","csv_dir"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/csv_dir/pokemonAE_Dense_reconst_psnr_inverse.csv'"]},"metadata":{"tags":[]},"execution_count":38}]},{"cell_type":"code","metadata":{"id":"FQbyvvCRMEr6"},"source":["image_gen_dir = os.path.join(experiments_dir, 'image_gen_dir')\n","create_if_not_exist(image_gen_dir)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"cr1ckyJuMEsA"},"source":["sg = SampleGeneration(latents_shape=latents_dim, filepath=image_gen_dir, gen_freq=5, save_img=True, gray_plot=False)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"nk7pZweuMEsG"},"source":["import numpy as np"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"tso3vAmgMEsL"},"source":["# Model Training"]},{"cell_type":"code","metadata":{"scrolled":false,"id":"BWjhenbBMEsM","executionInfo":{"status":"ok","timestamp":1604297792516,"user_tz":-60,"elapsed":10806512,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"bf63867e-7de0-44d2-ff92-a513c6ee015c","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.fit(\n","    x=train_generator,\n","    input_kw='images',\n","    steps_per_epoch=int(5e3),\n","    epochs=int(1e6), \n","    verbose=2,\n","    callbacks=[es, ms, csv_log, sg],\n","    workers=-1,\n","    use_multiprocessing=True,\n","    validation_data=val_generator,\n","    validation_steps=int(1e4)\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Epoch 1/1000000\n","\n","Epoch 00001: loss improved from inf to -5.03920, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 595s - loss: -5.0392e+00 - psnr: 11.3339 - total_variation: 81215.8516 - ssim_multiscale: 4.5438 - sharpdiff: 5.7175 - mean_absolute_error: 0.2181 - mean_squared_error: 0.0785 - val_loss: -5.2454e+00 - val_psnr: 11.6555 - val_total_variation: 19998.8359 - val_ssim_multiscale: 3.6139 - val_sharpdiff: 9.3242 - val_mean_absolute_error: 0.2278 - val_mean_squared_error: 0.0713\n","Epoch 2/1000000\n","\n","Epoch 00002: loss improved from -5.03920 to -5.80876, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 596s - loss: -5.8088e+00 - psnr: 12.9957 - total_variation: 95166.8828 - ssim_multiscale: 6.4024 - sharpdiff: 5.5625 - mean_absolute_error: 0.1494 - mean_squared_error: 0.0510 - val_loss: -5.1621e+00 - val_psnr: 11.4692 - val_total_variation: 16643.2871 - val_ssim_multiscale: 3.5557 - val_sharpdiff: 9.5783 - val_mean_absolute_error: 0.2355 - val_mean_squared_error: 0.0743\n","Epoch 3/1000000\n","\n","Epoch 00003: loss improved from -5.80876 to -5.86180, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 593s - loss: -5.8618e+00 - psnr: 13.1043 - total_variation: 94545.4609 - ssim_multiscale: 6.5377 - sharpdiff: 5.6393 - mean_absolute_error: 0.1441 - mean_squared_error: 0.0498 - val_loss: -5.0842e+00 - val_psnr: 11.2997 - val_total_variation: 15628.9629 - val_ssim_multiscale: 3.5516 - val_sharpdiff: 9.6513 - val_mean_absolute_error: 0.2410 - val_mean_squared_error: 0.0763\n","Epoch 4/1000000\n","\n","Epoch 00004: loss improved from -5.86180 to -5.88438, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 593s - loss: -5.8844e+00 - psnr: 13.1495 - total_variation: 94240.6875 - ssim_multiscale: 6.5788 - sharpdiff: 5.6712 - mean_absolute_error: 0.1418 - mean_squared_error: 0.0493 - val_loss: -5.1452e+00 - val_psnr: 11.4280 - val_total_variation: 15528.6162 - val_ssim_multiscale: 3.6459 - val_sharpdiff: 9.6909 - val_mean_absolute_error: 0.2365 - val_mean_squared_error: 0.0741\n","Epoch 5/1000000\n","\n","Epoch 00005: loss improved from -5.88438 to -5.90090, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 592s - loss: -5.9009e+00 - psnr: 13.1812 - total_variation: 94106.6016 - ssim_multiscale: 6.6047 - sharpdiff: 5.6898 - mean_absolute_error: 0.1402 - mean_squared_error: 0.0488 - val_loss: -5.3497e+00 - val_psnr: 11.8706 - val_total_variation: 16436.8906 - val_ssim_multiscale: 3.9253 - val_sharpdiff: 9.6537 - val_mean_absolute_error: 0.2185 - val_mean_squared_error: 0.0672\n","Epoch 6/1000000\n","\n","Epoch 00006: loss improved from -5.90090 to -5.91169, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 602s - loss: -5.9117e+00 - psnr: 13.1992 - total_variation: 94008.5078 - ssim_multiscale: 6.6234 - sharpdiff: 5.7037 - mean_absolute_error: 0.1392 - mean_squared_error: 0.0487 - val_loss: -5.4291e+00 - val_psnr: 12.0486 - val_total_variation: 17442.4473 - val_ssim_multiscale: 4.1115 - val_sharpdiff: 9.6108 - val_mean_absolute_error: 0.2101 - val_mean_squared_error: 0.0646\n","Epoch 7/1000000\n","\n","Epoch 00007: loss improved from -5.91169 to -5.92210, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 602s - loss: -5.9221e+00 - psnr: 13.2177 - total_variation: 93962.2812 - ssim_multiscale: 6.6355 - sharpdiff: 5.7132 - mean_absolute_error: 0.1382 - mean_squared_error: 0.0484 - val_loss: -5.4213e+00 - val_psnr: 12.0386 - val_total_variation: 17865.6953 - val_ssim_multiscale: 4.1337 - val_sharpdiff: 9.5739 - val_mean_absolute_error: 0.2086 - val_mean_squared_error: 0.0647\n","Epoch 8/1000000\n","\n","Epoch 00008: loss improved from -5.92210 to -5.92946, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 602s - loss: -5.9295e+00 - psnr: 13.2312 - total_variation: 93865.1250 - ssim_multiscale: 6.6441 - sharpdiff: 5.7227 - mean_absolute_error: 0.1374 - mean_squared_error: 0.0483 - val_loss: -5.4690e+00 - val_psnr: 12.1699 - val_total_variation: 17479.0391 - val_ssim_multiscale: 4.1914 - val_sharpdiff: 9.6174 - val_mean_absolute_error: 0.2007 - val_mean_squared_error: 0.0632\n","Epoch 9/1000000\n","\n","Epoch 00009: loss improved from -5.92946 to -5.93055, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 603s - loss: -5.9305e+00 - psnr: 13.2329 - total_variation: 93820.4219 - ssim_multiscale: 6.6487 - sharpdiff: 5.7282 - mean_absolute_error: 0.1373 - mean_squared_error: 0.0483 - val_loss: -5.4347e+00 - val_psnr: 12.0958 - val_total_variation: 18106.3672 - val_ssim_multiscale: 4.2059 - val_sharpdiff: 9.5671 - val_mean_absolute_error: 0.2024 - val_mean_squared_error: 0.0641\n","Epoch 10/1000000\n","\n","Epoch 00010: loss improved from -5.93055 to -5.93491, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 603s - loss: -5.9349e+00 - psnr: 13.2423 - total_variation: 93779.9062 - ssim_multiscale: 6.6536 - sharpdiff: 5.7327 - mean_absolute_error: 0.1367 - mean_squared_error: 0.0482 - val_loss: -5.3489e+00 - val_psnr: 11.9045 - val_total_variation: 17806.3848 - val_ssim_multiscale: 4.1108 - val_sharpdiff: 9.5774 - val_mean_absolute_error: 0.2109 - val_mean_squared_error: 0.0671\n","Epoch 11/1000000\n","\n","Epoch 00011: loss improved from -5.93491 to -5.93670, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 603s - loss: -5.9367e+00 - psnr: 13.2458 - total_variation: 93718.8359 - ssim_multiscale: 6.6574 - sharpdiff: 5.7378 - mean_absolute_error: 0.1364 - mean_squared_error: 0.0481 - val_loss: -5.3960e+00 - val_psnr: 12.0304 - val_total_variation: 16822.2168 - val_ssim_multiscale: 4.0925 - val_sharpdiff: 9.6546 - val_mean_absolute_error: 0.2054 - val_mean_squared_error: 0.0659\n","Epoch 12/1000000\n","\n","Epoch 00012: loss improved from -5.93670 to -5.93806, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 603s - loss: -5.9381e+00 - psnr: 13.2497 - total_variation: 93721.9453 - ssim_multiscale: 6.6563 - sharpdiff: 5.7394 - mean_absolute_error: 0.1362 - mean_squared_error: 0.0481 - val_loss: -5.2818e+00 - val_psnr: 11.7858 - val_total_variation: 18208.0098 - val_ssim_multiscale: 4.0967 - val_sharpdiff: 9.5342 - val_mean_absolute_error: 0.2111 - val_mean_squared_error: 0.0689\n","Epoch 13/1000000\n","\n","Epoch 00013: loss did not improve from -5.93806\n","5000/5000 - 601s - loss: -5.9378e+00 - psnr: 13.2496 - total_variation: 93679.8984 - ssim_multiscale: 6.6586 - sharpdiff: 5.7409 - mean_absolute_error: 0.1361 - mean_squared_error: 0.0481 - val_loss: -5.3809e+00 - val_psnr: 12.0016 - val_total_variation: 17277.6309 - val_ssim_multiscale: 4.1441 - val_sharpdiff: 9.6107 - val_mean_absolute_error: 0.2047 - val_mean_squared_error: 0.0660\n","Epoch 14/1000000\n","\n","Epoch 00014: loss improved from -5.93806 to -5.93981, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 603s - loss: -5.9398e+00 - psnr: 13.2534 - total_variation: 93655.7109 - ssim_multiscale: 6.6627 - sharpdiff: 5.7438 - mean_absolute_error: 0.1358 - mean_squared_error: 0.0480 - val_loss: -5.1950e+00 - val_psnr: 11.5928 - val_total_variation: 18360.4570 - val_ssim_multiscale: 3.9961 - val_sharpdiff: 9.4905 - val_mean_absolute_error: 0.2187 - val_mean_squared_error: 0.0723\n","Epoch 15/1000000\n","\n","Epoch 00015: loss did not improve from -5.93981\n","5000/5000 - 600s - loss: -5.9396e+00 - psnr: 13.2535 - total_variation: 93635.1016 - ssim_multiscale: 6.6592 - sharpdiff: 5.7451 - mean_absolute_error: 0.1357 - mean_squared_error: 0.0481 - val_loss: -5.3452e+00 - val_psnr: 11.9256 - val_total_variation: 17796.4902 - val_ssim_multiscale: 4.1227 - val_sharpdiff: 9.5570 - val_mean_absolute_error: 0.2073 - val_mean_squared_error: 0.0672\n","Epoch 16/1000000\n","\n","Epoch 00016: loss did not improve from -5.93981\n","5000/5000 - 600s - loss: -5.9385e+00 - psnr: 13.2516 - total_variation: 93631.8359 - ssim_multiscale: 6.6592 - sharpdiff: 5.7442 - mean_absolute_error: 0.1358 - mean_squared_error: 0.0481 - val_loss: -5.3214e+00 - val_psnr: 12.0218 - val_total_variation: 18256.2695 - val_ssim_multiscale: 4.2060 - val_sharpdiff: 9.5440 - val_mean_absolute_error: 0.1960 - val_mean_squared_error: 0.0662\n","Epoch 17/1000000\n","\n","Epoch 00017: loss improved from -5.93981 to -5.94285, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr_inverse/var_save_dir\n","5000/5000 - 601s - loss: -5.9428e+00 - psnr: 13.2607 - total_variation: 93609.7734 - ssim_multiscale: 6.6634 - sharpdiff: 5.7478 - mean_absolute_error: 0.1353 - mean_squared_error: 0.0479 - val_loss: -4.2706e+00 - val_psnr: 10.2920 - val_total_variation: 25388.8066 - val_ssim_multiscale: 3.8563 - val_sharpdiff: 8.9665 - val_mean_absolute_error: 0.2140 - val_mean_squared_error: 0.0960\n","Epoch 18/1000000\n","\n","Epoch 00018: loss did not improve from -5.94285\n","5000/5000 - 597s - loss: -5.9392e+00 - psnr: 13.2536 - total_variation: 93590.2031 - ssim_multiscale: 6.6597 - sharpdiff: 5.7470 - mean_absolute_error: 0.1356 - mean_squared_error: 0.0481 - val_loss: -5.1761e+00 - val_psnr: 11.6233 - val_total_variation: 19170.2969 - val_ssim_multiscale: 3.9490 - val_sharpdiff: 9.4545 - val_mean_absolute_error: 0.2126 - val_mean_squared_error: 0.0717\n","Epoch 00018: early stopping\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["<tensorflow.python.keras.callbacks.History at 0x7f4d4a4bbc18>"]},"metadata":{"tags":[]},"execution_count":42}]},{"cell_type":"markdown","metadata":{"id":"UhSTW1KSQeC_"},"source":["# Model Evaluation"]},{"cell_type":"markdown","metadata":{"id":"hCPgsBp9QeDA"},"source":["## inception_score"]},{"cell_type":"code","metadata":{"id":"w0wPQHi0QeDB"},"source":["from evaluation.generativity_metrics.inception_metrics import inception_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"7c7I66B9QeDF","executionInfo":{"status":"ok","timestamp":1604314388934,"user_tz":-60,"elapsed":27379651,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"286ad301-1d71-4bec-8ff9-f62d9343c1e5","colab":{"base_uri":"https://localhost:8080/"}},"source":["is_mean, is_sigma = inception_score(ae, tolerance_threshold=1e-6, max_iteration=300)\n","print(f'inception_score mean: {is_mean.compute()}, sigma: {is_sigma.compute()}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5\n","87916544/87910968 [==============================] - 1s 0us/step\n","calculating the inception_score mean ...\n","WARNING:tensorflow:Model was constructed with shape (None, 75, 75, 3) for input Tensor(\"input_1:0\", shape=(None, 75, 75, 3), dtype=float32), but it was called on an input with incompatible shape (None, 100, 100, 3).\n"],"name":"stdout"},{"output_type":"stream","text":["300it [2:17:10, 27.36s/it]"],"name":"stderr"},{"output_type":"stream","text":["calculating the inception_score sigma ...\n"],"name":"stdout"},{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/dask/array/routines.py:780: RuntimeWarning: Degrees of freedom <= 0 for slice\n","  warnings.warn(\"Degrees of freedom <= 0 for slice\", RuntimeWarning)\n","0it [00:00, ?it/s]/usr/local/lib/python3.6/dist-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide\n","  return func(*(_execute_task(a, cache) for a in args))\n","1it [00:27, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","2it [00:54, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","3it [01:22, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","4it [01:49, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","5it [02:17, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","6it [02:45, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","7it [03:12, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","8it [03:39, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","9it [04:07, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","10it [04:35, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","11it [05:02, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","12it [05:29, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","13it [05:57, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","14it [06:24, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","15it [06:52, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","16it [07:19, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","17it [07:46, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","18it [08:14, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","19it [08:41, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","20it [09:09, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","21it [09:36, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","22it [10:04, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","23it [10:31, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","24it [10:59, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","25it [11:26, 27.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","26it [11:53, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","27it [12:21, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","28it [12:48, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","29it [13:16, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","30it [13:43, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","31it [14:11, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","32it [14:38, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","33it [15:06, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","34it [15:33, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","35it [16:00, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","36it [16:27, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","37it [16:55, 27.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","38it [17:22, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","39it [17:50, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","40it [18:17, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","41it [18:44, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","42it [19:12, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","43it [19:39, 27.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","44it [20:06, 27.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","45it [20:33, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","46it [21:01, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","47it [21:29, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","48it [21:56, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","49it [22:23, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","50it [22:51, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","51it [23:19, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","52it [23:46, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","53it [24:14, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","54it [24:41, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","55it [25:09, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","56it [25:36, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","57it [26:03, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","58it [26:31, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","59it [26:58, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","60it [27:26, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","61it [27:53, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","62it [28:21, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","63it [28:48, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","64it [29:15, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","65it [29:43, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","66it [30:10, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","67it [30:38, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","68it [31:05, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","69it [31:33, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","70it [32:00, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","71it [32:27, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","72it [32:55, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","73it [33:23, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","74it [33:50, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","75it [34:17, 27.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","76it [34:45, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","77it [35:12, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","78it [35:39, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","79it [36:07, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","80it [36:35, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","81it [37:02, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","82it [37:30, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","83it [37:58, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","84it [38:25, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","85it [38:53, 27.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","86it [39:20, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","87it [39:48, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","88it [40:15, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","89it [40:43, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","90it [41:10, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","91it [41:38, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","92it [42:05, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","93it [42:33, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","94it [43:00, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","95it [43:28, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","96it [43:56, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","97it [44:24, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","98it [44:51, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","99it [45:18, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","100it [45:46, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","101it [46:13, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","102it [46:41, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","103it [47:08, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","104it [47:36, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","105it [48:03, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","106it [48:31, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","107it [48:58, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","108it [49:26, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","109it [49:53, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","110it [50:20, 27.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","111it [50:48, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","112it [51:15, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","113it [51:43, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","114it [52:10, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","115it [52:38, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","116it [53:05, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","117it [53:33, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","118it [54:01, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","119it [54:29, 27.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","120it [54:56, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","121it [55:24, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","122it [55:51, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","123it [56:19, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","124it [56:47, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","125it [57:14, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","126it [57:42, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","127it [58:09, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","128it [58:37, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","129it [59:04, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","130it [59:33, 27.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","131it [1:00:01, 27.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","132it [1:00:28, 27.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","133it [1:00:56, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","134it [1:01:24, 27.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","135it [1:01:51, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","136it [1:02:19, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","137it [1:02:47, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","138it [1:03:14, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","139it [1:03:42, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","140it [1:04:09, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","141it [1:04:37, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","142it [1:05:04, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","143it [1:05:32, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","144it [1:05:59, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","145it [1:06:27, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","146it [1:06:54, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","147it [1:07:21, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","148it [1:07:49, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","149it [1:08:17, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","150it [1:08:44, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","151it [1:09:12, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","152it [1:09:40, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","153it [1:10:07, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","154it [1:10:35, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","155it [1:11:02, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","156it [1:11:29, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","157it [1:11:57, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","158it [1:12:24, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","159it [1:12:51, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","160it [1:13:19, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","161it [1:13:46, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","162it [1:14:14, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","163it [1:14:42, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","164it [1:15:10, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","165it [1:15:37, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","166it [1:16:05, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","167it [1:16:32, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","168it [1:17:00, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","169it [1:17:28, 27.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","170it [1:17:55, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","171it [1:18:23, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","172it [1:18:51, 27.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","173it [1:19:19, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","174it [1:19:46, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","175it [1:20:14, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","176it [1:20:41, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","177it [1:21:09, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","178it [1:21:36, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","179it [1:22:03, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","180it [1:22:31, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","181it [1:22:59, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","182it [1:23:26, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","183it [1:23:53, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","184it [1:24:21, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","185it [1:24:49, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","186it [1:25:16, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","187it [1:25:44, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","188it [1:26:11, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","189it [1:26:39, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","190it [1:27:06, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","191it [1:27:34, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","192it [1:28:01, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","193it [1:28:29, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","194it [1:28:56, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","195it [1:29:24, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","196it [1:29:51, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","197it [1:30:19, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","198it [1:30:46, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","199it [1:31:14, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","200it [1:31:41, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","201it [1:32:09, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","202it [1:32:37, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","203it [1:33:04, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","204it [1:33:32, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","205it [1:33:59, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","206it [1:34:26, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","207it [1:34:54, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","208it [1:35:21, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","209it [1:35:49, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","210it [1:36:17, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","211it [1:36:44, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","212it [1:37:12, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","213it [1:37:39, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","214it [1:38:07, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","215it [1:38:34, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","216it [1:39:02, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","217it [1:39:29, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","218it [1:39:57, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","219it [1:40:24, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","220it [1:40:52, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","221it [1:41:19, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","222it [1:41:47, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","223it [1:42:14, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","224it [1:42:42, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","225it [1:43:09, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","226it [1:43:37, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","227it [1:44:04, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","228it [1:44:32, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","229it [1:44:59, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","230it [1:45:27, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","231it [1:45:54, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","232it [1:46:22, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","233it [1:46:50, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","234it [1:47:17, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","235it [1:47:45, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","236it [1:48:12, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","237it [1:48:39, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","238it [1:49:07, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","239it [1:49:34, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","240it [1:50:01, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","241it [1:50:29, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","242it [1:50:56, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","243it [1:51:24, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","244it [1:51:52, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","245it [1:52:19, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","246it [1:52:47, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","247it [1:53:14, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","248it [1:53:42, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","249it [1:54:09, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","250it [1:54:37, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","251it [1:55:04, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","252it [1:55:32, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","253it [1:55:59, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","254it [1:56:27, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","255it [1:56:55, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","256it [1:57:22, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","257it [1:57:50, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","258it [1:58:17, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","259it [1:58:45, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","260it [1:59:12, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","261it [1:59:40, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","262it [2:00:07, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","263it [2:00:34, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","264it [2:01:02, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","265it [2:01:30, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","266it [2:01:57, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","267it [2:02:25, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","268it [2:02:52, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","269it [2:03:19, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","270it [2:03:47, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","271it [2:04:14, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","272it [2:04:42, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","273it [2:05:09, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","274it [2:05:37, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","275it [2:06:04, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","276it [2:06:32, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","277it [2:06:59, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","278it [2:07:27, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","279it [2:07:54, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","280it [2:08:22, 27.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","281it [2:08:50, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","282it [2:09:17, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","283it [2:09:45, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","284it [2:10:13, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","285it [2:10:40, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","286it [2:11:07, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","287it [2:11:35, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","288it [2:12:03, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","289it [2:12:31, 27.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","290it [2:12:58, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","291it [2:13:25, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","292it [2:13:53, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","293it [2:14:20, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","294it [2:14:48, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","295it [2:15:16, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","296it [2:15:43, 27.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","297it [2:16:11, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","298it [2:16:38, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","299it [2:17:06, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","300it [2:17:34, 27.63s/it]"],"name":"stderr"},{"output_type":"stream","text":["inception_score mean: [2.09925671e+220], sigma: inf\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"Qk6qBylRQeDJ"},"source":["\n","## Frechet_inception_distance\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"t54Qm7_FQeDK"},"source":["from evaluation.generativity_metrics.inception_metrics import frechet_inception_distance"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"p-_KQpVPQeDP"},"source":["fis_score = frechet_inception_distance(ae, train_generator.as_numpy_iterator(), \n","                                       tolerance_threshold=1e-6, \n","                                       max_iteration=300, \n","                                       batch_size=32)\n"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"GtJ1QNcx_rt2"},"source":["print(f'frechet inception distance: {fis_score.compute()}')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"dS4QPAXoQeDX"},"source":["## perceptual_path_length_score"]},{"cell_type":"code","metadata":{"id":"FHxOntNaQeDZ"},"source":["from evaluation.generativity_metrics.perceptual_path_length import perceptual_path_length_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"FtgoCP49QeDj","executionInfo":{"status":"ok","timestamp":1604314664603,"user_tz":-60,"elapsed":27652602,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"d11ad9a0-2097-4b50-ef91-5f69904391a1","colab":{"base_uri":"https://localhost:8080/"}},"source":["ppl_mean_score = perceptual_path_length_score(ae, train_generator.as_numpy_iterator(), \n","                                              tolerance_threshold=1e-6, \n","                                              max_iteration=300, \n","                                              batch_size=32)\n","print(f'perceptual path length score: {ppl_mean_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5\n","58892288/58889256 [==============================] - 0s 0us/step\n"],"name":"stdout"},{"output_type":"stream","text":["300it [04:33,  1.12it/s]"],"name":"stderr"},{"output_type":"stream","text":["perceptual path length score: 4934.37255859375\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"l6zFWvmtQeDr"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Y8mKKa7hQeDv"},"source":["## precision score"]},{"cell_type":"code","metadata":{"id":"2VF-JOv3QeDx"},"source":["from evaluation.generativity_metrics.precision_recall import precision_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"vT1C64RdQeD5","executionInfo":{"status":"ok","timestamp":1604314664950,"user_tz":-60,"elapsed":27651050,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"fd5af1c3-f1a1-4307-91e8-1b35001236af","colab":{"base_uri":"https://localhost:8080/"}},"source":["_precision_score = precision_score(ae,  train_generator.as_numpy_iterator(), \n","                                   tolerance_threshold=1e-6, \n","                                   max_iteration=300)\n","print(f'precision score: {_precision_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","0it [00:00, ?it/s]/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00241899s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00198269s\n","precision score: [0.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"M4JbbHnQQeD-"},"source":["## recall score"]},{"cell_type":"code","metadata":{"id":"RhwDYty1QeEA"},"source":["from evaluation.generativity_metrics.precision_recall import recall_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LMzfn5KHQeEF","executionInfo":{"status":"ok","timestamp":1604314665455,"user_tz":-60,"elapsed":27650276,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"f61fae32-f3b4-4f65-88f8-74bd0e5175bd","colab":{"base_uri":"https://localhost:8080/"}},"source":["_recall_score = recall_score(ae, train_generator.as_numpy_iterator(), tolerance_threshold=1e-6, max_iteration=300)\n","print(f'recall score: {_recall_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","0it [00:00, ?it/s]/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00178409s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00234294s\n","recall score: [1.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"nQH-mfDmQeEJ"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"9vPAhxCyQeEQ"},"source":["# Image Generation"]},{"cell_type":"markdown","metadata":{"id":"s5OsqNYaQeES"},"source":["## image reconstruction"]},{"cell_type":"markdown","metadata":{"id":"oEEynQF2QeET"},"source":["### Training dataset"]},{"cell_type":"code","metadata":{"id":"Fg1wGMkRQeEU"},"source":["from training.generators.from_images.image_generation_testing import reconstruct_from_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZSJ55VozQeEZ","executionInfo":{"status":"ok","timestamp":1604314666224,"user_tz":-60,"elapsed":27649221,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"2a478742-fd1c-4cbf-cf6d-5708752a774d","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 67.73it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"G1_8VcdJQeEl","executionInfo":{"status":"ok","timestamp":1604314666226,"user_tz":-60,"elapsed":27649215,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"2f985ebd-5fe7-4e28-c346-eb44ec11495f","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 40.26it/s]\n"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"iwDP-H8cQeEq"},"source":["## with Randomness"]},{"cell_type":"code","metadata":{"id":"4YXvt2J8QeEr"},"source":["from training.generators.from_images.image_generation_testing import generate_images_like_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Lxr8AimWQeEy","executionInfo":{"status":"ok","timestamp":1604314667061,"user_tz":-60,"elapsed":27650039,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"39365fe1-5ede-45a6-8a64-303021a8e5ff","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 38.17it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"VfEeBtsxQeE7","executionInfo":{"status":"ok","timestamp":1604314667473,"user_tz":-60,"elapsed":27650444,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"5552a141-e1bd-43c4-8355-608aa49c10e8","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 42.97it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"pHRCUI6eQeFD"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"TdeyPBhtQeFG"},"source":["### Complete Randomness"]},{"cell_type":"code","metadata":{"id":"Tr8JPmloQeFH"},"source":["from training.generators.from_images.image_generation_testing import generate_images_randomly"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"9OZuHVx2QeFK","executionInfo":{"status":"ok","timestamp":1604314667480,"user_tz":-60,"elapsed":27650430,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"51cb99f7-5bc0-465b-864a-5afcd7990a57","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'random_synthetic_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_randomly(ae, save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["32it [00:00, 80.57it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"Jh8HeIbMQeFR"},"source":["from training.generators.from_images.image_generation_testing import interpolate_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"oKULH_U9QeFW","executionInfo":{"status":"ok","timestamp":1604314667789,"user_tz":-60,"elapsed":27650729,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"5f90a907-aa3b-478b-ff83-8cbb179ece6a","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'interpolate_dir')\n","create_if_not_exist(save_dir)\n","\n","interpolate_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 136.26it/s]\n","10it [00:00, 143.03it/s]\n","0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["\n","\n","\n"],"name":"stdout"},{"output_type":"stream","text":["10it [00:00, 141.62it/s]\n","10it [00:00, 113.63it/s]\n","100%|██████████| 4/4 [00:00<00:00, 11.34it/s]\n","10it [00:00, 143.45it/s]\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Fuhv1qXyQeFb"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"i0mPqk0UQeFg"},"source":[""],"execution_count":null,"outputs":[]}]}