{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"colab":{"name":"pokemonAE_Dense_reconst_1ellwlb_01sharpdiff.ipynb","provenance":[],"collapsed_sections":["hEAsVNW1LtRs","qT6qzSWJLtSG","HyEDJAeDLtTi","fbIa6Q7XLtUc","UhSTW1KSQeC_","hCPgsBp9QeDA","Qk6qBylRQeDJ","dS4QPAXoQeDX","Y8mKKa7hQeDv","M4JbbHnQQeD-","9vPAhxCyQeEQ","s5OsqNYaQeES","oEEynQF2QeET","iwDP-H8cQeEq","TdeyPBhtQeFG"],"toc_visible":true},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","metadata":{"id":"z_dRC21JmH8M"},"source":["Trained and tested except Frechet"]},{"cell_type":"code","metadata":{"id":"sLIC532RLtPc"},"source":["%load_ext autoreload\n","%autoreload 2"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"FaAUkhTxnzQT"},"source":["# Environment prep for Colab\n"," - download git repo \n"," - install required pip packages"]},{"cell_type":"code","metadata":{"id":"jRy-3Mj7Rn2h","executionInfo":{"status":"ok","timestamp":1604285950990,"user_tz":-60,"elapsed":25540,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"5088b1fd-c95e-4637-9ac1-7a298b1453cd","colab":{"base_uri":"https://localhost:8080/"}},"source":["!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Cloning into 'Generative_Models'...\n","remote: Enumerating objects: 15891, done.\u001b[K\n","remote: Total 15891 (delta 0), reused 0 (delta 0), pack-reused 15891\u001b[K\n","Receiving objects: 100% (15891/15891), 733.46 MiB | 44.36 MiB/s, done.\n","Resolving deltas: 100% (10845/10845), done.\n","Checking out files: 100% (1697/1697), done.\n","/content/Generative_Models\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0zbi2r-8nENp","scrolled":true,"executionInfo":{"status":"ok","timestamp":1604285983228,"user_tz":-60,"elapsed":57738,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"d1c0483a-4282-46de-c4b3-7fecfebf82f6","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","!pip install colorlog==4.0.2\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Mounted at /content/drive\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n","/content/Generative_Models\n","Collecting colorlog==4.0.2\n","  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl\n","Installing collected packages: colorlog\n","Successfully installed colorlog-4.0.2\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"N09gj2pVgT7R","executionInfo":{"status":"ok","timestamp":1604285983241,"user_tz":-60,"elapsed":57716,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"75214abd-0d4b-4c13-a620-dd1c321bac73","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"pDUjPvxE-DA2"},"source":["# Connect Drive to save and restore results"]},{"cell_type":"code","metadata":{"id":"YqhHHzGuEAi1","executionInfo":{"status":"ok","timestamp":1604285983244,"user_tz":-60,"elapsed":56347,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"70780e6d-e5cf-4895-9a7c-5ffabad85778","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"L7ypqATvLtPp"},"source":["# Settings"]},{"cell_type":"code","metadata":{"id":"JpIesIxyLtPr","executionInfo":{"status":"ok","timestamp":1604285983247,"user_tz":-60,"elapsed":54991,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"59ff2dba-869c-4685-ec5b-afb5629ee72a","colab":{"base_uri":"https://localhost:8080/"}},"source":["%env TF_KERAS = 1\n","import os\n","sep_local = os.path.sep\n","\n","import sys\n","sys.path.append('..'+sep_local+'..')\n","print(sep_local)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["env: TF_KERAS=1\n","/\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"FWETSF-XLtPz","executionInfo":{"status":"ok","timestamp":1604285983473,"user_tz":-60,"elapsed":55177,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"a231c5b7-0cce-4680-f9cf-5a9f61684f4d","colab":{"base_uri":"https://localhost:8080/"}},"source":["import tensorflow as tf\n","print(tf.__version__)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2.3.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"_sSTeuI1LtQF","executionInfo":{"status":"ok","timestamp":1604285983476,"user_tz":-60,"elapsed":55148,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"95a94f19-0142-4d75-b98c-9561d9d8eee0","colab":{"base_uri":"https://localhost:8080/"}},"source":["#os.chdir('..'+sep_local+'..'+sep_local+'..'+sep_local+'..'+sep_local+'..')\n","os.chdir('/content/Generative_Models')\n","print(os.getcwd())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"qlljVPRsLtQP"},"source":["# only on colab"]},{"cell_type":"code","metadata":{"id":"LlPNDQe3LtQS"},"source":["!cat data/.pokemon/pokemon.tar.part* > data/.pokemon/pokemon.tar"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"biW17P7rLtQe","executionInfo":{"status":"ok","timestamp":1604285985330,"user_tz":-60,"elapsed":54751,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"d6fc9b9d-bd41-40ca-a72e-68a66c7824f9","colab":{"base_uri":"https://localhost:8080/"}},"source":["!tar -xvf data/.pokemon/pokemon.tar --directory data/.pokemon/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Pokemon_LMDB/_training/\n","Pokemon_LMDB/_training/lock.mdb\n","Pokemon_LMDB/_training/data.mdb\n","Pokemon_LMDB/_validation/\n","Pokemon_LMDB/_validation/lock.mdb\n","Pokemon_LMDB/_validation/data.mdb\n","Pokemon_LMDB/meta_info.json\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"FD6gMiKrLtQn"},"source":["# Dataset loading"]},{"cell_type":"code","metadata":{"id":"nlHjb0rBLtQp"},"source":["from training.generators.from_lmdb.lmdb_image_generator import get_generators"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZUkGVAc5LtQ0"},"source":["dataset_name='pokemon'\n","inputs_shape= image_shape=(100, 100, 3)\n","batch_size = 10\n","latents_dim = 100\n","intermediate_dim = 50\n","lmdb_dir = 'data/.pokemon/Pokemon_LMDB'"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"gfc3hFDKLtQ-"},"source":["from transformation.lmdb_transformer import LmdbTransformer"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"iROOyW0ELtRE","executionInfo":{"status":"ok","timestamp":1604286043389,"user_tz":-60,"elapsed":7493,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"41c2e695-6fcb-478f-b081-8b037611e763","colab":{"base_uri":"https://localhost:8080/"}},"source":["train_generator, val_generator = get_generators(\n","        lmdb_dir=lmdb_dir,\n","        batch_size=batch_size,\n","        episode_len=None,\n","        episode_shift=None\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/transformation/file_image_generator.py:51: UserWarning: No files found\n","  warnings.warn(msg)\n"],"name":"stderr"},{"output_type":"stream","text":["Initializing Iterator training Number of images 591\n","Initializing Iterator validation Number of images 218\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"F-QTtxeDLtRX","executionInfo":{"status":"ok","timestamp":1604286043393,"user_tz":-60,"elapsed":2717,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"8fb086ff-3eb6-4227-f75e-2a41bca36591","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","_instance_scale=1.0\n","for data in val_generator:\n","    print(np.max(data['images']))\n","    break\n","    #print(data.keys())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"syt6hXGMLtRf","executionInfo":{"status":"ok","timestamp":1604286043397,"user_tz":-60,"elapsed":607,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"9ac10f6e-915d-4f16-991b-10afa550dd6e","colab":{"base_uri":"https://localhost:8080/"}},"source":["data['images'][0].shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["TensorShape([100, 100, 3])"]},"metadata":{"tags":[]},"execution_count":18}]},{"cell_type":"code","metadata":{"id":"mrAbxSupLtRk","executionInfo":{"status":"ok","timestamp":1604286045993,"user_tz":-60,"elapsed":948,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"212d8935-eead-4125-ee73-4f6edd8cbc23","colab":{"base_uri":"https://localhost:8080/"}},"source":["data.keys()"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["dict_keys(['images', 'label'])"]},"metadata":{"tags":[]},"execution_count":19}]},{"cell_type":"markdown","metadata":{"id":"hEAsVNW1LtRs"},"source":["# Model's Layers definition"]},{"cell_type":"code","metadata":{"id":"wx4HU8gbLtRx","executionInfo":{"status":"ok","timestamp":1604286048920,"user_tz":-60,"elapsed":786,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"09edc7b7-38a2-49b8-ccfa-3a509ca0491e","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","from collections.abc import Iterable\n","if isinstance(inputs_shape, Iterable):\n","    flat_outputs_shape = np.prod(inputs_shape)\n","flat_outputs_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["30000"]},"metadata":{"tags":[]},"execution_count":20}]},{"cell_type":"code","metadata":{"id":"kHwAco3YLtR4","executionInfo":{"status":"ok","timestamp":1604286049261,"user_tz":-60,"elapsed":1089,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"388f7f23-3f1b-477b-e224-831788ad31ab","colab":{"base_uri":"https://localhost:8080/"}},"source":["latents_dim"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["100"]},"metadata":{"tags":[]},"execution_count":21}]},{"cell_type":"code","metadata":{"id":"skWUY9ktLtSA"},"source":["enc_lays = [tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Flatten(),\n","            tf.keras.layers.Dense(units=latents_dim)]\n","\n","dec_lays = [tf.keras.layers.Dense(units=latents_dim, activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","\n","            tf.keras.layers.Dense(units=flat_outputs_shape),\n","            tf.keras.layers.Reshape(inputs_shape)]"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"qT6qzSWJLtSG"},"source":["# Model definition"]},{"cell_type":"code","metadata":{"id":"NtHnQ4zYLtSI","executionInfo":{"status":"ok","timestamp":1604286050930,"user_tz":-60,"elapsed":875,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"885a037c-29a3-4459-c938-2547a014a657","colab":{"base_uri":"https://localhost:8080/"}},"source":["model_name = dataset_name+'AE_Dense_reconst_1ell_01sharpdiff'\n","experiments_dir='/content/drive/My Drive/Results'+sep_local+model_name\n","print(experiments_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"5sjSM3H6LtSS"},"source":["from training.autoencoding_basic.autoencoders.autoencoder import autoencoder as AE"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"H4jOuhJpLtSa"},"source":["variables_params = \\\n","[\n","    {\n","        'name': 'inference', \n","        'inputs_shape':inputs_shape,\n","        'outputs_shape':latents_dim,\n","        'layers': enc_lays\n","    }\n","\n","    ,\n","    \n","        {\n","        'name': 'generative', \n","        'inputs_shape':latents_dim,\n","        'outputs_shape':inputs_shape,\n","        'layers':dec_lays\n","    }\n","]"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"_LJegfRoLtSj"},"source":["from utils.data_and_files.file_utils import create_if_not_exist"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"-RjYlrG7LtSq"},"source":["_restore = os.path.join(experiments_dir, 'var_save_dir')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"7WWlwUpXLtSz","executionInfo":{"status":"ok","timestamp":1604286052182,"user_tz":-60,"elapsed":2015,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"a28b79a4-6b19-488f-8ddc-6caecaabebff","colab":{"base_uri":"https://localhost:8080/","height":35}},"source":["create_if_not_exist(_restore)\n","_restore"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir'"]},"metadata":{"tags":[]},"execution_count":28}]},{"cell_type":"code","metadata":{"id":"hQxn1qwGLtS5"},"source":["#to restore trained model, set filepath=_restore"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":false,"id":"_jaKK0OkLtTB","executionInfo":{"status":"ok","timestamp":1604286058107,"user_tz":-60,"elapsed":7890,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"aafa63ff-6a53-4dfa-f251-880313b47a8f","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae = AE( \n","    name=model_name,\n","    latents_dim=latents_dim,\n","    batch_size=batch_size,\n","    variables_params=variables_params, \n","    filepath=_restore\n","    )"],"execution_count":null,"outputs":[{"output_type":"stream","text":["  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"inference\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","dense (Dense)                (None, 100, 100, 50)      200       \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 100, 100, 50)      2550      \n","_________________________________________________________________\n","flatten (Flatten)            (None, 500000)            0         \n","_________________________________________________________________\n","dense_2 (Dense)              (None, 100)               50000100  \n","_________________________________________________________________\n","batch_normalization (BatchNo (None, 100)               400       \n","_________________________________________________________________\n","dropout (Dropout)            (None, 100)               0         \n","_________________________________________________________________\n","activity_regularization (Act (None, 100)               0         \n","_________________________________________________________________\n","inference_outputs (Activatio (None, 100)               0         \n","=================================================================\n","Total params: 50,003,250\n","Trainable params: 50,003,050\n","Non-trainable params: 200\n","_________________________________________________________________\n","\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"generative\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","generative_inputs (InputLaye [(None, 100)]             0         \n","_________________________________________________________________\n","dense_3 (Dense)              (None, 100)               10100     \n","_________________________________________________________________\n","dense_4 (Dense)              (None, 1666)              168266    \n","_________________________________________________________________\n","dense_5 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_6 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_7 (Dense)              (None, 30000)             50010000  \n","_________________________________________________________________\n","reshape (Reshape)            (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","batch_normalization_1 (Batch (None, 100, 100, 3)       12        \n","_________________________________________________________________\n","dropout_1 (Dropout)          (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","activity_regularization_1 (A (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","generative_outputs (Activati (None, 100, 100, 3)       0         \n","=================================================================\n","Total params: 55,742,822\n","Trainable params: 55,742,816\n","Non-trainable params: 6\n","_________________________________________________________________\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Ao5tTwURLtTH"},"source":["from evaluation.quantitive_metrics.sharp_difference import prepare_sharpdiff\n","\n","#from statistical.losses_utilities import similarty_to_distance\n","from statistical.ae_losses import expected_loglikelihood_with_lower_bound as ellwlb"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"X6f_gmfALtTP","executionInfo":{"status":"ok","timestamp":1604286058116,"user_tz":-60,"elapsed":7862,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"eb055d16-f847-446e-c1cc-30fca54173cd","colab":{"base_uri":"https://localhost:8080/"}},"source":["#ae.compile(metrics=None)\n","#ae.compile()\n","ae.compile(loss={'x_logits': lambda x_true, x_logits: ellwlb(x_true, x_logits)+ 0.1*prepare_sharpdiff([ae.batch_size]+ae.get_inputs_shape())(x_true, x_logits)})"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Model: \"pokemonAE_Dense_reconst_1ell_01sharpdiff\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","inference (Functional)       (None, 100)               50003250  \n","_________________________________________________________________\n","generative (Functional)      (None, 100, 100, 3)       55742822  \n","_________________________________________________________________\n","tf_op_layer_x_logits (Tensor [(None, 100, 100, 3)]     0         \n","=================================================================\n","Total params: 105,746,072\n","Trainable params: 105,745,866\n","Non-trainable params: 206\n","_________________________________________________________________\n","None\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"3UbZmZppLtTa","executionInfo":{"status":"ok","timestamp":1604286058119,"user_tz":-60,"elapsed":7843,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"e0bb8358-dd06-4863-9e81-349129d0bfc8","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.output_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(None, 100, 100, 3)"]},"metadata":{"tags":[]},"execution_count":33}]},{"cell_type":"markdown","metadata":{"id":"HyEDJAeDLtTi"},"source":["# Callbacks"]},{"cell_type":"code","metadata":{"id":"fy2CsXs-LtTj"},"source":["from training.callbacks.sample_generation import SampleGeneration\n","from training.callbacks.save_model import ModelSaver"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"AZUb0DiGLtTn"},"source":["es = tf.keras.callbacks.EarlyStopping(\n","    monitor='val_loss', \n","    min_delta=1e-15, \n","    patience=10, \n","    verbose=1, \n","    restore_best_weights=False\n",")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"T5J5NqwvLtTz"},"source":["ms = ModelSaver(filepath=_restore)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"yI9Le-fxLtT9","executionInfo":{"status":"ok","timestamp":1604286064735,"user_tz":-60,"elapsed":859,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"accd36bc-aca1-4c77-87e9-1418fa9be538","colab":{"base_uri":"https://localhost:8080/"}},"source":["csv_dir = os.path.join(experiments_dir, 'csv_dir')\n","create_if_not_exist(csv_dir)\n","csv_dir = os.path.join(csv_dir, ae.name+'.csv')\n","csv_log = tf.keras.callbacks.CSVLogger(csv_dir, append=True)\n","csv_dir"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/csv_dir/pokemonAE_Dense_reconst_1ell_01sharpdiff.csv'"]},"metadata":{"tags":[]},"execution_count":37}]},{"cell_type":"code","metadata":{"id":"GGO9xLWyLtUF"},"source":["image_gen_dir = os.path.join(experiments_dir, 'image_gen_dir')\n","create_if_not_exist(image_gen_dir)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"fHO4i3nTLtUM"},"source":["sg = SampleGeneration(latents_shape=latents_dim, filepath=image_gen_dir, gen_freq=5, save_img=True, gray_plot=False)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"mFaHXWenLtUU"},"source":["import numpy as np"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"fbIa6Q7XLtUc"},"source":["# Model Training"]},{"cell_type":"code","metadata":{"scrolled":true,"id":"K7DvdEHuLtUc","executionInfo":{"status":"ok","timestamp":1604293370515,"user_tz":-60,"elapsed":7305457,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"961e8166-3a68-4697-d52a-6c4267b88532","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.fit(\n","    x=train_generator,\n","    input_kw='images',\n","    steps_per_epoch=int(5e3),\n","    epochs=int(1e6), \n","    verbose=2,\n","    callbacks=[es, ms, csv_log, sg],\n","    workers=-1,\n","    use_multiprocessing=True,\n","    validation_data=val_generator,\n","    validation_steps=int(1e4)\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Epoch 1/1000000\n","\n","Epoch 00001: loss improved from inf to 4000.88159, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 612s - loss: 4000.8816 - psnr: 13.2424 - total_variation: 102658.3672 - ssim_multiscale: 6.7675 - sharpdiff: 5.3225 - mean_absolute_error: 0.1214 - mean_squared_error: 0.0482 - val_loss: 6251.0254 - val_psnr: 12.1432 - val_total_variation: 22254.9453 - val_ssim_multiscale: 4.3933 - val_sharpdiff: 9.2693 - val_mean_absolute_error: 0.1865 - val_mean_squared_error: 0.0644\n","Epoch 2/1000000\n","\n","Epoch 00002: loss improved from 4000.88159 to 3966.60840, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 615s - loss: 3966.6084 - psnr: 13.2726 - total_variation: 102759.2969 - ssim_multiscale: 6.7876 - sharpdiff: 5.3245 - mean_absolute_error: 0.1197 - mean_squared_error: 0.0478 - val_loss: 5849.5669 - val_psnr: 12.3519 - val_total_variation: 21044.7227 - val_ssim_multiscale: 4.7056 - val_sharpdiff: 9.4176 - val_mean_absolute_error: 0.1763 - val_mean_squared_error: 0.0611\n","Epoch 3/1000000\n","\n","Epoch 00003: loss improved from 3966.60840 to 3953.45850, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 609s - loss: 3953.4585 - psnr: 13.2907 - total_variation: 102643.2734 - ssim_multiscale: 6.8030 - sharpdiff: 5.3363 - mean_absolute_error: 0.1183 - mean_squared_error: 0.0477 - val_loss: 6692.6636 - val_psnr: 11.7276 - val_total_variation: 22100.2109 - val_ssim_multiscale: 4.1124 - val_sharpdiff: 9.2485 - val_mean_absolute_error: 0.2016 - val_mean_squared_error: 0.0703\n","Epoch 4/1000000\n","\n","Epoch 00004: loss improved from 3953.45850 to 3925.65796, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 611s - loss: 3925.6580 - psnr: 13.3104 - total_variation: 102592.3906 - ssim_multiscale: 6.8108 - sharpdiff: 5.3431 - mean_absolute_error: 0.1170 - mean_squared_error: 0.0475 - val_loss: 6505.2417 - val_psnr: 11.9113 - val_total_variation: 19498.3770 - val_ssim_multiscale: 4.2165 - val_sharpdiff: 9.4876 - val_mean_absolute_error: 0.1936 - val_mean_squared_error: 0.0680\n","Epoch 5/1000000\n","\n","Epoch 00005: loss improved from 3925.65796 to 3887.73096, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 606s - loss: 3887.7310 - psnr: 13.3339 - total_variation: 102567.2500 - ssim_multiscale: 6.8271 - sharpdiff: 5.3512 - mean_absolute_error: 0.1155 - mean_squared_error: 0.0471 - val_loss: 7379.6626 - val_psnr: 11.3303 - val_total_variation: 20307.6230 - val_ssim_multiscale: 3.5919 - val_sharpdiff: 9.3265 - val_mean_absolute_error: 0.2163 - val_mean_squared_error: 0.0775\n","Epoch 6/1000000\n","\n","Epoch 00006: loss improved from 3887.73096 to 3887.61694, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 604s - loss: 3887.6169 - psnr: 13.3416 - total_variation: 102498.4766 - ssim_multiscale: 6.8364 - sharpdiff: 5.3595 - mean_absolute_error: 0.1147 - mean_squared_error: 0.0472 - val_loss: 7589.9937 - val_psnr: 11.2133 - val_total_variation: 14409.8428 - val_ssim_multiscale: 3.5288 - val_sharpdiff: 9.8047 - val_mean_absolute_error: 0.2201 - val_mean_squared_error: 0.0806\n","Epoch 7/1000000\n","\n","Epoch 00007: loss improved from 3887.61694 to 3864.26880, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 609s - loss: 3864.2688 - psnr: 13.3568 - total_variation: 102448.7891 - ssim_multiscale: 6.8428 - sharpdiff: 5.3656 - mean_absolute_error: 0.1137 - mean_squared_error: 0.0469 - val_loss: 8091.3745 - val_psnr: 11.1222 - val_total_variation: 15077.7266 - val_ssim_multiscale: 3.4211 - val_sharpdiff: 9.7537 - val_mean_absolute_error: 0.2100 - val_mean_squared_error: 0.0840\n","Epoch 8/1000000\n","\n","Epoch 00008: loss improved from 3864.26880 to 3850.46997, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 603s - loss: 3850.4700 - psnr: 13.3668 - total_variation: 102411.9609 - ssim_multiscale: 6.8520 - sharpdiff: 5.3719 - mean_absolute_error: 0.1128 - mean_squared_error: 0.0468 - val_loss: 7376.1567 - val_psnr: 11.4068 - val_total_variation: 12179.6924 - val_ssim_multiscale: 3.9488 - val_sharpdiff: 10.0867 - val_mean_absolute_error: 0.2009 - val_mean_squared_error: 0.0796\n","Epoch 9/1000000\n","\n","Epoch 00009: loss did not improve from 3850.46997\n","5000/5000 - 598s - loss: 3852.6785 - psnr: 13.3713 - total_variation: 102351.0938 - ssim_multiscale: 6.8563 - sharpdiff: 5.3773 - mean_absolute_error: 0.1124 - mean_squared_error: 0.0468 - val_loss: 7703.9404 - val_psnr: 11.1586 - val_total_variation: 10285.0693 - val_ssim_multiscale: 3.6750 - val_sharpdiff: 10.1966 - val_mean_absolute_error: 0.2102 - val_mean_squared_error: 0.0843\n","Epoch 10/1000000\n","\n","Epoch 00010: loss improved from 3850.46997 to 3830.69067, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 601s - loss: 3830.6907 - psnr: 13.3804 - total_variation: 102317.8750 - ssim_multiscale: 6.8609 - sharpdiff: 5.3806 - mean_absolute_error: 0.1117 - mean_squared_error: 0.0467 - val_loss: 7407.7173 - val_psnr: 11.3200 - val_total_variation: 11536.7793 - val_ssim_multiscale: 3.8699 - val_sharpdiff: 10.1069 - val_mean_absolute_error: 0.2055 - val_mean_squared_error: 0.0807\n","Epoch 11/1000000\n","\n","Epoch 00011: loss did not improve from 3830.69067\n","5000/5000 - 603s - loss: 3834.1165 - psnr: 13.3830 - total_variation: 102271.2656 - ssim_multiscale: 6.8646 - sharpdiff: 5.3851 - mean_absolute_error: 0.1114 - mean_squared_error: 0.0467 - val_loss: 7603.3765 - val_psnr: 11.1534 - val_total_variation: 11379.4229 - val_ssim_multiscale: 3.6483 - val_sharpdiff: 10.0877 - val_mean_absolute_error: 0.2137 - val_mean_squared_error: 0.0836\n","Epoch 12/1000000\n","\n","Epoch 00012: loss improved from 3830.69067 to 3817.16919, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_1ell_01sharpdiff/var_save_dir\n","5000/5000 - 617s - loss: 3817.1692 - psnr: 13.3906 - total_variation: 102263.1562 - ssim_multiscale: 6.8664 - sharpdiff: 5.3883 - mean_absolute_error: 0.1108 - mean_squared_error: 0.0465 - val_loss: 7977.8276 - val_psnr: 10.9755 - val_total_variation: 9654.4629 - val_ssim_multiscale: 3.5759 - val_sharpdiff: 10.2382 - val_mean_absolute_error: 0.2146 - val_mean_squared_error: 0.0882\n","Epoch 00012: early stopping\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["<tensorflow.python.keras.callbacks.History at 0x7fc68a0d1dd8>"]},"metadata":{"tags":[]},"execution_count":41}]},{"cell_type":"markdown","metadata":{"id":"UhSTW1KSQeC_"},"source":["# Model Evaluation"]},{"cell_type":"markdown","metadata":{"id":"hCPgsBp9QeDA"},"source":["## inception_score"]},{"cell_type":"code","metadata":{"id":"w0wPQHi0QeDB"},"source":["from evaluation.generativity_metrics.inception_metrics import inception_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"7c7I66B9QeDF","executionInfo":{"status":"ok","timestamp":1604309993330,"user_tz":-60,"elapsed":23916917,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"5f43f2a9-1d90-434b-ef4d-17fd0bcbdf08","colab":{"base_uri":"https://localhost:8080/"}},"source":["is_mean, is_sigma = inception_score(ae, tolerance_threshold=1e-6, max_iteration=300)\n","print(f'inception_score mean: {is_mean.compute()}, sigma: {is_sigma.compute()}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5\n","87916544/87910968 [==============================] - 0s 0us/step\n","calculating the inception_score mean ...\n","WARNING:tensorflow:Model was constructed with shape (None, 75, 75, 3) for input Tensor(\"input_1:0\", shape=(None, 75, 75, 3), dtype=float32), but it was called on an input with incompatible shape (None, 100, 100, 3).\n"],"name":"stdout"},{"output_type":"stream","text":["300it [2:18:09, 27.07s/it]"],"name":"stderr"},{"output_type":"stream","text":["calculating the inception_score sigma ...\n"],"name":"stdout"},{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/dask/array/routines.py:780: RuntimeWarning: Degrees of freedom <= 0 for slice\n","  warnings.warn(\"Degrees of freedom <= 0 for slice\", RuntimeWarning)\n","0it [00:00, ?it/s]/usr/local/lib/python3.6/dist-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide\n","  return func(*(_execute_task(a, cache) for a in args))\n","1it [00:27, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","2it [00:53, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","3it [01:20, 26.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","4it [01:47, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","5it [02:14, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","6it [02:40, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","7it [03:07, 26.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","8it [03:33, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","9it [04:00, 26.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","10it [04:26, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","11it [04:54, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","12it [05:20, 26.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","13it [05:46, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","14it [06:13, 26.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","15it [06:40, 26.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","16it [07:07, 26.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","17it [07:34, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","18it [08:01, 26.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","19it [08:27, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","20it [08:54, 26.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","21it [09:21, 26.76s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","22it [09:48, 26.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","23it [10:15, 26.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","24it [10:42, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","25it [11:10, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","26it [11:37, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","27it [12:05, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","28it [12:33, 27.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","29it [13:00, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","30it [13:28, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","31it [13:56, 27.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","32it [14:24, 27.83s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","33it [14:52, 27.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","34it [15:21, 28.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","35it [15:49, 28.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","36it [16:17, 28.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","37it [16:45, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","38it [17:13, 28.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","39it [17:41, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","40it [18:09, 28.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","41it [18:38, 28.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","42it [19:06, 28.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","43it [19:34, 28.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","44it [20:02, 28.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","45it [20:31, 28.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","46it [20:59, 28.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","47it [21:27, 28.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","48it [21:55, 28.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","49it [22:24, 28.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","50it [22:53, 28.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","51it [23:21, 28.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","52it [23:49, 28.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","53it [24:18, 28.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","54it [24:46, 28.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","55it [25:14, 28.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","56it [25:43, 28.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","57it [26:11, 28.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","58it [26:40, 28.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","59it [27:08, 28.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","60it [27:37, 28.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","61it [28:05, 28.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","62it [28:34, 28.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","63it [29:02, 28.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","64it [29:31, 28.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","65it [29:59, 28.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","66it [30:28, 28.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","67it [30:57, 28.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","68it [31:25, 28.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","69it [31:54, 28.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","70it [32:22, 28.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","71it [32:51, 28.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","72it [33:20, 28.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","73it [33:48, 28.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","74it [34:17, 28.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","75it [34:46, 28.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","76it [35:14, 28.66s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","77it [35:43, 28.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","78it [36:12, 28.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","79it [36:40, 28.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","80it [37:08, 28.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","82it [38:05, 28.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","83it [38:33, 28.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","84it [39:01, 28.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","85it [39:29, 28.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","86it [39:57, 28.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","87it [40:24, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","88it [40:52, 27.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","89it [41:20, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","90it [41:48, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","91it [42:16, 27.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","92it [42:44, 27.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","93it [43:11, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","94it [43:39, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","95it [44:07, 27.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","96it [44:34, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","97it [45:01, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","98it [45:28, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","99it [45:56, 27.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","100it [46:23, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","101it [46:50, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","102it [47:17, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","103it [47:45, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","104it [48:12, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","105it [48:39, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","106it [49:06, 27.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","107it [49:34, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","108it [50:02, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","109it [50:30, 27.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","110it [50:58, 27.80s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","111it [51:26, 27.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","112it [51:54, 27.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","113it [52:22, 27.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","114it [52:51, 28.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","115it [53:21, 28.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","116it [53:49, 28.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","117it [54:18, 28.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","118it [54:47, 28.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","119it [55:15, 28.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","120it [55:44, 28.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","121it [56:12, 28.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","122it [56:41, 28.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","123it [57:09, 28.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","124it [57:37, 28.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","125it [58:06, 28.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","126it [58:35, 28.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","127it [59:03, 28.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","128it [59:31, 28.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","129it [59:59, 28.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","130it [1:00:27, 28.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","131it [1:00:55, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","132it [1:01:22, 27.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","133it [1:01:51, 28.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","134it [1:02:18, 27.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","135it [1:02:46, 27.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","136it [1:03:14, 27.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","137it [1:03:42, 27.90s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","138it [1:04:10, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","139it [1:04:38, 27.90s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","140it [1:05:05, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","141it [1:05:34, 27.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","142it [1:06:01, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","143it [1:06:29, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","144it [1:06:57, 27.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","145it [1:07:25, 27.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","146it [1:07:52, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","147it [1:08:20, 27.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","148it [1:08:48, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","149it [1:09:15, 27.67s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","150it [1:09:43, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","151it [1:10:10, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","152it [1:10:38, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","153it [1:11:05, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","154it [1:11:33, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","155it [1:12:00, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","156it [1:12:28, 27.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","157it [1:12:56, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","158it [1:13:23, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","159it [1:13:51, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","160it [1:14:18, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","161it [1:14:45, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","162it [1:15:13, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","163it [1:15:40, 27.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","164it [1:16:08, 27.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","165it [1:16:35, 27.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","166it [1:17:02, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","167it [1:17:30, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","168it [1:17:57, 27.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","169it [1:18:25, 27.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","170it [1:18:52, 27.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","171it [1:19:19, 27.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","172it [1:19:47, 27.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","173it [1:20:14, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","174it [1:20:41, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","175it [1:21:09, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","176it [1:21:36, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","177it [1:22:03, 27.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","178it [1:22:31, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","179it [1:22:58, 27.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","180it [1:23:25, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","181it [1:23:53, 27.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","182it [1:24:20, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","183it [1:24:47, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","184it [1:25:14, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","185it [1:25:42, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","186it [1:26:09, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","187it [1:26:36, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","188it [1:27:03, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","189it [1:27:31, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","190it [1:27:58, 27.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","191it [1:28:25, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","192it [1:28:52, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","193it [1:29:20, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","194it [1:29:47, 27.28s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","195it [1:30:14, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","196it [1:30:41, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","197it [1:31:08, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","198it [1:31:36, 27.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","199it [1:32:03, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","200it [1:32:30, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","201it [1:32:57, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","202it [1:33:25, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","203it [1:33:52, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","204it [1:34:19, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","205it [1:34:46, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","206it [1:35:12, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","207it [1:35:41, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","208it [1:36:09, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","209it [1:36:37, 27.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","210it [1:37:05, 27.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","211it [1:37:33, 27.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","212it [1:38:01, 27.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","213it [1:38:29, 27.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","214it [1:38:57, 27.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","215it [1:39:25, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","216it [1:39:53, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","217it [1:40:20, 27.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","218it [1:40:48, 27.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","219it [1:41:16, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","220it [1:41:43, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","221it [1:42:10, 27.56s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","222it [1:42:37, 27.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","223it [1:43:05, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","224it [1:43:31, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","225it [1:43:58, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","226it [1:44:25, 26.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","227it [1:44:51, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","228it [1:45:17, 26.69s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","229it [1:45:44, 26.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","230it [1:46:11, 26.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","231it [1:46:37, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","232it [1:47:04, 26.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","233it [1:47:30, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","234it [1:47:57, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","235it [1:48:23, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","236it [1:48:50, 26.57s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","237it [1:49:16, 26.50s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","238it [1:49:43, 26.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","239it [1:50:09, 26.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","240it [1:50:36, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","241it [1:51:03, 26.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","242it [1:51:29, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","243it [1:51:56, 26.54s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","244it [1:52:22, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","245it [1:52:48, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","246it [1:53:15, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","247it [1:53:42, 26.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","248it [1:54:08, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","249it [1:54:35, 26.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","250it [1:55:01, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","251it [1:55:28, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","252it [1:55:54, 26.47s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","253it [1:56:20, 26.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","254it [1:56:47, 26.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","255it [1:57:13, 26.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","256it [1:57:39, 26.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","257it [1:58:06, 26.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","258it [1:58:32, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","259it [1:58:59, 26.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","260it [1:59:26, 26.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","261it [1:59:52, 26.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","262it [2:00:18, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","263it [2:00:44, 26.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","264it [2:01:11, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","265it [2:01:37, 26.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","266it [2:02:04, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","267it [2:02:30, 26.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","268it [2:02:56, 26.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","269it [2:03:23, 26.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","270it [2:03:49, 26.45s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","271it [2:04:15, 26.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","272it [2:04:42, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","273it [2:05:08, 26.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","274it [2:05:35, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","275it [2:06:01, 26.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","276it [2:06:28, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","277it [2:06:54, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","278it [2:07:20, 26.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","279it [2:07:47, 26.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","280it [2:08:13, 26.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","281it [2:08:39, 26.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","282it [2:09:06, 26.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","283it [2:09:32, 26.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","284it [2:09:58, 26.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","285it [2:10:25, 26.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","286it [2:10:51, 26.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","287it [2:11:18, 26.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","288it [2:11:44, 26.38s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","289it [2:12:11, 26.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","290it [2:12:37, 26.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","291it [2:13:03, 26.41s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","292it [2:13:30, 26.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","293it [2:13:56, 26.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","294it [2:14:23, 26.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","295it [2:14:49, 26.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","296it [2:15:16, 26.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","297it [2:15:42, 26.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","298it [2:16:08, 26.42s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","299it [2:16:35, 26.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","300it [2:17:01, 26.43s/it]"],"name":"stderr"},{"output_type":"stream","text":["inception_score mean: [5.71726667e+157], sigma: inf\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"Qk6qBylRQeDJ"},"source":["\n","## Frechet_inception_distance\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"t54Qm7_FQeDK"},"source":["from evaluation.generativity_metrics.inception_metrics import frechet_inception_distance"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"p-_KQpVPQeDP"},"source":["fis_score = frechet_inception_distance(ae, train_generator.as_numpy_iterator(), \n","                                       tolerance_threshold=1e-6, \n","                                       max_iteration=300, \n","                                       batch_size=32)\n"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"GtJ1QNcx_rt2"},"source":["print(f'frechet inception distance: {fis_score.compute()}')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"dS4QPAXoQeDX"},"source":["## perceptual_path_length_score"]},{"cell_type":"code","metadata":{"id":"FHxOntNaQeDZ"},"source":["from evaluation.generativity_metrics.perceptual_path_length import perceptual_path_length_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"FtgoCP49QeDj","executionInfo":{"status":"ok","timestamp":1604310260480,"user_tz":-60,"elapsed":24181544,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"6dd55f4a-7823-461f-d7cc-30d08cd887d2","colab":{"base_uri":"https://localhost:8080/"}},"source":["ppl_mean_score = perceptual_path_length_score(ae, train_generator.as_numpy_iterator(), \n","                                              tolerance_threshold=1e-6, \n","                                              max_iteration=300, \n","                                              batch_size=32)\n","print(f'perceptual path length score: {ppl_mean_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5\n","58892288/58889256 [==============================] - 1s 0us/step\n"],"name":"stdout"},{"output_type":"stream","text":["300it [04:24,  1.13it/s]"],"name":"stderr"},{"output_type":"stream","text":["perceptual path length score: 5193.7294921875\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"l6zFWvmtQeDr"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Y8mKKa7hQeDv"},"source":["## precision score"]},{"cell_type":"code","metadata":{"id":"2VF-JOv3QeDx"},"source":["from evaluation.generativity_metrics.precision_recall import precision_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"vT1C64RdQeD5","executionInfo":{"status":"ok","timestamp":1604310260767,"user_tz":-60,"elapsed":24180283,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"8345ad3f-4e88-4716-c93c-c5b2bb2bcf98","colab":{"base_uri":"https://localhost:8080/"}},"source":["_precision_score = precision_score(ae,  train_generator.as_numpy_iterator(), \n","                                   tolerance_threshold=1e-6, \n","                                   max_iteration=300)\n","print(f'precision score: {_precision_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00248241s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00180984s\n","precision score: [0.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"M4JbbHnQQeD-"},"source":["## recall score"]},{"cell_type":"code","metadata":{"id":"RhwDYty1QeEA"},"source":["from evaluation.generativity_metrics.precision_recall import recall_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LMzfn5KHQeEF","executionInfo":{"status":"ok","timestamp":1604310261537,"user_tz":-60,"elapsed":24178226,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"303ef419-09f8-4c1c-9a46-7c21e621a7fe","colab":{"base_uri":"https://localhost:8080/"}},"source":["_recall_score = recall_score(ae, train_generator.as_numpy_iterator(), tolerance_threshold=1e-6, max_iteration=300)\n","print(f'recall score: {_recall_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00187397s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00173426s\n","recall score: [1.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"nQH-mfDmQeEJ"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"9vPAhxCyQeEQ"},"source":["# Image Generation"]},{"cell_type":"markdown","metadata":{"id":"s5OsqNYaQeES"},"source":["## image reconstruction"]},{"cell_type":"markdown","metadata":{"id":"oEEynQF2QeET"},"source":["### Training dataset"]},{"cell_type":"code","metadata":{"id":"Fg1wGMkRQeEU"},"source":["from training.generators.from_images.image_generation_testing import reconstruct_from_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZSJ55VozQeEZ","executionInfo":{"status":"ok","timestamp":1604310265442,"user_tz":-60,"elapsed":24180250,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"b06047b7-20e3-4de5-9c42-7c006ac50f39","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:03,  2.60it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"G1_8VcdJQeEl","executionInfo":{"status":"ok","timestamp":1604310270033,"user_tz":-60,"elapsed":24184812,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"4ae6d784-3333-4324-e0f7-af4c033a3140","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:04,  2.29it/s]\n"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"iwDP-H8cQeEq"},"source":["## with Randomness"]},{"cell_type":"code","metadata":{"id":"4YXvt2J8QeEr"},"source":["from training.generators.from_images.image_generation_testing import generate_images_like_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Lxr8AimWQeEy","executionInfo":{"status":"ok","timestamp":1604310274331,"user_tz":-60,"elapsed":24189071,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"58fa4db1-8edd-419e-ee85-834fcc85cc81","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:04,  2.23it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"VfEeBtsxQeE7","executionInfo":{"status":"ok","timestamp":1604310279448,"user_tz":-60,"elapsed":24194162,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"44eaa464-3818-43b7-d2ba-62410b8eb322","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:04,  2.14it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"pHRCUI6eQeFD"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"TdeyPBhtQeFG"},"source":["### Complete Randomness"]},{"cell_type":"code","metadata":{"id":"Tr8JPmloQeFH"},"source":["from training.generators.from_images.image_generation_testing import generate_images_randomly"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"9OZuHVx2QeFK","executionInfo":{"status":"ok","timestamp":1604310286719,"user_tz":-60,"elapsed":24201373,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"e12e460c-79f8-4d32-9b29-80fb91a052c9","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'random_synthetic_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_randomly(ae, save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["32it [00:07,  4.28it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"Jh8HeIbMQeFR"},"source":["from training.generators.from_images.image_generation_testing import interpolate_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"oKULH_U9QeFW","executionInfo":{"status":"ok","timestamp":1604310287526,"user_tz":-60,"elapsed":24202146,"user":{"displayName":"Mina Atteia`","photoUrl":"","userId":"18048956301099950853"}},"outputId":"2087a728-0e16-412c-b824-f852254a3ae0","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'interpolate_dir')\n","create_if_not_exist(save_dir)\n","\n","interpolate_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 131.89it/s]\n","10it [00:00, 143.70it/s]\n","0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["\n","\n","\n"],"name":"stdout"},{"output_type":"stream","text":["10it [00:00, 132.60it/s]\n","10it [00:00, 138.24it/s]\n","100%|██████████| 4/4 [00:00<00:00, 11.49it/s]\n","10it [00:00, 129.97it/s]\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Fuhv1qXyQeFb"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"i0mPqk0UQeFg"},"source":[""],"execution_count":null,"outputs":[]}]}