{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"colab":{"name":"pokemonAE_Dense_reconst_psnr.ipynb","provenance":[],"collapsed_sections":["i5fK5_BwMKo6","lRsHN94YMKpL","GLKsP82XMKqe","Qo4auPx6MKq-","UhSTW1KSQeC_","hCPgsBp9QeDA","Qk6qBylRQeDJ","dS4QPAXoQeDX","Y8mKKa7hQeDv","M4JbbHnQQeD-","9vPAhxCyQeEQ","s5OsqNYaQeES","oEEynQF2QeET","iwDP-H8cQeEq","TdeyPBhtQeFG"],"toc_visible":true},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","metadata":{"id":"dSivKYUtmzyh"},"source":["**Trained and tested except Frechet**"]},{"cell_type":"code","metadata":{"id":"NmPagHhWID9D"},"source":["%load_ext autoreload\n","%autoreload 2"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"FaAUkhTxnzQT"},"source":["# Environment prep for Colab\n"," - download git repo \n"," - install required pip packages"]},{"cell_type":"code","metadata":{"id":"jRy-3Mj7Rn2h","executionInfo":{"status":"ok","timestamp":1604287119688,"user_tz":-60,"elapsed":26549,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"e0d7b172-5266-417a-ea34-f2c552b8abe4","colab":{"base_uri":"https://localhost:8080/"}},"source":["!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Cloning into 'Generative_Models'...\n","remote: Enumerating objects: 15891, done.\u001b[K\n","remote: Total 15891 (delta 0), reused 0 (delta 0), pack-reused 15891\u001b[K\n","Receiving objects: 100% (15891/15891), 733.46 MiB | 45.84 MiB/s, done.\n","Resolving deltas: 100% (10845/10845), done.\n","Checking out files: 100% (1697/1697), done.\n","/content/Generative_Models\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0zbi2r-8nENp","scrolled":true,"executionInfo":{"status":"ok","timestamp":1604287148780,"user_tz":-60,"elapsed":55616,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"126fee88-8126-41bc-a5fd-bf92bc03f4fa","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well!git clone https://github.com/kkahloots/Generative_Models.git # this is for loading git with correct brach\n","%cd /content/Generative_Models/\n","!pip -q install -r /content/Generative_Models/requirements.txt\n","!pip install colorlog==4.0.2\n","%cd /content/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Mounted at /content/drive\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n","/content/Generative_Models\n","Collecting colorlog==4.0.2\n","  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl\n","Installing collected packages: colorlog\n","Successfully installed colorlog-4.0.2\n","/content\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"N09gj2pVgT7R","executionInfo":{"status":"ok","timestamp":1604287148785,"user_tz":-60,"elapsed":55594,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"8fb5283a-285c-4551-cd44-cd656312407c","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"pDUjPvxE-DA2"},"source":["# Connect Drive to save and restore results"]},{"cell_type":"code","metadata":{"id":"YqhHHzGuEAi1","executionInfo":{"status":"ok","timestamp":1604287148787,"user_tz":-60,"elapsed":53141,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"98aff784-6a57-46ba-f9ba-a74897da70be","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","!mkdir /content/drive/My\\ Drive/Results\n","MAIN_SAVE_DIR = '/content/drive/My Drive/Results'\n","IMG_DIR = '/content/Generative_Models/data/.pokemon' #change .qbert here as well"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n","mkdir: cannot create directory ‘/content/drive/My Drive/Results’: File exists\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"39O7_8FyQeAF"},"source":["# Settings"]},{"cell_type":"code","metadata":{"id":"A7JMGRKYQeAG","executionInfo":{"status":"ok","timestamp":1604287148789,"user_tz":-60,"elapsed":51767,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"2f003786-6fd2-486c-acae-13bed7f7cc7b","colab":{"base_uri":"https://localhost:8080/"}},"source":["%env TF_KERAS = 1\n","import os\n","sep_local = os.path.sep\n","\n","import sys\n","sys.path.append('..'+sep_local+'..')\n","print(sep_local)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["env: TF_KERAS=1\n","/\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"RPwxSJHtQeAM","executionInfo":{"status":"ok","timestamp":1604287149951,"user_tz":-60,"elapsed":52906,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"f6f94e86-5815-456b-d0cd-6252b32abd7b","colab":{"base_uri":"https://localhost:8080/"}},"source":["import tensorflow as tf\n","print(tf.__version__)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2.3.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"WjzDvWotQeAR","executionInfo":{"status":"ok","timestamp":1604287149954,"user_tz":-60,"elapsed":52887,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"cc75bb24-6ef6-48b8-ee7b-5779548f98ab","colab":{"base_uri":"https://localhost:8080/"}},"source":["#os.chdir('..'+sep_local+'..'+sep_local+'..'+sep_local+'..'+sep_local+'..')\n","os.chdir('/content/Generative_Models')\n","print(os.getcwd())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"sePRvXjHQeAX"},"source":["# only on colab"]},{"cell_type":"code","metadata":{"id":"jKLnMEbfQeAa"},"source":["!cat data/.pokemon/pokemon.tar.part* > data/.pokemon/pokemon.tar"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"low1ZyVAQeAh","executionInfo":{"status":"ok","timestamp":1604287151677,"user_tz":-60,"elapsed":51623,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"069168e7-c99d-4d29-9147-e73039e4b213","colab":{"base_uri":"https://localhost:8080/"}},"source":["!tar -xvf data/.pokemon/pokemon.tar --directory data/.pokemon/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Pokemon_LMDB/_training/\n","Pokemon_LMDB/_training/lock.mdb\n","Pokemon_LMDB/_training/data.mdb\n","Pokemon_LMDB/_validation/\n","Pokemon_LMDB/_validation/lock.mdb\n","Pokemon_LMDB/_validation/data.mdb\n","Pokemon_LMDB/meta_info.json\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"001UYhPAMKn9"},"source":["# Dataset loading"]},{"cell_type":"code","metadata":{"id":"M-zHJXlLMKn_"},"source":["from training.generators.from_lmdb.lmdb_image_generator import get_generators"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"oXRyeW_6MKoI"},"source":["dataset_name='pokemon'\n","inputs_shape= image_shape=(100, 100, 3)\n","batch_size = 10\n","latents_dim = 100\n","intermediate_dim = 50\n","lmdb_dir = 'data/.pokemon/Pokemon_LMDB'"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"PgOK7t_zMKoR"},"source":["from transformation.lmdb_transformer import LmdbTransformer"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"mlsKabjAMKoa","executionInfo":{"status":"ok","timestamp":1604287202491,"user_tz":-60,"elapsed":6692,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"460fe497-2d1b-440d-e975-e4087bedf152","colab":{"base_uri":"https://localhost:8080/"}},"source":["train_generator, val_generator = get_generators(\n","        lmdb_dir=lmdb_dir,\n","        batch_size=batch_size,\n","        episode_len=None,\n","        episode_shift=None\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/transformation/file_image_generator.py:51: UserWarning: No files found\n","  warnings.warn(msg)\n"],"name":"stderr"},{"output_type":"stream","text":["Initializing Iterator training Number of images 591\n","Initializing Iterator validation Number of images 218\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"azeY5KH0MKom","executionInfo":{"status":"ok","timestamp":1604287202499,"user_tz":-60,"elapsed":4246,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"7dc3b2e9-4049-4a5e-d5e2-8a302997b39b","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","_instance_scale=1.0\n","for data in val_generator:\n","    print(np.max(data['images']))\n","    break\n","    #print(data.keys())"],"execution_count":null,"outputs":[{"output_type":"stream","text":["1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"d_P1loVeMKou","executionInfo":{"status":"ok","timestamp":1604287202502,"user_tz":-60,"elapsed":2887,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"68c5f6ee-125c-42d2-ebd0-266690d5b4d6","colab":{"base_uri":"https://localhost:8080/"}},"source":["data['images'][0].shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["TensorShape([100, 100, 3])"]},"metadata":{"tags":[]},"execution_count":18}]},{"cell_type":"code","metadata":{"id":"u-87k1lbMKo0","executionInfo":{"status":"ok","timestamp":1604287202507,"user_tz":-60,"elapsed":1908,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"a17956ca-01d5-4a9f-dd26-0d44d29c7b09","colab":{"base_uri":"https://localhost:8080/"}},"source":["data.keys()"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["dict_keys(['images', 'label'])"]},"metadata":{"tags":[]},"execution_count":19}]},{"cell_type":"markdown","metadata":{"id":"i5fK5_BwMKo6"},"source":["# Model's Layers definition"]},{"cell_type":"code","metadata":{"id":"1Rnzk2giMKo7","executionInfo":{"status":"ok","timestamp":1604287205567,"user_tz":-60,"elapsed":897,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"3a141f11-c349-49bd-c150-1e31fcf19ed6","colab":{"base_uri":"https://localhost:8080/"}},"source":["import numpy as np\n","from collections.abc import Iterable\n","if isinstance(inputs_shape, Iterable):\n","    flat_outputs_shape = np.prod(inputs_shape)\n","flat_outputs_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["30000"]},"metadata":{"tags":[]},"execution_count":20}]},{"cell_type":"code","metadata":{"id":"aNiU1mP1MKpA","executionInfo":{"status":"ok","timestamp":1604287205574,"user_tz":-60,"elapsed":871,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"0a2cc9cf-6768-4fcf-a7b0-5ca05eeb2bfe","colab":{"base_uri":"https://localhost:8080/"}},"source":["latents_dim"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["100"]},"metadata":{"tags":[]},"execution_count":21}]},{"cell_type":"code","metadata":{"id":"1pc5wDTjMKpF"},"source":["enc_lays = [tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Dense(units=intermediate_dim, activation='relu'),\n","            tf.keras.layers.Flatten(),\n","            tf.keras.layers.Dense(units=latents_dim)]\n","\n","dec_lays = [tf.keras.layers.Dense(units=latents_dim, activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","            tf.keras.layers.Dense(units= latents_dim*intermediate_dim//3 , activation='relu'),\n","\n","            tf.keras.layers.Dense(units=flat_outputs_shape),\n","            tf.keras.layers.Reshape(inputs_shape)]"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"lRsHN94YMKpL"},"source":["# Model definition"]},{"cell_type":"code","metadata":{"id":"TRLXGtK5MKpM","executionInfo":{"status":"ok","timestamp":1604287213707,"user_tz":-60,"elapsed":932,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"b1388152-8756-4a57-a11d-7ab7dc11eac3","colab":{"base_uri":"https://localhost:8080/"}},"source":["model_name = dataset_name+'AE_Dense_reconst_psnr'\n","experiments_dir='/content/drive/My Drive/Results'+sep_local+model_name\n","print(experiments_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"Anfgni8HMKpR"},"source":["from training.autoencoding_basic.autoencoders.autoencoder import autoencoder as AE"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"YKn4Ox4VMKpb"},"source":["variables_params = \\\n","[\n","    {\n","        'name': 'inference', \n","        'inputs_shape':inputs_shape,\n","        'outputs_shape':latents_dim,\n","        'layers': enc_lays\n","    }\n","\n","    ,\n","    \n","        {\n","        'name': 'generative', \n","        'inputs_shape':latents_dim,\n","        'outputs_shape':inputs_shape,\n","        'layers':dec_lays\n","    }\n","]"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"uryWQfwRMKpk"},"source":["from utils.data_and_files.file_utils import create_if_not_exist"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"hp7KgVC8MKpt"},"source":["_restore = os.path.join(experiments_dir, 'var_save_dir')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"vQ-jA1AhMKp0","executionInfo":{"status":"ok","timestamp":1604287214757,"user_tz":-60,"elapsed":1932,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"59332c11-5e06-4ce9-ffde-453fd7d053c7","colab":{"base_uri":"https://localhost:8080/","height":35}},"source":["create_if_not_exist(_restore)\n","_restore"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir'"]},"metadata":{"tags":[]},"execution_count":28}]},{"cell_type":"code","metadata":{"id":"hkJkdDgvMKp6"},"source":["#to restore trained model, set filepath=_restore"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":false,"id":"_yVJ2dL8MKqE","executionInfo":{"status":"ok","timestamp":1604287215214,"user_tz":-60,"elapsed":2365,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"40072eef-ff44-4811-da60-bd8202b4d42f","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae = AE( \n","    name=model_name,\n","    latents_dim=latents_dim,\n","    batch_size=batch_size,\n","    variables_params=variables_params, \n","    filepath=_restore\n","    )"],"execution_count":null,"outputs":[{"output_type":"stream","text":["  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[37mDEBUG   \u001b[0m | \u001b[37mRestore old models ...\u001b[0m\n","  \u001b[31mERROR   \u001b[0m | \u001b[31mFaild to restore old models !\u001b[0m\n","  \u001b[31mERROR   \u001b[0m | \u001b[31mFaild to restore old models !\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["\n","SavedModel file does not exist at: /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir/pokemonAE_Dense_reconst_psnr_inference.hdf5/{saved_model.pbtxt|saved_model.pb}\n","\n","\n","Model: \"inference\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","dense (Dense)                (None, 100, 100, 50)      200       \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 100, 100, 50)      2550      \n","_________________________________________________________________\n","flatten (Flatten)            (None, 500000)            0         \n","_________________________________________________________________\n","dense_2 (Dense)              (None, 100)               50000100  \n","_________________________________________________________________\n","batch_normalization (BatchNo (None, 100)               400       \n","_________________________________________________________________\n","dropout (Dropout)            (None, 100)               0         \n","_________________________________________________________________\n","activity_regularization (Act (None, 100)               0         \n","_________________________________________________________________\n","inference_outputs (Activatio (None, 100)               0         \n","=================================================================\n","Total params: 50,003,250\n","Trainable params: 50,003,050\n","Non-trainable params: 200\n","_________________________________________________________________\n","\n"],"name":"stdout"},{"output_type":"stream","text":["  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n","  \u001b[33mWARNING \u001b[0m | \u001b[33mNone\u001b[0m\n"],"name":"stderr"},{"output_type":"stream","text":["Model: \"generative\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","generative_inputs (InputLaye [(None, 100)]             0         \n","_________________________________________________________________\n","dense_3 (Dense)              (None, 100)               10100     \n","_________________________________________________________________\n","dense_4 (Dense)              (None, 1666)              168266    \n","_________________________________________________________________\n","dense_5 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_6 (Dense)              (None, 1666)              2777222   \n","_________________________________________________________________\n","dense_7 (Dense)              (None, 30000)             50010000  \n","_________________________________________________________________\n","reshape (Reshape)            (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","batch_normalization_1 (Batch (None, 100, 100, 3)       12        \n","_________________________________________________________________\n","dropout_1 (Dropout)          (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","activity_regularization_1 (A (None, 100, 100, 3)       0         \n","_________________________________________________________________\n","generative_outputs (Activati (None, 100, 100, 3)       0         \n","=================================================================\n","Total params: 55,742,822\n","Trainable params: 55,742,816\n","Non-trainable params: 6\n","_________________________________________________________________\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"FhHpRqavMKqM"},"source":["from evaluation.quantitive_metrics.peak_signal_to_noise_ratio import prepare_psnr\n","#from statistical.losses_utilities import similarty_to_distance\n","from statistical.ae_losses import expected_loglikelihood_with_lower_bound as ellwlb"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"r8Bk96iRMKqR","executionInfo":{"status":"ok","timestamp":1604287215220,"user_tz":-60,"elapsed":2340,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"944114ec-1600-4168-e9d7-f68c000a5bc1","colab":{"base_uri":"https://localhost:8080/"}},"source":["#ae.compile(metrics=None)\n","#ae.compile()\n","ae.compile(loss={'x_logits': lambda x_true, x_logits: prepare_psnr([ae.batch_size]+ae.get_inputs_shape())(x_true, x_logits)})"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Model: \"pokemonAE_Dense_reconst_psnr\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","inference_inputs (InputLayer [(None, 100, 100, 3)]     0         \n","_________________________________________________________________\n","inference (Functional)       (None, 100)               50003250  \n","_________________________________________________________________\n","generative (Functional)      (None, 100, 100, 3)       55742822  \n","_________________________________________________________________\n","tf_op_layer_x_logits (Tensor [(None, 100, 100, 3)]     0         \n","=================================================================\n","Total params: 105,746,072\n","Trainable params: 105,745,866\n","Non-trainable params: 206\n","_________________________________________________________________\n","None\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"BU1q6JH8MKqX","executionInfo":{"status":"ok","timestamp":1604287215222,"user_tz":-60,"elapsed":2322,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"75975efc-f5a3-4b4e-cb27-f3ca99566443","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.output_shape"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(None, 100, 100, 3)"]},"metadata":{"tags":[]},"execution_count":33}]},{"cell_type":"markdown","metadata":{"id":"GLKsP82XMKqe"},"source":["# Callbacks"]},{"cell_type":"code","metadata":{"id":"T6657w0QMKqg"},"source":["from training.callbacks.sample_generation import SampleGeneration\n","from training.callbacks.save_model import ModelSaver"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"TRwIi6k_MKqk"},"source":["es = tf.keras.callbacks.EarlyStopping(\n","    monitor='val_loss', \n","    min_delta=1e-15, \n","    patience=10, \n","    verbose=1, \n","    restore_best_weights=False\n",")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"AdXtK1rYMKqq"},"source":["ms = ModelSaver(filepath=_restore)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"k_3-k4W5MKqu","executionInfo":{"status":"ok","timestamp":1604287215664,"user_tz":-60,"elapsed":1202,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"b954caad-a89e-474c-b9f4-a90de0b16c12","colab":{"base_uri":"https://localhost:8080/"}},"source":["csv_dir = os.path.join(experiments_dir, 'csv_dir')\n","create_if_not_exist(csv_dir)\n","csv_dir = os.path.join(csv_dir, ae.name+'.csv')\n","csv_log = tf.keras.callbacks.CSVLogger(csv_dir, append=True)\n","csv_dir"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'/content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/csv_dir/pokemonAE_Dense_reconst_psnr.csv'"]},"metadata":{"tags":[]},"execution_count":37}]},{"cell_type":"code","metadata":{"id":"4f-1bFqHMKqz"},"source":["image_gen_dir = os.path.join(experiments_dir, 'image_gen_dir')\n","create_if_not_exist(image_gen_dir)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"4OHxJg8lMKq3"},"source":["sg = SampleGeneration(latents_shape=latents_dim, filepath=image_gen_dir, gen_freq=5, save_img=True, gray_plot=False)"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Qo4auPx6MKq-"},"source":["# Model Training"]},{"cell_type":"code","metadata":{"scrolled":true,"id":"tEGEwmkwMKq_","executionInfo":{"status":"ok","timestamp":1604293791574,"user_tz":-60,"elapsed":6575986,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"0197cde2-256a-4daf-8027-20a834df795c","colab":{"base_uri":"https://localhost:8080/"}},"source":["ae.fit(\n","    x=train_generator,\n","    input_kw='images',\n","    steps_per_epoch=int(5e3),\n","    epochs=int(1e6), \n","    verbose=2,\n","    callbacks=[es, ms, csv_log, sg],\n","    workers=-1,\n","    use_multiprocessing=True,\n","    validation_data=val_generator,\n","    validation_steps=int(1e4)\n",")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Epoch 1/1000000\n","\n","Epoch 00001: loss improved from inf to 3.36232, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 592s - loss: 3.3623 - psnr: 3.1129 - total_variation: 97443.8047 - ssim_multiscale: 0.0588 - sharpdiff: 4.6635 - mean_absolute_error: 0.6385 - mean_squared_error: 0.4982 - val_loss: 2.3288 - val_psnr: 2.0424 - val_total_variation: 16792.8281 - val_ssim_multiscale: 0.1873 - val_sharpdiff: 9.1081 - val_mean_absolute_error: 0.7377 - val_mean_squared_error: 0.6304\n","Epoch 2/1000000\n","\n","Epoch 00002: loss improved from 3.36232 to 2.68097, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 593s - loss: 2.6810 - psnr: 2.2654 - total_variation: 115206.4531 - ssim_multiscale: 0.1245 - sharpdiff: 4.1804 - mean_absolute_error: 0.7138 - mean_squared_error: 0.5963 - val_loss: 2.3365 - val_psnr: 2.0504 - val_total_variation: 19559.1035 - val_ssim_multiscale: 0.2291 - val_sharpdiff: 8.9062 - val_mean_absolute_error: 0.7357 - val_mean_squared_error: 0.6287\n","Epoch 3/1000000\n","\n","Epoch 00003: loss improved from 2.68097 to 2.58774, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 591s - loss: 2.5877 - psnr: 2.1711 - total_variation: 118345.4062 - ssim_multiscale: 0.1144 - sharpdiff: 4.1538 - mean_absolute_error: 0.7268 - mean_squared_error: 0.6091 - val_loss: 2.3968 - val_psnr: 2.1195 - val_total_variation: 24135.2715 - val_ssim_multiscale: 0.1412 - val_sharpdiff: 8.6078 - val_mean_absolute_error: 0.7280 - val_mean_squared_error: 0.6185\n","Epoch 4/1000000\n","\n","Epoch 00004: loss improved from 2.58774 to 2.55716, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 592s - loss: 2.5572 - psnr: 2.1419 - total_variation: 119125.4297 - ssim_multiscale: 0.1116 - sharpdiff: 4.1472 - mean_absolute_error: 0.7308 - mean_squared_error: 0.6132 - val_loss: 2.3434 - val_psnr: 2.0460 - val_total_variation: 21225.3848 - val_ssim_multiscale: 0.2261 - val_sharpdiff: 8.8000 - val_mean_absolute_error: 0.7349 - val_mean_squared_error: 0.6292\n","Epoch 5/1000000\n","\n","Epoch 00005: loss improved from 2.55716 to 2.54374, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 589s - loss: 2.5437 - psnr: 2.1294 - total_variation: 119336.7812 - ssim_multiscale: 0.1096 - sharpdiff: 4.1470 - mean_absolute_error: 0.7324 - mean_squared_error: 0.6149 - val_loss: 2.4098 - val_psnr: 2.1197 - val_total_variation: 24073.5742 - val_ssim_multiscale: 0.1565 - val_sharpdiff: 8.5939 - val_mean_absolute_error: 0.7276 - val_mean_squared_error: 0.6193\n","Epoch 6/1000000\n","\n","Epoch 00006: loss improved from 2.54374 to 2.54000, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 594s - loss: 2.5400 - psnr: 2.1261 - total_variation: 119426.2109 - ssim_multiscale: 0.1109 - sharpdiff: 4.1478 - mean_absolute_error: 0.7329 - mean_squared_error: 0.6154 - val_loss: 2.3667 - val_psnr: 2.0619 - val_total_variation: 22236.2793 - val_ssim_multiscale: 0.2065 - val_sharpdiff: 8.7048 - val_mean_absolute_error: 0.7335 - val_mean_squared_error: 0.6272\n","Epoch 7/1000000\n","\n","Epoch 00007: loss improved from 2.54000 to 2.53368, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 598s - loss: 2.5337 - psnr: 2.1202 - total_variation: 119512.9844 - ssim_multiscale: 0.1082 - sharpdiff: 4.1490 - mean_absolute_error: 0.7337 - mean_squared_error: 0.6162 - val_loss: 2.4520 - val_psnr: 2.1567 - val_total_variation: 24496.0703 - val_ssim_multiscale: 0.1291 - val_sharpdiff: 8.5511 - val_mean_absolute_error: 0.7232 - val_mean_squared_error: 0.6144\n","Epoch 8/1000000\n","\n","Epoch 00008: loss improved from 2.53368 to 2.53051, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 602s - loss: 2.5305 - psnr: 2.1175 - total_variation: 119605.9766 - ssim_multiscale: 0.1084 - sharpdiff: 4.1500 - mean_absolute_error: 0.7340 - mean_squared_error: 0.6166 - val_loss: 2.6114 - val_psnr: 2.2496 - val_total_variation: 33987.6016 - val_ssim_multiscale: 0.0466 - val_sharpdiff: 7.8493 - val_mean_absolute_error: 0.7060 - val_mean_squared_error: 0.5997\n","Epoch 9/1000000\n","\n","Epoch 00009: loss did not improve from 2.53051\n","5000/5000 - 603s - loss: 2.5537 - psnr: 2.1393 - total_variation: 119298.8047 - ssim_multiscale: 0.1060 - sharpdiff: 4.1604 - mean_absolute_error: 0.7315 - mean_squared_error: 0.6137 - val_loss: 2.6287 - val_psnr: 2.2876 - val_total_variation: 32464.9336 - val_ssim_multiscale: 0.2710 - val_sharpdiff: 8.0284 - val_mean_absolute_error: 0.7035 - val_mean_squared_error: 0.5965\n","Epoch 10/1000000\n","\n","Epoch 00010: loss did not improve from 2.53051\n","5000/5000 - 602s - loss: 2.5349 - psnr: 2.1215 - total_variation: 119497.1016 - ssim_multiscale: 0.1054 - sharpdiff: 4.1566 - mean_absolute_error: 0.7335 - mean_squared_error: 0.6160 - val_loss: 2.3933 - val_psnr: 2.0476 - val_total_variation: 22366.0469 - val_ssim_multiscale: 0.4434 - val_sharpdiff: 8.6913 - val_mean_absolute_error: 0.7317 - val_mean_squared_error: 0.6294\n","Epoch 11/1000000\n","\n","Epoch 00011: loss improved from 2.53051 to 2.52878, saving model to /content/drive/My Drive/Results/pokemonAE_Dense_reconst_psnr/var_save_dir\n","5000/5000 - 605s - loss: 2.5288 - psnr: 2.1157 - total_variation: 119615.9766 - ssim_multiscale: 0.1067 - sharpdiff: 4.1538 - mean_absolute_error: 0.7343 - mean_squared_error: 0.6169 - val_loss: 2.4579 - val_psnr: 2.1234 - val_total_variation: 25516.5352 - val_ssim_multiscale: 0.2666 - val_sharpdiff: 8.4825 - val_mean_absolute_error: 0.7254 - val_mean_squared_error: 0.6183\n","Epoch 00011: early stopping\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["<tensorflow.python.keras.callbacks.History at 0x7f318b750c50>"]},"metadata":{"tags":[]},"execution_count":40}]},{"cell_type":"markdown","metadata":{"id":"VkMSnDnoIaCn"},"source":[""]},{"cell_type":"markdown","metadata":{"id":"UhSTW1KSQeC_"},"source":["# Model Evaluation"]},{"cell_type":"markdown","metadata":{"id":"hCPgsBp9QeDA"},"source":["## inception_score"]},{"cell_type":"code","metadata":{"id":"w0wPQHi0QeDB"},"source":["from evaluation.generativity_metrics.inception_metrics import inception_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"7c7I66B9QeDF","executionInfo":{"status":"ok","timestamp":1604310522741,"user_tz":-60,"elapsed":23302021,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"c2339433-2a53-44da-c742-91431b6596c8","colab":{"base_uri":"https://localhost:8080/"}},"source":["is_mean, is_sigma = inception_score(ae, tolerance_threshold=1e-6, max_iteration=300)\n","print(f'inception_score mean: {is_mean.compute()}, sigma: {is_sigma.compute()}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5\n","87916544/87910968 [==============================] - 1s 0us/step\n","calculating the inception_score mean ...\n","WARNING:tensorflow:Model was constructed with shape (None, 75, 75, 3) for input Tensor(\"input_1:0\", shape=(None, 75, 75, 3), dtype=float32), but it was called on an input with incompatible shape (None, 100, 100, 3).\n"],"name":"stdout"},{"output_type":"stream","text":["300it [2:20:39, 27.53s/it]"],"name":"stderr"},{"output_type":"stream","text":["calculating the inception_score sigma ...\n"],"name":"stdout"},{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/dask/array/routines.py:780: RuntimeWarning: Degrees of freedom <= 0 for slice\n","  warnings.warn(\"Degrees of freedom <= 0 for slice\", RuntimeWarning)\n","0it [00:00, ?it/s]/usr/local/lib/python3.6/dist-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide\n","  return func(*(_execute_task(a, cache) for a in args))\n","1it [00:27, 27.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","2it [00:54, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","3it [01:21, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","4it [01:48, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","5it [02:16, 27.31s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","6it [02:43, 27.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","7it [03:10, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","8it [03:38, 27.36s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","9it [04:05, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","10it [04:32, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","11it [04:59, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","12it [05:26, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","13it [05:53, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","14it [06:20, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","15it [06:47, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","16it [07:14, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","17it [07:41, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","18it [08:08, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","19it [08:35, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","20it [09:03, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","21it [09:30, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","22it [09:56, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","23it [10:24, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","24it [10:51, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","25it [11:18, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","26it [11:44, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","27it [12:11, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","28it [12:39, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","29it [13:06, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","30it [13:33, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","31it [14:00, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","32it [14:27, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","33it [14:55, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","34it [15:22, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","35it [15:49, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","36it [16:17, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","37it [16:44, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","38it [17:11, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","39it [17:38, 27.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","40it [18:06, 27.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","41it [18:33, 27.28s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","42it [19:00, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","43it [19:27, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","44it [19:54, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","45it [20:21, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","46it [20:48, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","47it [21:15, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","48it [21:42, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","49it [22:10, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","50it [22:36, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","51it [23:04, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","52it [23:30, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","53it [23:58, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","54it [24:25, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","55it [24:52, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","56it [25:19, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","57it [25:46, 27.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","58it [26:13, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","59it [26:41, 27.27s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","60it [27:08, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","61it [27:35, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","63it [28:29, 27.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","64it [28:57, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","65it [29:24, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","66it [29:51, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","67it [30:18, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","68it [30:45, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","69it [31:12, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","70it [31:39, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","71it [32:06, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","72it [32:34, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","73it [33:01, 27.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","74it [33:28, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","75it [33:55, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","76it [34:23, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","77it [34:50, 27.37s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","78it [35:17, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","79it [35:44, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","80it [36:11, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","81it [36:38, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","82it [37:05, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","83it [37:32, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","84it [37:59, 26.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","85it [38:25, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","86it [38:52, 26.90s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","87it [39:20, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","88it [39:47, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","89it [40:14, 27.05s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","90it [40:41, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","91it [41:08, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","92it [41:35, 27.17s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","93it [42:02, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","94it [42:30, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","95it [42:57, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","96it [43:24, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","97it [43:52, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","98it [44:19, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","99it [44:46, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","100it [45:13, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","101it [45:40, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","102it [46:07, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","103it [46:34, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","104it [47:01, 27.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","105it [47:28, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","106it [47:56, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","107it [48:23, 27.21s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","108it [48:50, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","109it [49:17, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","110it [49:44, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","111it [50:11, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","112it [50:38, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","113it [51:05, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","114it [51:32, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","115it [52:00, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","116it [52:27, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","117it [52:54, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","118it [53:20, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","119it [53:48, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","120it [54:15, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","121it [54:42, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","122it [55:09, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","123it [55:37, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","124it [56:04, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","125it [56:30, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","126it [56:58, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","127it [57:24, 26.94s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","128it [57:51, 26.87s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","129it [58:18, 26.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","130it [58:45, 26.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","131it [59:11, 26.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","132it [59:39, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","133it [1:00:07, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","134it [1:00:35, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","135it [1:01:02, 27.53s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","136it [1:01:30, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","137it [1:01:58, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","138it [1:02:25, 27.60s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","139it [1:02:53, 27.68s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","140it [1:03:21, 27.72s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","141it [1:03:49, 27.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","142it [1:04:17, 27.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","143it [1:04:44, 27.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","144it [1:05:12, 27.55s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","145it [1:05:39, 27.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","146it [1:06:07, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","147it [1:06:35, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","148it [1:07:02, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","149it [1:07:29, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","150it [1:07:56, 27.40s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","151it [1:08:24, 27.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","152it [1:08:51, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","153it [1:09:18, 27.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","154it [1:09:45, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","155it [1:10:12, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","156it [1:10:39, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","157it [1:11:06, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","158it [1:11:33, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","159it [1:12:00, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","160it [1:12:27, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","161it [1:12:54, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","162it [1:13:22, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","163it [1:13:49, 27.16s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","164it [1:14:15, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","165it [1:14:43, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","166it [1:15:09, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","167it [1:15:36, 26.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","168it [1:16:03, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","169it [1:16:31, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","170it [1:16:57, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","171it [1:17:24, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","172it [1:17:51, 26.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","173it [1:18:18, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","174it [1:18:45, 26.91s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","175it [1:19:12, 26.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","176it [1:19:38, 26.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","177it [1:20:05, 26.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","178it [1:20:32, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","179it [1:20:59, 26.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","180it [1:21:26, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","181it [1:21:53, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","182it [1:22:20, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","183it [1:22:47, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","184it [1:23:14, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","185it [1:23:41, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","186it [1:24:09, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","187it [1:24:36, 27.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","188it [1:25:03, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","189it [1:25:30, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","190it [1:25:57, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","191it [1:26:24, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","192it [1:26:51, 27.11s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","193it [1:27:18, 27.15s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","194it [1:27:45, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","195it [1:28:12, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","196it [1:28:39, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","197it [1:29:06, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","198it [1:29:33, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","199it [1:30:00, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","200it [1:30:27, 26.93s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","201it [1:30:54, 27.08s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","202it [1:31:22, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","203it [1:31:49, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","204it [1:32:16, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","205it [1:32:43, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","206it [1:33:10, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","207it [1:33:37, 26.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","208it [1:34:04, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","209it [1:34:31, 26.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","210it [1:34:58, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","211it [1:35:24, 26.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","212it [1:35:51, 26.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","213it [1:36:18, 26.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","214it [1:36:46, 27.03s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","215it [1:37:12, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","216it [1:37:40, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","217it [1:38:07, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","218it [1:38:34, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","219it [1:39:01, 27.10s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","220it [1:39:28, 27.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","221it [1:39:55, 27.12s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","222it [1:40:22, 27.13s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","223it [1:40:49, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","224it [1:41:16, 27.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","225it [1:41:43, 26.98s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","226it [1:42:10, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","227it [1:42:37, 27.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","228it [1:43:04, 27.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","229it [1:43:31, 27.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","230it [1:43:58, 27.07s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","231it [1:44:26, 27.20s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","232it [1:44:53, 27.14s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","233it [1:45:21, 27.33s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","234it [1:45:49, 27.61s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","235it [1:46:16, 27.58s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","236it [1:46:44, 27.51s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","237it [1:47:11, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","238it [1:47:39, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","239it [1:48:06, 27.34s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","240it [1:48:33, 27.46s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","241it [1:49:01, 27.48s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","242it [1:49:29, 27.52s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","243it [1:49:56, 27.43s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","244it [1:50:24, 27.63s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","245it [1:50:52, 27.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","246it [1:51:19, 27.65s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","247it [1:51:47, 27.74s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","248it [1:52:15, 27.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","249it [1:52:43, 27.85s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","250it [1:53:11, 27.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","251it [1:53:39, 27.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","252it [1:54:07, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","253it [1:54:36, 28.09s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","254it [1:55:03, 28.02s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","255it [1:55:31, 27.96s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","256it [1:55:59, 27.82s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","257it [1:56:27, 27.88s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","258it [1:56:55, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","259it [1:57:23, 27.89s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","260it [1:57:50, 27.90s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","261it [1:58:18, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","262it [1:58:46, 27.84s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","263it [1:59:14, 27.78s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","264it [1:59:41, 27.64s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","265it [2:00:08, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","266it [2:00:35, 27.44s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","267it [2:01:02, 27.29s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","268it [2:01:30, 27.25s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","269it [2:01:57, 27.18s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","270it [2:02:24, 27.19s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","271it [2:02:51, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","272it [2:03:19, 27.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","273it [2:03:46, 27.23s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","274it [2:04:13, 27.35s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","275it [2:04:41, 27.39s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","276it [2:05:08, 27.30s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","277it [2:05:35, 27.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","278it [2:06:02, 27.22s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","279it [2:06:29, 27.24s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","280it [2:06:57, 27.26s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","281it [2:07:24, 27.32s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","282it [2:07:52, 27.49s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","283it [2:08:20, 27.59s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","284it [2:08:48, 27.62s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","285it [2:09:15, 27.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","286it [2:09:43, 27.73s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","287it [2:10:11, 27.81s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","288it [2:10:39, 27.70s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","289it [2:11:06, 27.71s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","290it [2:11:34, 27.79s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","291it [2:12:02, 27.86s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","292it [2:12:31, 27.92s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","293it [2:12:59, 27.97s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","294it [2:13:27, 28.01s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","295it [2:13:55, 27.95s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","296it [2:14:23, 28.06s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","297it [2:14:51, 27.99s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","298it [2:15:19, 28.04s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","299it [2:15:47, 28.00s/it]/usr/local/lib/python3.6/dist-packages/dask/array/core.py:3967: RuntimeWarning: invalid value encountered in double_scalars\n","  result = function(*args, **kwargs)\n","300it [2:16:15, 28.07s/it]"],"name":"stderr"},{"output_type":"stream","text":["inception_score mean: [1.4813654e+186], sigma: inf\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"Qk6qBylRQeDJ"},"source":["\n","## Frechet_inception_distance\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"t54Qm7_FQeDK"},"source":["from evaluation.generativity_metrics.inception_metrics import frechet_inception_distance"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"p-_KQpVPQeDP"},"source":["fis_score = frechet_inception_distance(ae, train_generator.as_numpy_iterator(), \n","                                       tolerance_threshold=1e-6, \n","                                       max_iteration=300, \n","                                       batch_size=32)\n"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"GtJ1QNcx_rt2"},"source":["print(f'frechet inception distance: {fis_score.compute()}')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"dS4QPAXoQeDX"},"source":["## perceptual_path_length_score"]},{"cell_type":"code","metadata":{"id":"FHxOntNaQeDZ"},"source":["from evaluation.generativity_metrics.perceptual_path_length import perceptual_path_length_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"FtgoCP49QeDj","executionInfo":{"status":"ok","timestamp":1604310816578,"user_tz":-60,"elapsed":23592096,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"7b5a1da4-2ba5-4542-e9f2-3cf73aaddae8","colab":{"base_uri":"https://localhost:8080/"}},"source":["ppl_mean_score = perceptual_path_length_score(ae, train_generator.as_numpy_iterator(), \n","                                              tolerance_threshold=1e-6, \n","                                              max_iteration=300, \n","                                              batch_size=32)\n","print(f'perceptual path length score: {ppl_mean_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5\n","58892288/58889256 [==============================] - 1s 0us/step\n"],"name":"stdout"},{"output_type":"stream","text":["300it [04:51,  1.04it/s]"],"name":"stderr"},{"output_type":"stream","text":["perceptual path length score: 4903.8759765625\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"l6zFWvmtQeDr"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Y8mKKa7hQeDv"},"source":["## precision score"]},{"cell_type":"code","metadata":{"id":"2VF-JOv3QeDx"},"source":["from evaluation.generativity_metrics.precision_recall import precision_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"vT1C64RdQeD5","executionInfo":{"status":"ok","timestamp":1604310817012,"user_tz":-60,"elapsed":23591332,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"f29d45c9-93f0-402b-ccf5-6279f3277c1d","colab":{"base_uri":"https://localhost:8080/"}},"source":["_precision_score = precision_score(ae,  train_generator.as_numpy_iterator(), \n","                                   tolerance_threshold=1e-6, \n","                                   max_iteration=300)\n","print(f'precision score: {_precision_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["\r0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00216508s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.0022409s\n"],"name":"stdout"},{"output_type":"stream","text":["/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n"],"name":"stderr"},{"output_type":"stream","text":["precision score: [0.]\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"M4JbbHnQQeD-"},"source":["## recall score"]},{"cell_type":"code","metadata":{"id":"RhwDYty1QeEA"},"source":["from evaluation.generativity_metrics.precision_recall import recall_score"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LMzfn5KHQeEF","executionInfo":{"status":"ok","timestamp":1604310817349,"user_tz":-60,"elapsed":23589741,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"024612a9-5f00-4efc-ed5a-128182e7531e","colab":{"base_uri":"https://localhost:8080/"}},"source":["_recall_score = recall_score(ae, train_generator.as_numpy_iterator(), tolerance_threshold=1e-6, max_iteration=300)\n","print(f'recall score: {_recall_score}')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","0it [00:00, ?it/s]/content/Generative_Models/evaluation/generativity_metrics/precision_recall.py:84: RuntimeWarning: invalid value encountered in true_divide\n","  realism_score[begin1:end1] = self.D[nearest_indices[begin1:end1], 0] / np.min(distance_batch[0:end1-begin1, :], axis=1)\n","                  "],"name":"stderr"},{"output_type":"stream","text":["Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00245094s\n","Evaluating k-NN precision and recall with 10 samples...\n","Done evaluation in: 0.00246978s\n","recall score: [1.]\n"],"name":"stdout"},{"output_type":"stream","text":["\r"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"nQH-mfDmQeEJ"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"9vPAhxCyQeEQ"},"source":["# Image Generation"]},{"cell_type":"markdown","metadata":{"id":"s5OsqNYaQeES"},"source":["## image reconstruction"]},{"cell_type":"markdown","metadata":{"id":"oEEynQF2QeET"},"source":["### Training dataset"]},{"cell_type":"code","metadata":{"id":"Fg1wGMkRQeEU"},"source":["from training.generators.from_images.image_generation_testing import reconstruct_from_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZSJ55VozQeEZ","executionInfo":{"status":"ok","timestamp":1604310818226,"user_tz":-60,"elapsed":23584759,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"355a3a30-be65-42d7-a1a9-0af49c7e92e4","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 54.14it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"G1_8VcdJQeEl","executionInfo":{"status":"ok","timestamp":1604310818517,"user_tz":-60,"elapsed":23585043,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"0ed94baf-3c8b-40d1-df31-0f85270a52e5","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'reconstruct_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","reconstruct_from_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 38.38it/s]\n"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"id":"iwDP-H8cQeEq"},"source":["## with Randomness"]},{"cell_type":"code","metadata":{"id":"4YXvt2J8QeEr"},"source":["from training.generators.from_images.image_generation_testing import generate_images_like_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Lxr8AimWQeEy","executionInfo":{"status":"ok","timestamp":1604310818523,"user_tz":-60,"elapsed":23585038,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"dadf2205-7608-4a5b-b8f5-71d852d24e91","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_training_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, train_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 41.03it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"VfEeBtsxQeE7","executionInfo":{"status":"ok","timestamp":1604310818858,"user_tz":-60,"elapsed":23585367,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"5876bc3e-5eaf-41b3-f09a-cfd3eb056cb8","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'generate_testing_images_like_a_batch_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_like_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 46.90it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"pHRCUI6eQeFD"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"TdeyPBhtQeFG"},"source":["### Complete Randomness"]},{"cell_type":"code","metadata":{"id":"Tr8JPmloQeFH"},"source":["from training.generators.from_images.image_generation_testing import generate_images_randomly"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"9OZuHVx2QeFK","executionInfo":{"status":"ok","timestamp":1604310819292,"user_tz":-60,"elapsed":23585783,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"90ba66b4-3d81-4fcf-efb0-16c2c43a48c1","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'random_synthetic_dir')\n","create_if_not_exist(save_dir)\n","\n","generate_images_randomly(ae, save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["32it [00:00, 75.75it/s]\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"Jh8HeIbMQeFR"},"source":["from training.generators.from_images.image_generation_testing import interpolate_a_batch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"oKULH_U9QeFW","executionInfo":{"status":"ok","timestamp":1604310820720,"user_tz":-60,"elapsed":23587199,"user":{"displayName":"Mina Atteia","photoUrl":"","userId":"09678414752620549323"}},"outputId":"c302a32e-e0ce-4ac1-b05c-7f42fbe297d6","colab":{"base_uri":"https://localhost:8080/"}},"source":["from utils.data_and_files.file_utils import create_if_not_exist\n","save_dir = os.path.join(experiments_dir, 'interpolate_dir')\n","create_if_not_exist(save_dir)\n","\n","interpolate_a_batch(ae, val_generator.as_numpy_iterator(), save_dir)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["10it [00:00, 117.34it/s]\n","10it [00:00, 133.39it/s]\n","0it [00:00, ?it/s]"],"name":"stderr"},{"output_type":"stream","text":["\n","\n","\n"],"name":"stdout"},{"output_type":"stream","text":["10it [00:00, 123.68it/s]\n","10it [00:00, 124.23it/s]\n","100%|██████████| 4/4 [00:00<00:00, 10.65it/s]\n","10it [00:00, 122.88it/s]\n"],"name":"stderr"},{"output_type":"stream","text":["\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Fuhv1qXyQeFb"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"i0mPqk0UQeFg"},"source":[""],"execution_count":null,"outputs":[]}]}